export const SPELL_ICONS = {
  "Shillelagh": "staff",
  "Vicious Mockery": "lips",
  "Druidcraft": "leaf",
  "Chill Touch": "zombiehand",
  "Dancing Lights": "candle",
  "Mending": "wrench",
  "Light": "lantern",
  "Message": "letter",
  "Thaumaturgy": "sparkle",
  "Guidance": "compass",
  "Spare the Dying": "heartbeat",
  "Silent Image": "frame",
  "Bless": "star",
  "Heroism": "helmet",
  "Longstrider": "boots",
  "Mage Armor": "armor",
  "Hideous Laughter": "mask",
  "Illusory Script": "scroll",
  "Hunter's Mark": "target",
  "Detect Poison and Disease": "toxic",
  "Detect Magic": "sparkle",
  "Faerie Fire": "flame",
  "Identify": "monocle",
  "Entangle": "thorns",
  "Purify Food and Drink": "mug",
  "Feather Fall": "feather",
  "Floating Disk": "disc",
  "Bane": "skull",
  "Expeditious Retreat": "dash",
  "Command": "crown",
  "Jump": "boots",
  "False Life": "heartbeat",
  "Color Spray": "prism",
  "Grease": "drop",
  "Create or Destroy Water": "drop",
  "Alarm": "bell",
  "Sanctuary": "sigil",
  "Goodberry": "herb",
  "Pass without Trace": "footprints",
  "Spiritual Weapon": "mace",
  "Continual Flame": "torch",
  "Suggestion": "spiral",
  "Magic Mouth": "lips",
  "Augury": "bone",
  "Barkskin": "tree",
  "Animal Messenger": "letter",
  "Protection from Poison": "toxic",
  "Zone of Truth": "scales",
  "Moonbeam": "moon",
  "Arcanist's Magic Aura": "sparkle",
  "Arcane Lock": "lock",
  "Magic Weapon": "sword",
  "Lesser Restoration": "medkit",
  "Gentle Repose": "mummy",
  "Detect Thoughts": "brain",
  "Knock": "key",
  "Mirror Image": "mirror",
  "Warding Bond": "ring",
  "Web": "web",
  "Aid": "medkit",
  "Find Traps": "lockpick",
  "Locate Object": "compass",
  "Flaming Sphere": "orb",
  "Blur": "fog",
  "Heat Metal": "hammer",
  "Alter Self": "mask",
  "Darkvision": "eye2",
  "Enlarge/Reduce": "arrow",
  "Enhance Ability": "upgrade",
  "Calm Emotions": "charmed",
  "Spike Growth": "thorns",
  "Revivify": "heartbeat",
  "Gaseous Form": "smoke",
  "Hypnotic Pattern": "spiral",
  "Spirit Guardians": "ghost",
  "Slow": "hourglass",
  "Counterspell": "antimagic",
  "Tiny Hut": "tent",
  "Magic Circle": "sigil",
  "Beacon of Hope": "lantern",
  "Blink": "ghost",
  "Nondetection": "blind",
  "Major Image": "frame",
  "Glyph of Warding": "rune",
  "Water Breathing": "fish",
  "Clairvoyance": "crystalball",
  "Phantom Steed": "ghost",
  "Vampiric Touch": "fang",
  "Feign Death": "coffin",
  "Speak with Plants": "herb",
  "Dispel Magic": "antimagic",
  "Meld into Stone": "rock",
  "Remove Curse": "sparkle",
  "Create Food and Water": "bread",
  "Wind Wall": "wind",
  "Haste": "lightning2",
  "Water Walk": "wave",
  "Faithful Hound": "paw",
  "Hallucinatory Terrain": "mountain",
  "Giant Insect": "bug",
  "Death Ward": "coffin",
  "Banishment": "portal",
  "Fabricate": "hammer",
  "Stone Shape": "rock",
  "Control Water": "wave",
  "Private Sanctum": "rook",
  "Arcane Eye": "eye2",
  "Fire Shield": "shield",
  "Dimension Door": "door",
  "Locate Creature": "compass",
  "Secret Chest": "chest",
  "Polymorph": "paw",
  "Phantasmal Killer": "scared",
  "Conjure Woodland Beings": "tree",
  "Compulsion": "chain",
  "Freedom of Movement": "dash",
  "Confusion": "spiral",
  "Guardian of Faith": "helmet",
  "Black Tentacles": "tentacle",
  "Tree Stride": "tree",
  "Contagion": "toxic",
  "Legend Lore": "book",
  "Scrying": "mirror",
  "Insect Plague": "bug",
  "Geas": "scroll",
  "Commune": "candle",
  "Commune with Nature": "tree",
  "Raise Dead": "heartbeat",
  "Animate Objects": "wand",
  "Planar Binding": "chain",
  "Antilife Shell": "bubble",
  "Seeming": "mask",
  "Awaken": "tree",
  "Dispel Evil and Good": "sun",
  "Reincarnate": "spiral",
  "Contact Other Plane": "planet",
  "Hallow": "sigil",
  "Wall of Force": "force",
  "Dream": "moon",
  "Passwall": "door",
  "Creation": "wand",
  "Telekinesis": "hand",
  "Telepathic Bond": "brain",
  "Mislead": "people",
  "Arcane Hand": "hand",
  "Magic Jar": "flask",
  "Forbiddance": "sigil",
  "True Seeing": "eye2",
  "Instant Summons": "hand",
  "Mass Suggestion": "spiral",
  "Flesh to Stone": "rock",
  "Guards and Wards": "rook",
  "Move Earth": "mountain",
  "Heroes' Feast": "meat",
  "Find the Path": "compass",
  "Conjure Fey": "wings",
  "Programmed Illusion": "frame",
  "Transport via Plants": "tree",
  "Eyebite": "eye",
  "Word of Recall": "portal",
  "Blade Barrier": "swords",
  "Wall of Thorns": "thorns",
  "Contingency": "hourglass",
  "Magnificent Mansion": "rook",
  "Mirage Arcane": "mountain",
  "Resurrection": "sunrise",
  "Sequester": "lock",
  "Arcane Sword": "sword",
  "Reverse Gravity": "planet",
  "Delayed Blast Fireball": "bomb",
  "Finger of Death": "reaper",
  "Simulacrum": "mirror",
  "Conjure Celestial": "sun",
  "Project Image": "frame",
  "Prismatic Spray": "prism",
  "Symbol": "rune",
  "Teleport": "portal",
  "Plane Shift": "portal",
  "Antipathy/Sympathy": "charmed",
  "Control Weather": "storm",
  "Incendiary Cloud": "smoke",
  "Demiplane": "door",
  "Earthquake": "mountain",
  "Clone": "people",
  "Glibness": "lips",
  "Maze": "maze",
  "Dominate Monster": "crown",
  "Antimagic Field": "antimagic",
  "Holy Aura": "sun",
  "Power Word Stun": "stunned",
  "Imprisonment": "cage",
  "Wish": "star",
  "True Resurrection": "sunrise",
  "True Polymorph": "dragon",
  "Meteor Swarm": "constellation",
  "Time Stop": "hourglass",
  "Foresight": "crystalball",
  "Prismatic Wall": "prism",
  "Power Word Kill": "reaper",
  "Weird": "scared"
};

export const FEATURE_ICONS = {
  "Rage": "fist",
  "Unarmored Defense": "shield",
  "Reckless Attack": "battleaxe",
  "Danger Sense": "eye",
  "Primal Path": "footprints",
  "Frenzy": "flame",
  "Extra Attack": "swords",
  "Extra Attack (2)": "swords",
  "Extra Attack (3)": "swords",
  "Fast Movement": "dash",
  "Mindless Rage": "brain",
  "Feral Instinct": "paw",
  "Brutal Critical": "d20",
  "Intimidating Presence": "scared",
  "Relentless Rage": "heartbeat",
  "Retaliation": "swords",
  "Persistent Rage": "flame",
  "Indomitable Might": "fist",
  "Primal Champion": "crown",
  "Spellcasting": "wand",
  "Bardic Inspiration": "lute",
  "Jack of All Trades": "juggle",
  "Song of Rest": "music",
  "Bard College": "lute",
  "Expertise": "upgrade",
  "Bonus Proficiencies": "wrench",
  "Bonus Proficiency": "wrench",
  "Cutting Words": "lips",
  "Font of Inspiration": "lute",
  "Countercharm": "music",
  "Additional Magical Secrets": "book",
  "Magical Secrets": "book",
  "Peerless Skill": "star",
  "Superior Inspiration": "music",
  "Divine Domain": "sun",
  "Life Domain Spells": "heart",
  "Disciple of Life": "heart",
  "Channel Divinity": "sun",
  "Channel Divinity: Turn Undead": "reaper",
  "Channel Divinity: Preserve Life": "heartbeat",
  "Destroy Undead": "reaper",
  "Blessed Healer": "medkit",
  "Divine Strike": "mace",
  "Divine Intervention": "sunrise",
  "Supreme Healing": "heart",
  "Druidic": "leaf",
  "Wild Shape": "paw",
  "Druid Circle": "tree",
  "Bonus Cantrip": "sparkle",
  "Natural Recovery": "herb",
  "Circle Spells": "tree",
  "Circle Spells: Arctic": "snow",
  "Circle Spells: Coast": "wave",
  "Circle Spells: Desert": "sun",
  "Circle Spells: Forest": "tree",
  "Circle Spells: Grassland": "herb",
  "Circle Spells: Mountain": "mountain",
  "Circle Spells: Swamp": "toxic",
  "Circle Spells: Underdark": "mushroom",
  "Land's Stride": "footprints",
  "Nature's Ward": "leaf",
  "Nature's Sanctuary": "tree",
  "Timeless Body": "hourglass",
  "Beast Spells": "paw",
  "Archdruid": "crown",
  "Fighting Style": "swords",
  "Additional Fighting Style": "swords",
  "Second Wind": "heartbeat",
  "Action Surge": "lightning2",
  "Martial Archetype": "helmet",
  "Improved Critical": "d20",
  "Superior Critical": "d20",
  "Remarkable Athlete": "dash",
  "Indomitable": "shield",
  "Survivor": "heartbeat",
  "Martial Arts": "fist",
  "Ki": "yinyang",
  "Flurry of Blows": "fist",
  "Patient Defense": "shield",
  "Step of the Wind": "wind",
  "Unarmored Movement": "dash",
  "Monastic Tradition": "yinyang",
  "Deflect Missiles": "arrow",
  "Open Hand Technique": "hand",
  "Slow Fall": "feather",
  "Stunning Strike": "stunned",
  "Ki-Empowered Strikes": "fist",
  "Wholeness of Body": "heart",
  "Evasion": "dash",
  "Stillness of Mind": "brain",
  "Purity of Body": "toxic",
  "Tranquility": "yinyang",
  "Tongue of the Sun and Moon": "letter",
  "Diamond Soul": "gem",
  "Quivering Palm": "hand",
  "Empty Body": "invisible",
  "Perfect Self": "yinyang",
  "Divine Sense": "eye",
  "Lay on Hands": "hand",
  "Divine Smite": "sun",
  "Divine Health": "heart",
  "Sacred Oath": "scroll",
  "Oath Spells": "scroll",
  "Channel Divinity: Sacred Weapon": "sword",
  "Channel Divinity: Turn the Unholy": "sun",
  "Aura of Protection": "shield",
  "Aura of Devotion": "charmed",
  "Aura of Courage": "helmet",
  "Improved Divine Smite": "sun",
  "Cleansing Touch": "hand",
  "Purity of Spirit": "sun",
  "Holy Nimbus": "sunrise",
  "Favored Enemy": "target",
  "Natural Explorer": "compass",
  "Ranger Archetype": "bow",
  "Primeval Awareness": "eye",
  "Hunter's Prey": "target",
  "Hunter's Prey: Colossus Slayer": "target",
  "Hunter's Prey: Giant Killer": "axe",
  "Hunter's Prey: Horde Breaker": "swords",
  "Defensive Tactics": "shield",
  "Defensive Tactics: Escape the Horde": "dash",
  "Defensive Tactics: Multiattack Defense": "shield",
  "Defensive Tactics: Steel Will": "scared",
  "Hide in Plain Sight": "mask",
  "Multiattack": "quiver",
  "Multiattack: Volley": "quiver",
  "Multiattack: Whirlwind Attack": "tornado",
  "Vanish": "invisible",
  "Superior Hunter's Defense": "shield",
  "Superior Hunter's Defense: Evasion": "dash",
  "Superior Hunter's Defense: Stand Against the Tide": "wave",
  "Superior Hunter's Defense: Uncanny Dodge": "shield",
  "Feral Senses": "eye",
  "Foe Slayer": "target",
  "Sneak Attack": "dagger",
  "Thieves' Cant": "letter",
  "Cunning Action": "dash",
  "Roguish Archetype": "mask",
  "Fast Hands": "hand",
  "Second-Story Work": "rope",
  "Uncanny Dodge": "shield",
  "Supreme Sneak": "footprints",
  "Reliable Talent": "star",
  "Use Magic Device": "wand",
  "Blindsense": "deaf",
  "Slippery Mind": "brain",
  "Thief's Reflexes": "lightning2",
  "Elusive": "ghost",
  "Stroke of Luck": "d20",
  "Sorcerous Origin": "flame",
  "Dragon Ancestor": "dragon",
  "Draconic Resilience": "armor",
  "Font of Magic": "crystal",
  "Metamagic": "spiral",
  "Careful Spell": "shield",
  "Distant Spell": "target",
  "Empowered Spell": "force",
  "Extended Spell": "hourglass",
  "Heightened Spell": "upgrade",
  "Quickened Spell": "lightning2",
  "Subtle Spell": "invisible",
  "Twinned Spell": "people",
  "Elemental Affinity": "flame",
  "Dragon Wings": "wings",
  "Draconic Presence": "dragon",
  "Sorcerous Restoration": "crystal",
  "Otherworldly Patron": "pact",
  "Pact Magic": "pact",
  "Expanded Spell List": "book",
  "Dark One's Blessing": "heartbeat",
  "Pact of the Chain": "chain",
  "Pact of the Blade": "sword",
  "Pact of the Tome": "book",
  "Dark One's Own Luck": "d20",
  "Fiendish Resilience": "horns",
  "Mystic Arcanum": "constellation",
  "Hurl Through Hell": "flame",
  "Eldritch Master": "crown",
  "Arcane Recovery": "book",
  "Arcane Tradition": "book",
  "Evocation Savant": "scroll",
  "Sculpt Spells": "orb",
  "Potent Cantrip": "force",
  "Empowered Evocation": "force",
  "Overchannel": "lightning2",
  "Spell Mastery": "star",
  "Signature Spells": "quill",
  "Archery": "bow",
  "Defense": "armor",
  "Dueling": "sword",
  "Great Weapon Fighting": "battleaxe",
  "Protection": "shield",
  "Two-Weapon Fighting": "dagger",
  "Grappler": "fist",
  "Shelter of the Faithful": "candle",
  "Ability Score Increase": "upgrade",
  "Size, Speed, Languages": "user",
  "Darkvision": "moon",
  "Gnome Cunning": "brain",
  "Artificer's Lore": "book",
  "Tinker": "gear",
  "Dwarven Resilience": "toxic",
  "Dwarven Combat Training": "axe",
  "Tool Proficiency": "hammer",
  "Stonecunning": "rock",
  "Dwarven Toughness": "heartbeat",
  "Draconic Ancestry": "dragon",
  "Breath Weapon": "flame",
  "Damage Resistance": "shield",
  "Menacing": "scared",
  "Relentless Endurance": "heartbeat",
  "Savage Attacks": "d20",
  "Lucky": "d20",
  "Brave": "helmet",
  "Halfling Nimbleness": "dash",
  "Naturally Stealthy": "footprints",
  "Fey Ancestry": "wings",
  "Skill Versatility": "juggle",
  "Hellish Resistance": "flame",
  "Infernal Legacy": "horns",
  "Keen Senses": "eye",
  "Trance": "moon",
  "Elf Weapon Training": "bow",
  "Cantrip": "sparkle",
  "Extra Language": "letter"
};

export const INVOCATION_ICONS = {
  "Мучительный заряд": "force",
  "Доспех теней": "armor",
  "Шаг вознесения": "wings",
  "Язык зверей": "paw",
  "Чарующее влияние": "charmed",
  "Колдовской шёпот": "lips",
  "Книга древних тайн": "book",
  "Цепи Карцери": "chain",
  "Взор дьявола": "eye2",
  "Страшное слово": "scared",
  "Мистическое зрение": "sparkle",
  "Мистическое копьё": "spear",
  "Глаза хранителя рун": "rune",
  "Дьявольская живучесть": "heartbeat",
  "Взгляд двух разумов": "brain",
  "Пьющий жизнь": "fang",
  "Маска многих лиц": "mask",
  "Мастер множества обличий": "mask",
  "Приспешники хаоса": "tentacle",
  "Трясина разума": "hourglass",
  "Туманные видения": "fog",
  "Единство с тенями": "moon",
  "Потусторонний прыжок": "boots",
  "Отталкивающий заряд": "wind",
  "Ваятель плоти": "paw",
  "Знак дурного предзнаменования": "skull",
  "Похититель пяти судеб": "d20",
  "Жаждущий клинок": "sword",
  "Видения далёких миров": "planet",
  "Голос повелителя цепи": "letter",
  "Шёпот могилы": "coffin",
  "Ведьмин взор": "eye"
};

const lower = s => String(s || "").trim().toLowerCase().replace(/ё/g, "е");
const INV_BY_NAME = new Map(Object.entries(INVOCATION_ICONS).map(([k, v]) => [lower(k), v]));

export function spellIconByName(sp) {
  return SPELL_ICONS[String((sp && sp.nameEn) || "").trim()] || "";
}

export function featureIconByName(f) {
  if (!f) return "";
  const en = String(f.nameEn || "").trim();
  if (en && FEATURE_ICONS[en]) return FEATURE_ICONS[en];
  if (en.includes(":") && FEATURE_ICONS[en.split(":")[0].trim()]) return FEATURE_ICONS[en.split(":")[0].trim()];
  return INV_BY_NAME.get(lower(f.name)) || "";
}
