export const SPELL_ICONS = {
  "Acid Splash": "gi/sbed/splash",
  "Mage Hand": "gi/lorc/magic-palm",
  "Shillelagh": "gi/delapouite/wood-club",
  "Vicious Mockery": "gi/lorc/sharp-lips",
  "Druidcraft": "gi/lorc/sprout",
  "Chill Touch": "gi/delapouite/skeletal-hand",
  "Ray of Frost": "gi/lorc/ringed-beam",
  "Minor Illusion": "gi/delapouite/magick-trick",
  "Eldritch Blast": "gi/lorc/unstable-projectile",
  "Fire Bolt": "gi/lorc/fire-dash",
  "Dancing Lights": "gi/lorc/triorb",
  "Mending": "gi/lorc/sewing-needle",
  "Light": "gi/lorc/lantern-flame",
  "Sacred Flame": "gi/delapouite/fire-shrine",
  "Message": "gi/delapouite/chat-bubble",
  "Resistance": "gi/lorc/checked-shield",
  "Produce Flame": "gi/lorc/fluffy-flame",
  "Guidance": "gi/delapouite/polar-star",
  "Spare the Dying": "gi/delapouite/heart-beats",
  "Prestidigitation": "gi/lorc/fairy-wand",
  "Thaumaturgy": "gi/lorc/sonic-shout",
  "Shocking Grasp": "gi/delapouite/bolt-spell-cast",
  "Poison Spray": "gi/lorc/bottle-vapors",
  "Hellish Rebuke": "gi/lorc/unfriendly-fire",
  "Silent Image": "gi/delapouite/wood-frame",
  "Bless": "gi/lorc/spiked-halo",
  "Divine Favor": "gi/lorc/shining-sword",
  "Thunderwave": "gi/lorc/sonic-boom",
  "Magic Missile": "gi/lorc/striking-arrows",
  "Heroism": "gi/delapouite/spartan-helmet",
  "Longstrider": "gi/lorc/walking-boot",
  "Mage Armor": "gi/lorc/breastplate",
  "Animal Friendship": "gi/lorc/paw-heart",
  "Hideous Laughter": "gi/lorc/imp-laugh",
  "Protection from Evil and Good": "gi/delapouite/cross-shield",
  "Illusory Script": "gi/lorc/scroll-unfurled",
  "Healing Word": "gi/delapouite/heart-wings",
  "Cure Wounds": "gi/lorc/glowing-hands",
  "Disguise Self": "gi/lorc/drama-masks",
  "Hunter's Mark": "gi/sbed/targeted",
  "Inflict Wounds": "gi/lorc/ragged-wound",
  "Guiding Bolt": "gi/delapouite/falling-star",
  "Unseen Servant": "gi/delapouite/broom",
  "Detect Poison and Disease": "gi/lorc/poison-bottle",
  "Detect Evil and Good": "gi/lorc/templar-eye",
  "Detect Magic": "gi/lorc/shiny-iris",
  "Burning Hands": "gi/lorc/fire-wave",
  "Faerie Fire": "gi/delapouite/sparkles",
  "Identify": "gi/delapouite/lorgnette",
  "Entangle": "gi/lorc/curling-vines",
  "Charm Person": "gi/lorc/charm",
  "Purify Food and Drink": "gi/lorc/chalice-drops",
  "Feather Fall": "gi/lorc/feather",
  "Floating Disk": "gi/delapouite/floating-platforms",
  "Find Familiar": "gi/lorc/owl",
  "Comprehend Languages": "gi/delapouite/zigzag-hieroglyph",
  "Bane": "gi/lorc/cursed-star",
  "Expeditious Retreat": "gi/lorc/winged-leg",
  "Command": "gi/lorc/pointing",
  "Jump": "gi/delapouite/jump-across",
  "False Life": "gi/lorc/glass-heart",
  "Speak with Animals": "gi/lorc/wolf-howl",
  "Color Spray": "gi/lorc/expanded-rays",
  "Grease": "gi/lorc/spill",
  "Create or Destroy Water": "gi/lorc/droplets",
  "Alarm": "gi/lorc/ringing-bell",
  "Fog Cloud": "gi/delapouite/fog",
  "Sanctuary": "gi/delapouite/slumbering-sanctuary",
  "Sleep": "gi/delapouite/night-sleep",
  "Goodberry": "gi/delapouite/raspberry",
  "Shield": "gi/lorc/magic-shield",
  "Shield of Faith": "gi/delapouite/templar-shield",
  "Pass without Trace": "gi/lorc/boot-prints",
  "Spiritual Weapon": "gi/delapouite/flanged-mace",
  "Rope Trick": "gi/delapouite/rope-coil",
  "Continual Flame": "gi/delapouite/torch",
  "See Invisibility": "gi/delapouite/extra-vision",
  "Suggestion": "gi/lorc/spiral-bloom",
  "Magic Mouth": "gi/lorc/lips",
  "Augury": "gi/caro-asercion/tarot-10-wheel-of-fortune",
  "Shatter": "gi/lorc/shattered-glass",
  "Barkskin": "gi/delapouite/log",
  "Animal Messenger": "gi/lorc/dove",
  "Protection from Poison": "gi/seregacthtuf/acid-shield",
  "Zone of Truth": "gi/lorc/scales",
  "Acid Arrow": "gi/lorc/chemical-arrow",
  "Levitate": "gi/lorc/lift",
  "Moonbeam": "gi/lorc/concentric-crescents",
  "Ray of Enfeeblement": "gi/lorc/beam-wake",
  "Arcanist's Magic Aura": "gi/lorc/magic-swirl",
  "Arcane Lock": "gi/lorc/padlock",
  "Magic Weapon": "gi/lorc/rune-sword",
  "Lesser Restoration": "gi/delapouite/remedy",
  "Prayer of Healing": "gi/lorc/prayer",
  "Invisibility": "gi/delapouite/invisible",
  "Gentle Repose": "gi/delapouite/sarcophagus",
  "Detect Thoughts": "gi/lorc/brain",
  "Knock": "gi/lorc/unlocking",
  "Mirror Image": "gi/lorc/two-shadows",
  "Warding Bond": "gi/lorc/linked-rings",
  "Enthrall": "gi/delapouite/public-speaker",
  "Scorching Ray": "gi/lorc/fire-ray",
  "Web": "gi/lorc/spider-web",
  "Spider Climb": "gi/lorc/hanging-spider",
  "Aid": "gi/zeromancer/heart-plus",
  "Locate Animals or Plants": "gi/darkzaitzev/plants-and-animals",
  "Find Traps": "gi/lorc/wolf-trap",
  "Locate Object": "gi/lorc/compass",
  "Find Steed": "gi/skoll/chess-knight",
  "Gust of Wind": "gi/lorc/wind-slap",
  "Flame Blade": "gi/lorc/sparkling-sabre",
  "Flaming Sphere": "gi/lorc/burning-dot",
  "Blur": "gi/lorc/dodging",
  "Heat Metal": "gi/delapouite/melting-metal",
  "Blindness/Deafness": "gi/delapouite/blindfold",
  "Alter Self": "gi/lorc/inner-self",
  "Darkvision": "gi/delapouite/night-vision",
  "Silence": "gi/delapouite/silenced",
  "Misty Step": "gi/lorc/teleport",
  "Darkness": "gi/lorc/spiky-eclipse",
  "Enlarge/Reduce": "gi/delapouite/resize",
  "Hold Person": "gi/delapouite/frozen-body",
  "Enhance Ability": "gi/delapouite/upgrade",
  "Calm Emotions": "gi/lorc/lotus",
  "Spike Growth": "gi/delapouite/spiky-pit",
  "Revivify": "gi/lorc/shining-heart",
  "Animate Dead": "gi/skoll/raise-skeleton",
  "Gaseous Form": "gi/delapouite/steam",
  "Hypnotic Pattern": "gi/lorc/twirl-center",
  "Daylight": "gi/lorc/sun",
  "Spirit Guardians": "gi/lorc/ghost-ally",
  "Slow": "gi/lorc/snail",
  "Protection from Energy": "gi/lorc/energy-shield",
  "Stinking Cloud": "gi/sbed/poison-cloud",
  "Counterspell": "gi/lorc/interdiction",
  "Tiny Hut": "gi/delapouite/camping-tent",
  "Magic Circle": "gi/skoll/pentacle",
  "Beacon of Hope": "gi/delapouite/lighthouse",
  "Blink": "gi/delapouite/elysium-shade",
  "Sleet Storm": "gi/lorc/snowing",
  "Mass Healing Word": "gi/delapouite/nested-hearts",
  "Lightning Bolt": "gi/lorc/heavy-lightning",
  "Nondetection": "gi/lorc/eye-shield",
  "Major Image": "gi/delapouite/mona-lisa",
  "Fireball": "gi/lorc/bright-explosion",
  "Glyph of Warding": "gi/delapouite/rub-el-hizb",
  "Water Breathing": "gi/lorc/angler-fish",
  "Clairvoyance": "gi/lorc/crystal-ball",
  "Fly": "gi/lorc/feathered-wing",
  "Sending": "gi/lorc/envelope",
  "Phantom Steed": "gi/delapouite/horseshoe",
  "Conjure Animals": "gi/lorc/direwolf",
  "Call Lightning": "gi/lorc/thunder-struck",
  "Vampiric Touch": "gi/lorc/life-tap",
  "Feign Death": "gi/lorc/coffin",
  "Bestow Curse": "gi/lorc/voodoo-doll",
  "Speak with Dead": "gi/lorc/skull-in-jar",
  "Speak with Plants": "gi/lorc/ent-mouth",
  "Dispel Magic": "gi/lorc/fission",
  "Plant Growth": "gi/delapouite/tree-growth",
  "Meld into Stone": "gi/delapouite/menhir",
  "Remove Curse": "gi/skoll/breaking-chain",
  "Create Food and Water": "gi/delapouite/cornucopia",
  "Wind Wall": "gi/lorc/windy-stripes",
  "Fear": "gi/lorc/terror",
  "Haste": "gi/lorc/sprint",
  "Water Walk": "gi/lorc/wave-crest",
  "Tongues": "gi/lorc/conversation",
  "Faithful Hound": "gi/lorc/hound",
  "Greater Invisibility": "gi/lucasms/cloak",
  "Hallucinatory Terrain": "gi/lorc/mountains",
  "Giant Insect": "gi/delapouite/praying-mantis",
  "Ice Storm": "gi/lorc/heavy-rain",
  "Death Ward": "gi/lorc/skull-shield",
  "Banishment": "gi/lorc/magic-portal",
  "Fabricate": "gi/lorc/anvil",
  "Stone Shape": "gi/lorc/stone-crafting",
  "Stoneskin": "gi/delapouite/rock-golem",
  "Control Water": "gi/lorc/wave-strike",
  "Private Sanctum": "gi/lorc/locked-fortress",
  "Arcane Eye": "gi/lorc/eyeball",
  "Wall of Fire": "gi/delapouite/firewall",
  "Fire Shield": "gi/lorc/fire-shield",
  "Dimension Door": "gi/delapouite/exit-door",
  "Dominate Beast": "gi/lorc/spiked-collar",
  "Locate Creature": "gi/delapouite/position-marker",
  "Secret Chest": "gi/lorc/locked-chest",
  "Polymorph": "gi/delapouite/frog-prince",
  "Divination": "gi/lorc/rune-stone",
  "Phantasmal Killer": "gi/lorc/haunting",
  "Conjure Woodland Beings": "gi/delapouite/fairy",
  "Conjure Minor Elementals": "gi/delapouite/djinn",
  "Compulsion": "gi/lorc/spiral-arrow",
  "Freedom of Movement": "gi/delapouite/liberty-wing",
  "Confusion": "gi/lorc/uncertainty",
  "Guardian of Faith": "gi/lorc/angel-outfit",
  "Resilient Sphere": "gi/delapouite/glass-ball",
  "Blight": "gi/lorc/dead-wood",
  "Black Tentacles": "gi/lorc/interlaced-tentacles",
  "Greater Restoration": "gi/delapouite/caduceus",
  "Tree Stride": "gi/delapouite/tree-door",
  "Contagion": "gi/lorc/biohazard",
  "Legend Lore": "gi/lorc/book-aura",
  "Modify Memory": "gi/delapouite/brain-dump",
  "Wall of Stone": "gi/delapouite/stone-wall",
  "Cone of Cold": "gi/lorc/energy-breath",
  "Teleportation Circle": "gi/lorc/circle-sparks",
  "Mass Cure Wounds": "gi/delapouite/healing",
  "Scrying": "gi/lorc/mirror-mirror",
  "Insect Plague": "gi/delapouite/fly",
  "Flame Strike": "gi/lorc/fire-zone",
  "Geas": "gi/lorc/wax-seal",
  "Commune": "gi/delapouite/prayer-beads",
  "Commune with Nature": "gi/delapouite/ecology",
  "Raise Dead": "gi/skoll/hasty-grave",
  "Animate Objects": "gi/delapouite/mimic-chest",
  "Planar Binding": "gi/lorc/crossed-chains",
  "Dominate Person": "gi/lorc/puppet",
  "Antilife Shell": "gi/lorc/surrounded-shield",
  "Conjure Elemental": "tw/monster/elemental",
  "Seeming": "gi/lorc/tribal-mask",
  "Awaken": "gi/delapouite/deku-tree",
  "Dispel Evil and Good": "gi/lorc/cross-flare",
  "Reincarnate": "gi/lorc/ouroboros",
  "Contact Other Plane": "gi/delapouite/brain-tentacle",
  "Hallow": "gi/delapouite/church",
  "Wall of Force": "gi/lorc/shieldcomb",
  "Cloudkill": "gi/lorc/death-zone",
  "Dream": "gi/delapouite/dream-catcher",
  "Passwall": "gi/delapouite/broken-wall",
  "Creation": "gi/lorc/cubes",
  "Telekinesis": "gi/lorc/psychic-waves",
  "Telepathic Bond": "gi/lorc/telepathy",
  "Hold Monster": "gi/lorc/monster-grasp",
  "Mislead": "gi/lorc/split-body",
  "Arcane Hand": "gi/lorc/grab",
  "Magic Jar": "gi/delapouite/bottled-shadow",
  "Harm": "gi/lorc/internal-injury",
  "Forbiddance": "gi/delapouite/temple-gate",
  "True Seeing": "gi/delapouite/eye-of-horus",
  "Circle of Death": "gi/lorc/skull-ring",
  "Freezing Sphere": "gi/lorc/frozen-orb",
  "Wall of Ice": "gi/lorc/icicles-fence",
  "Instant Summons": "gi/lorc/saphir",
  "Mass Suggestion": "gi/lorc/divided-spiral",
  "Irresistible Dance": "gi/delapouite/ballerina-shoes",
  "Flesh to Stone": "gi/lorc/stoned-skull",
  "Guards and Wards": "gi/lorc/guarded-tower",
  "Move Earth": "gi/lorc/earth-spit",
  "Heroes' Feast": "gi/lorc/roast-chicken",
  "Planar Ally": "gi/delapouite/daemon-pull",
  "Find the Path": "gi/lorc/treasure-map",
  "Heal": "gi/sbed/health-increase",
  "Conjure Fey": "gi/delapouite/unicorn",
  "Programmed Illusion": "gi/delapouite/theater-curtains",
  "Transport via Plants": "gi/delapouite/tree-roots",
  "Disintegrate": "gi/lorc/disintegrate",
  "Eyebite": "gi/skoll/evil-eyes",
  "Word of Recall": "gi/lorc/return-arrow",
  "Sunbeam": "gi/lorc/sunbeams",
  "Create Undead": "gi/skoll/raise-zombie",
  "Blade Barrier": "gi/lorc/spinning-blades",
  "Wall of Thorns": "gi/lorc/thorny-vine",
  "Globe of Invulnerability": "gi/lorc/shield-echoes",
  "Contingency": "gi/lorc/time-trap",
  "Wind Walk": "gi/lorc/fluffy-cloud",
  "Chain Lightning": "gi/willdabeast/chain-lightning",
  "Divine Word": "gi/lorc/holy-symbol",
  "Magnificent Mansion": "gi/delapouite/indian-palace",
  "Mirage Arcane": "gi/delapouite/oasis",
  "Resurrection": "gi/lorc/ankh",
  "Sequester": "gi/delapouite/locked-box",
  "Arcane Sword": "gi/lorc/bouncing-sword",
  "Reverse Gravity": "gi/sbed/falling",
  "Fire Storm": "gi/lorc/wildfires",
  "Delayed Blast Fireball": "gi/lorc/time-bomb",
  "Finger of Death": "gi/lorc/smoking-finger",
  "Simulacrum": "gi/delapouite/ice-golem",
  "Conjure Celestial": "gi/lorc/angel-wings",
  "Project Image": "gi/lorc/shadow-follower",
  "Prismatic Spray": "gi/delapouite/prism",
  "Regenerate": "gi/sbed/regeneration",
  "Forcecage": "gi/delapouite/cage",
  "Symbol": "gi/delapouite/heptagram",
  "Teleport": "tw/location/portal",
  "Plane Shift": "gi/lorc/interstellar-path",
  "Etherealness": "gi/lorc/ghost",
  "Antipathy/Sympathy": "gi/lorc/magnet",
  "Control Weather": "gi/delapouite/sun-cloud",
  "Incendiary Cloud": "gi/lorc/burning-embers",
  "Demiplane": "gi/delapouite/arabic-door",
  "Animal Shapes": "gi/lorc/paw",
  "Earthquake": "gi/lorc/earth-crack",
  "Clone": "gi/lorc/embryo",
  "Glibness": "gi/delapouite/tongue",
  "Maze": "gi/lorc/maze",
  "Dominate Monster": "gi/sbed/overmind",
  "Antimagic Field": "gi/sbed/cancel",
  "Mind Blank": "gi/lorc/brain-freeze",
  "Holy Aura": "gi/lorc/beams-aura",
  "Feeblemind": "gi/delapouite/brain-leak",
  "Power Word Stun": "gi/delapouite/knocked-out-stars",
  "Sunburst": "gi/lorc/sun-radiations",
  "Storm of Vengeance": "gi/lorc/lightning-storm",
  "Gate": "gi/lorc/magic-gate",
  "Weird": "gi/lorc/screaming",
  "Imprisonment": "gi/lorc/imprisoned",
  "Wish": "gi/lorc/magic-lamp",
  "True Resurrection": "gi/lorc/sunrise",
  "True Polymorph": "gi/delapouite/transform",
  "Mass Heal": "gi/lorc/holy-grail",
  "Meteor Swarm": "gi/lorc/fragmented-meteor",
  "Time Stop": "gi/lorc/hourglass",
  "Foresight": "gi/lorc/third-eye",
  "Astral Projection": "gi/delapouite/soul",
  "Prismatic Wall": "gi/lorc/crystal-bars",
  "Power Word Kill": "gi/sbed/death-skull",
  "Shapechange": "gi/lorc/werewolf"
};

export const FEATURE_ICONS = {
  "Rage": "gi/lorc/fist",
  "Unarmored Defense": "gi/delapouite/abdominal-armor",
  "Reckless Attack": "gi/lorc/axe-swing",
  "Danger Sense": "gi/lorc/hazard-sign",
  "Primal Path": "gi/lorc/tribal-mask",
  "Frenzy": "gi/lorc/crossed-axes",
  "Extra Attack": "gi/lorc/crossed-swords",
  "Fast Movement": "gi/lorc/sprint",
  "Mindless Rage": "gi/delapouite/brain-leak",
  "Feral Instinct": "gi/sbed/pounce",
  "Brutal Critical": "gi/lorc/skull-crack",
  "Intimidating Presence": "gi/lorc/horned-skull",
  "Relentless Rage": "gi/lorc/half-heart",
  "Retaliation": "gi/lorc/sword-clash",
  "Persistent Rage": "gi/lorc/burning-passion",
  "Indomitable Might": "gi/delapouite/mighty-force",
  "Primal Champion": "gi/delapouite/war-bonnet",
  "Spellcasting": "gi/delapouite/spell-book",
  "Bardic Inspiration": "gi/lorc/lyre",
  "Jack of All Trades": "gi/delapouite/swiss-army-knife",
  "Song of Rest": "gi/delapouite/musical-notes",
  "Bard College": "gi/delapouite/graduate-cap",
  "Expertise": "gi/delapouite/ribbon-medal",
  "Bonus Proficiencies": "gi/delapouite/checklist",
  "Cutting Words": "gi/lorc/sharp-lips",
  "Font of Inspiration": "gi/lorc/fountain",
  "Countercharm": "gi/lorc/anthem",
  "Additional Magical Secrets": "gi/lorc/gift-of-knowledge",
  "Magical Secrets": "gi/delapouite/secret-book",
  "Peerless Skill": "gi/lorc/on-target",
  "Superior Inspiration": "gi/lorc/rally-the-troops",
  "Divine Domain": "gi/lorc/holy-symbol",
  "Life Domain Spells": "gi/lorc/ankh",
  "Bonus Proficiency": "gi/delapouite/chest-armor",
  "Disciple of Life": "gi/zeromancer/heart-plus",
  "Channel Divinity": "gi/lorc/sunbeams",
  "Channel Divinity: Turn Undead": "gi/delapouite/crucifix",
  "Channel Divinity: Preserve Life": "gi/lorc/shining-heart",
  "Destroy Undead": "gi/lorc/broken-skull",
  "Blessed Healer": "gi/delapouite/rod-of-asclepius",
  "Divine Strike": "gi/delapouite/flanged-mace",
  "Divine Intervention": "gi/delapouite/hand-of-god",
  "Supreme Healing": "gi/lorc/miracle-medecine",
  "Druidic": "gi/lorc/rune-stone",
  "Wild Shape": "gi/lorc/wolf-howl",
  "Druid Circle": "gi/delapouite/circle-forest",
  "Bonus Cantrip": "gi/delapouite/sparkles",
  "Natural Recovery": "gi/delapouite/stump-regrowth",
  "Circle Spells": "gi/cathelineau/holy-oak",
  "Circle Spells: Arctic": "gi/delapouite/iceberg",
  "Circle Spells: Coast": "gi/delapouite/sea-cliff",
  "Circle Spells: Desert": "gi/delapouite/desert",
  "Circle Spells: Forest": "gi/delapouite/forest",
  "Circle Spells: Grassland": "gi/delapouite/high-grass",
  "Circle Spells: Mountain": "gi/lorc/mountaintop",
  "Circle Spells: Swamp": "gi/delapouite/swamp",
  "Circle Spells: Underdark": "gi/delapouite/stalactites",
  "Land's Stride": "gi/lorc/boot-prints",
  "Nature's Ward": "gi/lorc/three-leaves",
  "Nature's Sanctuary": "gi/delapouite/slumbering-sanctuary",
  "Timeless Body": "gi/lorc/sands-of-time",
  "Beast Spells": "gi/lorc/paw-front",
  "Archdruid": "gi/lorc/oak",
  "Fighting Style": "gi/lorc/swords-emblem",
  "Second Wind": "gi/delapouite/lungs",
  "Action Surge": "gi/delapouite/extra-time",
  "Martial Archetype": "gi/delapouite/knight-banner",
  "Improved Critical": "gi/delapouite/dice-twenty-faces-twenty",
  "Remarkable Athlete": "gi/delapouite/leg",
  "Indomitable": "gi/lorc/diamond-hard",
  "Additional Fighting Style": "gi/delapouite/sword-brandish",
  "Extra Attack (2)": "gi/lorc/crossed-sabres",
  "Superior Critical": "gi/lorc/deadly-strike",
  "Survivor": "gi/sbed/regeneration",
  "Extra Attack (3)": "gi/lorc/sword-array",
  "Martial Arts": "gi/delapouite/black-belt",
  "Ki": "gi/delapouite/yin-yang",
  "Flurry of Blows": "gi/lorc/punch-blast",
  "Patient Defense": "gi/delapouite/vibrating-shield",
  "Step of the Wind": "gi/lorc/wingfoot",
  "Unarmored Movement": "gi/lorc/barefoot",
  "Monastic Tradition": "gi/delapouite/pagoda",
  "Deflect Missiles": "gi/darkzaitzev/catch",
  "Open Hand Technique": "gi/skoll/open-palm",
  "Slow Fall": "gi/lorc/feather",
  "Stunning Strike": "gi/delapouite/knocked-out-stars",
  "Ki-Empowered Strikes": "gi/lorc/thor-fist",
  "Wholeness of Body": "gi/lorc/heart-organ",
  "Evasion": "gi/felbrigg/dodge",
  "Stillness of Mind": "gi/lorc/lotus-flower",
  "Purity of Body": "gi/delapouite/antibody",
  "Tranquility": "gi/lorc/dove",
  "Tongue of the Sun and Moon": "gi/lorc/conversation",
  "Diamond Soul": "gi/lorc/cut-diamond",
  "Quivering Palm": "gi/lorc/magic-palm",
  "Empty Body": "gi/lorc/spectre",
  "Perfect Self": "gi/lorc/enlightenment",
  "Divine Sense": "gi/lorc/templar-eye",
  "Lay on Hands": "gi/lorc/glowing-hands",
  "Divine Smite": "gi/lorc/shining-sword",
  "Divine Health": "gi/lorc/templar-heart",
  "Sacred Oath": "gi/delapouite/sword-altar",
  "Oath Spells": "gi/delapouite/winged-scepter",
  "Channel Divinity: Sacred Weapon": "gi/lorc/relic-blade",
  "Channel Divinity: Turn the Unholy": "gi/delapouite/jerusalem-cross",
  "Aura of Protection": "gi/lorc/magic-shield",
  "Aura of Devotion": "gi/lorc/rosa-shield",
  "Aura of Courage": "gi/lorc/lion",
  "Improved Divine Smite": "gi/lorc/sparkling-sabre",
  "Cleansing Touch": "gi/delapouite/holy-water",
  "Purity of Spirit": "gi/lorc/angel-outfit",
  "Holy Nimbus": "gi/lorc/sun-radiations",
  "Favored Enemy": "gi/delapouite/target-poster",
  "Natural Explorer": "gi/lorc/compass",
  "Ranger Archetype": "gi/lorc/hunting-horn",
  "Primeval Awareness": "gi/lorc/beast-eye",
  "Hunter's Prey: Colossus Slayer": "gi/lorc/large-wound",
  "Hunter's Prey: Giant Killer": "gi/delapouite/sling",
  "Hunter's Prey: Horde Breaker": "gi/lorc/divergence",
  "Hunter's Prey": "gi/lorc/wolf-trap",
  "Defensive Tactics: Escape the Horde": "gi/delapouite/detour",
  "Defensive Tactics: Multiattack Defense": "gi/lorc/shield-echoes",
  "Defensive Tactics: Steel Will": "gi/lorc/anvil",
  "Defensive Tactics": "gi/delapouite/attached-shield",
  "Hide in Plain Sight": "gi/darkzaitzev/chameleon-glyph",
  "Multiattack: Volley": "gi/lorc/arrow-cluster",
  "Multiattack: Whirlwind Attack": "gi/lorc/sword-spin",
  "Multiattack": "gi/delapouite/multiple-targets",
  "Vanish": "gi/darkzaitzev/smoke-bomb",
  "Superior Hunter's Defense: Evasion": "gi/felbrigg/dodge",
  "Superior Hunter's Defense: Stand Against the Tide": "gi/lorc/wave-strike",
  "Superior Hunter's Defense: Uncanny Dodge": "gi/delapouite/avoidance",
  "Superior Hunter's Defense": "gi/delapouite/griffin-shield",
  "Feral Senses": "gi/delapouite/hunter-eyes",
  "Foe Slayer": "gi/lorc/dead-eye",
  "Sneak Attack": "gi/lorc/cloak-dagger",
  "Thieves' Cant": "gi/delapouite/zigzag-hieroglyph",
  "Cunning Action": "gi/delapouite/misdirection",
  "Roguish Archetype": "gi/lorc/hood",
  "Fast Hands": "gi/lorc/snatch",
  "Second-Story Work": "gi/delapouite/ladder",
  "Uncanny Dodge": "gi/delapouite/avoidance",
  "Supreme Sneak": "gi/darkzaitzev/tabi-boot",
  "Reliable Talent": "gi/delapouite/dice-shield",
  "Use Magic Device": "gi/lorc/magic-lamp",
  "Blindsense": "gi/lorc/echo-ripples",
  "Slippery Mind": "gi/delapouite/eel",
  "Thief's Reflexes": "gi/lorc/hourglass",
  "Elusive": "gi/lorc/divert",
  "Stroke of Luck": "gi/delapouite/shamrock",
  "Sorcerous Origin": "gi/lorc/magic-swirl",
  "Dragon Ancestor": "gi/delapouite/dragon-orb",
  "Draconic Resilience": "gi/lorc/dorsal-scales",
  "Font of Magic": "gi/lorc/floating-crystal",
  "Metamagic": "gi/lorc/moebius-star",
  "Careful Spell": "gi/lorc/energy-shield",
  "Distant Spell": "gi/lorc/spyglass",
  "Empowered Spell": "gi/delapouite/rolling-dices",
  "Extended Spell": "gi/delapouite/duration",
  "Heightened Spell": "gi/delapouite/upgrade",
  "Quickened Spell": "gi/lorc/fast-arrow",
  "Subtle Spell": "gi/lorc/silence",
  "Twinned Spell": "gi/lorc/duality",
  "Elemental Affinity": "gi/lorc/triorb",
  "Dragon Wings": "gi/delapouite/spiky-wing",
  "Draconic Presence": "gi/lorc/wyvern",
  "Sorcerous Restoration": "gi/lorc/cycle",
  "Otherworldly Patron": "gi/delapouite/warlock-eye",
  "Pact Magic": "gi/delapouite/contract",
  "Expanded Spell List": "gi/lorc/burning-book",
  "Dark One's Blessing": "gi/lorc/life-tap",
  "Pact of the Chain": "gi/lorc/crossed-chains",
  "Pact of the Blade": "gi/lorc/rune-sword",
  "Pact of the Tome": "gi/willdabeast/black-book",
  "Dark One's Own Luck": "gi/lorc/fire-ace",
  "Fiendish Resilience": "gi/lorc/skull-shield",
  "Mystic Arcanum": "gi/delapouite/heptagram",
  "Hurl Through Hell": "gi/lorc/magic-portal",
  "Eldritch Master": "gi/lorc/magic-gate",
  "Arcane Recovery": "gi/lorc/bookmark",
  "Arcane Tradition": "gi/lorc/pointy-hat",
  "Evocation Savant": "gi/lorc/quill-ink",
  "Sculpt Spells": "gi/delapouite/chisel",
  "Potent Cantrip": "gi/lorc/unstable-projectile",
  "Empowered Evocation": "gi/lorc/crowned-explosion",
  "Overchannel": "gi/lorc/unstable-orb",
  "Spell Mastery": "gi/lorc/book-aura",
  "Signature Spells": "gi/lorc/wax-seal",
  "Archery": "gi/delapouite/bow-arrow",
  "Defense": "gi/lorc/breastplate",
  "Dueling": "gi/sbed/duel",
  "Great Weapon Fighting": "gi/delapouite/two-handed-sword",
  "Protection": "gi/lorc/checked-shield",
  "Two-Weapon Fighting": "gi/lorc/dervish-swords",
  "Grappler": "gi/lorc/grapple",
  "Shelter of the Faithful": "gi/delapouite/church",
  "Ability Score Increase": "gi/delapouite/progression",
  "Size, Speed, Languages": "gi/delapouite/measure-tape",
  "Darkvision": "gi/lorc/owl",
  "Gnome Cunning": "gi/lorc/brain",
  "Artificer's Lore": "gi/delapouite/lorgnette",
  "Tinker": "gi/lorc/tinker",
  "Dwarven Resilience": "gi/kier-heyl/dwarf-helmet",
  "Dwarven Combat Training": "gi/lorc/battle-axe",
  "Tool Proficiency": "gi/delapouite/toolbox",
  "Stonecunning": "gi/lorc/stone-crafting",
  "Dwarven Toughness": "gi/delapouite/heart-armor",
  "Draconic Ancestry": "gi/lorc/dragon-spiral",
  "Breath Weapon": "gi/lorc/dragon-breath",
  "Damage Resistance": "gi/delapouite/dragon-shield",
  "Menacing": "gi/delapouite/angry-eyes",
  "Relentless Endurance": "gi/lorc/heart-tower",
  "Savage Attacks": "gi/lorc/serrated-slash",
  "Lucky": "gi/lorc/clover",
  "Brave": "gi/delapouite/heart-shield",
  "Halfling Nimbleness": "gi/delapouite/jump-across",
  "Naturally Stealthy": "gi/lorc/hidden",
  "Fey Ancestry": "gi/lorc/fairy",
  "Skill Versatility": "gi/lorc/jigsaw-piece",
  "Hellish Resistance": "gi/delapouite/hell-crosses",
  "Infernal Legacy": "gi/lorc/pentagram-rose",
  "Keen Senses": "gi/delapouite/elf-ear",
  "Trance": "gi/lorc/semi-closed-eye",
  "Elf Weapon Training": "gi/lorc/pocket-bow",
  "Cantrip": "gi/lorc/fairy-wand",
  "Extra Language": "gi/skoll/talk"
};

export const INVOCATION_ICONS = {
  "Мучительный заряд": "gi/lorc/plasma-bolt",
  "Доспех теней": "gi/delapouite/cape-armor",
  "Шаг вознесения": "gi/lorc/feathered-wing",
  "Язык зверей": "gi/lorc/paw-heart",
  "Чарующее влияние": "gi/lorc/lips",
  "Колдовской шёпот": "gi/lorc/divided-spiral",
  "Книга древних тайн": "gi/lorc/evil-book",
  "Цепи Карцери": "gi/lorc/andromeda-chain",
  "Взор дьявола": "gi/lorc/burning-eye",
  "Страшное слово": "gi/lorc/uncertainty",
  "Мистическое зрение": "gi/lorc/crystal-eye",
  "Мистическое копьё": "gi/lorc/barbed-spear",
  "Глаза хранителя рун": "gi/lorc/rune-stone",
  "Дьявольская живучесть": "gi/delapouite/heart-beats",
  "Взгляд двух разумов": "gi/lorc/linked-rings",
  "Пьющий жизнь": "gi/lorc/dripping-sword",
  "Маска многих лиц": "gi/lorc/drama-masks",
  "Мастер множества обличий": "gi/delapouite/matryoshka-dolls",
  "Приспешники хаоса": "gi/delapouite/rock-golem",
  "Трясина разума": "gi/lorc/snail",
  "Туманные видения": "gi/delapouite/fog",
  "Единство с тенями": "gi/lorc/hidden",
  "Потусторонний прыжок": "gi/lorc/winged-leg",
  "Отталкивающий заряд": "gi/lorc/bowling-propulsion",
  "Ваятель плоти": "gi/delapouite/frog-prince",
  "Знак дурного предзнаменования": "gi/lorc/raven",
  "Похититель пяти судеб": "gi/lorc/life-in-the-balance",
  "Жаждущий клинок": "gi/lorc/spinning-sword",
  "Видения далёких миров": "gi/lorc/interstellar-path",
  "Голос повелителя цепи": "gi/lorc/sparrow",
  "Шёпот могилы": "gi/lorc/tombstone",
  "Ведьмин взор": "gi/lorc/octogonal-eye"
};

const lower = s => String(s || "").trim().toLowerCase().replace(/ё/g, "е");
const INV_BY_NAME = new Map(Object.entries(INVOCATION_ICONS).map(([k, v]) => [lower(k), v]));

export const SPELL_RU = {
  "брызги кислоты": "Acid Splash",
  "волшебная рука": "Mage Hand",
  "дубинка": "Shillelagh",
  "злая насмешка": "Vicious Mockery",
  "искусство друидов": "Druidcraft",
  "леденящее прикосновение": "Chill Touch",
  "луч холода": "Ray of Frost",
  "малая иллюзия": "Minor Illusion",
  "мистический заряд": "Eldritch Blast",
  "огненный снаряд": "Fire Bolt",
  "пляшущие огоньки": "Dancing Lights",
  "починка": "Mending",
  "свет": "Light",
  "священное пламя": "Sacred Flame",
  "сообщение": "Message",
  "сопротивление": "Resistance",
  "сотворение пламени": "Produce Flame",
  "указание": "Guidance",
  "уход за умирающим": "Spare the Dying",
  "фокусы": "Prestidigitation",
  "чудотворство": "Thaumaturgy",
  "электрошок": "Shocking Grasp",
  "ядовитые брызги": "Poison Spray",
  "адское возмездие": "Hellish Rebuke",
  "безмолвный образ": "Silent Image",
  "благословение": "Bless",
  "божественное благоволение": "Divine Favor",
  "волна грома": "Thunderwave",
  "волшебная стрела": "Magic Missile",
  "героизм": "Heroism",
  "длинный шаг": "Longstrider",
  "доспехи мага": "Mage Armor",
  "дружба с животными": "Animal Friendship",
  "жуткий смех": "Hideous Laughter",
  "защита от добра и зла": "Protection from Evil and Good",
  "иллюзорный текст": "Illusory Script",
  "лечащее слово": "Healing Word",
  "лечение ран": "Cure Wounds",
  "маскировка": "Disguise Self",
  "метка охотника": "Hunter's Mark",
  "нанесение ран": "Inflict Wounds",
  "направленный снаряд": "Guiding Bolt",
  "невидимый слуга": "Unseen Servant",
  "обнаружение болезней и яда": "Detect Poison and Disease",
  "обнаружение добра и зла": "Detect Evil and Good",
  "обнаружение магии": "Detect Magic",
  "огненные ладони": "Burning Hands",
  "огонь фей": "Faerie Fire",
  "опознание": "Identify",
  "опутывание": "Entangle",
  "очарование личности": "Charm Person",
  "очищение пищи и питья": "Purify Food and Drink",
  "падение пёрышком": "Feather Fall",
  "парящий диск": "Floating Disk",
  "поиск фамильяра": "Find Familiar",
  "понимание языков": "Comprehend Languages",
  "порча": "Bane",
  "поспешное отступление": "Expeditious Retreat",
  "приказ": "Command",
  "прыжок": "Jump",
  "псевдожизнь": "False Life",
  "разговор с животными": "Speak with Animals",
  "сверкающие брызги": "Color Spray",
  "скольжение": "Grease",
  "сотворение или уничтожение воды": "Create or Destroy Water",
  "тревога": "Alarm",
  "туманное облако": "Fog Cloud",
  "убежище": "Sanctuary",
  "усыпление": "Sleep",
  "чудо-ягоды": "Goodberry",
  "щит": "Shield",
  "щит веры": "Shield of Faith",
  "бесследное передвижение": "Pass without Trace",
  "божественное оружие": "Spiritual Weapon",
  "верёвочный трюк": "Rope Trick",
  "вечный огонь": "Continual Flame",
  "видение невидимого": "See Invisibility",
  "внушение": "Suggestion",
  "волшебные уста": "Magic Mouth",
  "гадание": "Augury",
  "дребезги": "Shatter",
  "дубовая кора": "Barkskin",
  "животное-посыльный": "Animal Messenger",
  "защита от яда": "Protection from Poison",
  "зона истины": "Zone of Truth",
  "кислотная стрела": "Acid Arrow",
  "левитация": "Levitate",
  "лунный луч": "Moonbeam",
  "луч слабости": "Ray of Enfeeblement",
  "магическая аура": "Arcanist's Magic Aura",
  "магический замок": "Arcane Lock",
  "магическое оружие": "Magic Weapon",
  "малое восстановление": "Lesser Restoration",
  "молитва лечения": "Prayer of Healing",
  "невидимость": "Invisibility",
  "нетленные останки": "Gentle Repose",
  "обнаружение мыслей": "Detect Thoughts",
  "открывание": "Knock",
  "отражения": "Mirror Image",
  "охранная связь": "Warding Bond",
  "очарование": "Enthrall",
  "палящий луч": "Scorching Ray",
  "паутина": "Web",
  "паучье лазание": "Spider Climb",
  "подмога": "Aid",
  "поиск животных или растений": "Locate Animals or Plants",
  "поиск ловушек": "Find Traps",
  "поиск предмета": "Locate Object",
  "поиск скакуна": "Find Steed",
  "порыв ветра": "Gust of Wind",
  "пылающий клинок": "Flame Blade",
  "пылающий шар": "Flaming Sphere",
  "размытый образ": "Blur",
  "раскалённый металл": "Heat Metal",
  "слепота/глухота": "Blindness/Deafness",
  "смена обличья": "Alter Self",
  "тёмное зрение": "Darkvision",
  "тишина": "Silence",
  "туманный шаг": "Misty Step",
  "тьма": "Darkness",
  "увеличение/уменьшение": "Enlarge/Reduce",
  "удержание личности": "Hold Person",
  "улучшение характеристики": "Enhance Ability",
  "умиротворение": "Calm Emotions",
  "шипастая поросль": "Spike Growth",
  "возрождение": "Revivify",
  "восставший труп": "Animate Dead",
  "газообразная форма": "Gaseous Form",
  "гипнотический узор": "Hypnotic Pattern",
  "дневной свет": "Daylight",
  "духовные стражи": "Spirit Guardians",
  "замедление": "Slow",
  "защита от энергии": "Protection from Energy",
  "зловонное облако": "Stinking Cloud",
  "контрзаклинание": "Counterspell",
  "крошечная хижина": "Tiny Hut",
  "магический круг": "Magic Circle",
  "маяк надежды": "Beacon of Hope",
  "мерцание": "Blink",
  "метель": "Sleet Storm",
  "множественное лечащее слово": "Mass Healing Word",
  "молния": "Lightning Bolt",
  "необнаружимость": "Nondetection",
  "образ": "Major Image",
  "огненный шар": "Fireball",
  "охранные руны": "Glyph of Warding",
  "подводное дыхание": "Water Breathing",
  "подсматривание": "Clairvoyance",
  "полёт": "Fly",
  "послание": "Sending",
  "призрачный скакун": "Phantom Steed",
  "призыв животных": "Conjure Animals",
  "призыв молнии": "Call Lightning",
  "прикосновение вампира": "Vampiric Touch",
  "притворная смерть": "Feign Death",
  "проклятие": "Bestow Curse",
  "разговор с мёртвыми": "Speak with Dead",
  "разговор с растениями": "Speak with Plants",
  "рассеивание магии": "Dispel Magic",
  "рост растений": "Plant Growth",
  "слияние с камнем": "Meld into Stone",
  "снятие проклятия": "Remove Curse",
  "сотворение пищи и воды": "Create Food and Water",
  "стена ветра": "Wind Wall",
  "ужас": "Fear",
  "ускорение": "Haste",
  "хождение по воде": "Water Walk",
  "языки": "Tongues",
  "верный пёс": "Faithful Hound",
  "высшая невидимость": "Greater Invisibility",
  "галлюцинаторная местность": "Hallucinatory Terrain",
  "гигантское насекомое": "Giant Insect",
  "град": "Ice Storm",
  "защита от смерти": "Death Ward",
  "изгнание": "Banishment",
  "изготовление": "Fabricate",
  "изменение формы камня": "Stone Shape",
  "каменная кожа": "Stoneskin",
  "контроль над водами": "Control Water",
  "личное убежище": "Private Sanctum",
  "магический глаз": "Arcane Eye",
  "огненная стена": "Wall of Fire",
  "огненный щит": "Fire Shield",
  "переносящая дверь": "Dimension Door",
  "подчинение зверя": "Dominate Beast",
  "поиск существа": "Locate Creature",
  "потайной сундук": "Secret Chest",
  "превращение": "Polymorph",
  "предсказание": "Divination",
  "призрачный убийца": "Phantasmal Killer",
  "призыв лесных обитателей": "Conjure Woodland Beings",
  "призыв малых элементалей": "Conjure Minor Elementals",
  "принуждение": "Compulsion",
  "свобода перемещения": "Freedom of Movement",
  "смятение": "Confusion",
  "страж веры": "Guardian of Faith",
  "упругая сфера": "Resilient Sphere",
  "усыхание": "Blight",
  "чёрные щупальца": "Black Tentacles",
  "высшее восстановление": "Greater Restoration",
  "древесный путь": "Tree Stride",
  "заражение": "Contagion",
  "знание легенд": "Legend Lore",
  "изменение памяти": "Modify Memory",
  "каменная стена": "Wall of Stone",
  "конус холода": "Cone of Cold",
  "круг телепортации": "Teleportation Circle",
  "множественное лечение ран": "Mass Cure Wounds",
  "наблюдение": "Scrying",
  "нашествие насекомых": "Insect Plague",
  "небесный огонь": "Flame Strike",
  "обет": "Geas",
  "общение": "Commune",
  "общение с природой": "Commune with Nature",
  "оживление": "Raise Dead",
  "оживление вещей": "Animate Objects",
  "планарные узы": "Planar Binding",
  "подчинение личности": "Dominate Person",
  "преграда жизни": "Antilife Shell",
  "призыв элементаля": "Conjure Elemental",
  "притворство": "Seeming",
  "пробуждение": "Awaken",
  "рассеивание добра и зла": "Dispel Evil and Good",
  "реинкарнация": "Reincarnate",
  "связь с иным планом": "Contact Other Plane",
  "святилище": "Hallow",
  "силовая стена": "Wall of Force",
  "смертельное облако": "Cloudkill",
  "сновидение": "Dream",
  "создание прохода": "Passwall",
  "сотворение": "Creation",
  "телекинез": "Telekinesis",
  "телепатическая связь": "Telepathic Bond",
  "удержание чудовища": "Hold Monster",
  "фальшивый двойник": "Mislead",
  "чародейская рука": "Arcane Hand",
  "волшебный сосуд": "Magic Jar",
  "вред": "Harm",
  "запрет": "Forbiddance",
  "истинное зрение": "True Seeing",
  "круг смерти": "Circle of Death",
  "леденящая сфера": "Freezing Sphere",
  "ледяная стена": "Wall of Ice",
  "мгновенный вызов": "Instant Summons",
  "множественное внушение": "Mass Suggestion",
  "неудержимая пляска": "Irresistible Dance",
  "окаменение": "Flesh to Stone",
  "охрана и защита": "Guards and Wards",
  "перемещение почвы": "Move Earth",
  "пир героев": "Heroes' Feast",
  "планарный союзник": "Planar Ally",
  "поиск пути": "Find the Path",
  "полное исцеление": "Heal",
  "призыв феи": "Conjure Fey",
  "программируемая иллюзия": "Programmed Illusion",
  "путешествие через растения": "Transport via Plants",
  "распад": "Disintegrate",
  "сглаз": "Eyebite",
  "слово возврата": "Word of Recall",
  "солнечный луч": "Sunbeam",
  "сотворение нежити": "Create Undead",
  "стена клинков": "Blade Barrier",
  "стена шипов": "Wall of Thorns",
  "сфера неуязвимости": "Globe of Invulnerability",
  "условие": "Contingency",
  "хождение по ветру": "Wind Walk",
  "цепная молния": "Chain Lightning",
  "божественное слово": "Divine Word",
  "великолепный особняк": "Magnificent Mansion",
  "волшебный мираж": "Mirage Arcane",
  "воскрешение": "Resurrection",
  "изоляция": "Sequester",
  "магический меч": "Arcane Sword",
  "обратная гравитация": "Reverse Gravity",
  "огненная буря": "Fire Storm",
  "огненный шар замедленного действия": "Delayed Blast Fireball",
  "перст смерти": "Finger of Death",
  "подобие": "Simulacrum",
  "призыв небожителя": "Conjure Celestial",
  "проекция образа": "Project Image",
  "радужные брызги": "Prismatic Spray",
  "регенерация": "Regenerate",
  "силовая клетка": "Forcecage",
  "символ": "Symbol",
  "телепортация": "Teleport",
  "уход в иной мир": "Plane Shift",
  "эфирность": "Etherealness",
  "антипатия/симпатия": "Antipathy/Sympathy",
  "власть над погодой": "Control Weather",
  "воспламеняющееся облако": "Incendiary Cloud",
  "демиплан": "Demiplane",
  "животные формы": "Animal Shapes",
  "землетрясение": "Earthquake",
  "клон": "Clone",
  "красноречие": "Glibness",
  "лабиринт": "Maze",
  "подчинение чудовища": "Dominate Monster",
  "поле антимагии": "Antimagic Field",
  "пустой разум": "Mind Blank",
  "священная аура": "Holy Aura",
  "слабоумие": "Feeblemind",
  "слово силы: оглушение": "Power Word Stun",
  "солнечный взрыв": "Sunburst",
  "буря возмездия": "Storm of Vengeance",
  "врата": "Gate",
  "жуть": "Weird",
  "заточение": "Imprisonment",
  "исполнение желаний": "Wish",
  "истинное воскрешение": "True Resurrection",
  "истинное превращение": "True Polymorph",
  "массовое исцеление": "Mass Heal",
  "метеоритный дождь": "Meteor Swarm",
  "остановка времени": "Time Stop",
  "предвидение": "Foresight",
  "проекция в астрал": "Astral Projection",
  "радужная стена": "Prismatic Wall",
  "слово силы: смерть": "Power Word Kill",
  "смена облика": "Shapechange"
};

export const FEATURE_RU = {
  "ярость": "Rage",
  "защита без доспехов": "Unarmored Defense",
  "безрассудная атака": "Reckless Attack",
  "чувство опасности": "Danger Sense",
  "путь дикости": "Primal Path",
  "бешенство": "Frenzy",
  "дополнительная атака": "Extra Attack",
  "быстрое передвижение": "Fast Movement",
  "бездумная ярость": "Mindless Rage",
  "дикий инстинкт": "Feral Instinct",
  "жестокий критический удар": "Brutal Critical",
  "пугающее присутствие": "Intimidating Presence",
  "непреклонная ярость": "Relentless Rage",
  "возмездие": "Retaliation",
  "неукротимая ярость": "Persistent Rage",
  "неодолимая мощь": "Indomitable Might",
  "дикий чемпион": "Primal Champion",
  "использование заклинаний": "Spellcasting",
  "вдохновение барда": "Bardic Inspiration",
  "мастер на все руки": "Jack of All Trades",
  "песнь отдыха": "Song of Rest",
  "коллегия бардов": "Bard College",
  "компетентность": "Expertise",
  "дополнительные владения": "Bonus Proficiencies",
  "острое словцо": "Cutting Words",
  "источник вдохновения": "Font of Inspiration",
  "контрочарование": "Countercharm",
  "дополнительные тайны магии": "Additional Magical Secrets",
  "тайны магии": "Magical Secrets",
  "непревзойдённое мастерство": "Peerless Skill",
  "превосходное вдохновение": "Superior Inspiration",
  "божественный домен": "Divine Domain",
  "заклинания домена жизни": "Life Domain Spells",
  "дополнительное владение": "Bonus Proficiency",
  "последователь жизни": "Disciple of Life",
  "канал божественности": "Channel Divinity",
  "канал божественности: изгнание нежити": "Channel Divinity: Turn Undead",
  "канал божественности: сохранение жизни": "Channel Divinity: Preserve Life",
  "уничтожение нежити": "Destroy Undead",
  "благословенный целитель": "Blessed Healer",
  "божественный удар": "Divine Strike",
  "божественное вмешательство": "Divine Intervention",
  "высшее исцеление": "Supreme Healing",
  "друидический язык": "Druidic",
  "дикий облик": "Wild Shape",
  "круг друидов": "Druid Circle",
  "дополнительный заговор": "Bonus Cantrip",
  "естественное восстановление": "Natural Recovery",
  "заклинания круга": "Circle Spells",
  "заклинания круга: арктика": "Circle Spells: Arctic",
  "заклинания круга: побережье": "Circle Spells: Coast",
  "заклинания круга: пустыня": "Circle Spells: Desert",
  "заклинания круга: лес": "Circle Spells: Forest",
  "заклинания круга: луга": "Circle Spells: Grassland",
  "заклинания круга: горы": "Circle Spells: Mountain",
  "заклинания круга: болото": "Circle Spells: Swamp",
  "заклинания круга: подземье": "Circle Spells: Underdark",
  "тропы земли": "Land's Stride",
  "защита природы": "Nature's Ward",
  "святилище природы": "Nature's Sanctuary",
  "безвременное тело": "Timeless Body",
  "заклинания зверя": "Beast Spells",
  "архидруид": "Archdruid",
  "боевой стиль": "Fighting Style",
  "второе дыхание": "Second Wind",
  "всплеск действий": "Action Surge",
  "воинский архетип": "Martial Archetype",
  "улучшенный критический удар": "Improved Critical",
  "выдающийся атлет": "Remarkable Athlete",
  "упорство": "Indomitable",
  "дополнительный боевой стиль": "Additional Fighting Style",
  "дополнительная атака (2)": "Extra Attack (2)",
  "превосходный критический удар": "Superior Critical",
  "уцелевший": "Survivor",
  "дополнительная атака (3)": "Extra Attack (3)",
  "боевые искусства": "Martial Arts",
  "ки": "Ki",
  "шквал ударов": "Flurry of Blows",
  "терпеливая оборона": "Patient Defense",
  "поступь ветра": "Step of the Wind",
  "движение без доспехов": "Unarmored Movement",
  "монастырская традиция": "Monastic Tradition",
  "отражение снарядов": "Deflect Missiles",
  "техника открытой ладони": "Open Hand Technique",
  "медленное падение": "Slow Fall",
  "ошеломляющий удар": "Stunning Strike",
  "удары, усиленные ки": "Ki-Empowered Strikes",
  "целостность тела": "Wholeness of Body",
  "увёртливость": "Evasion",
  "безмятежность разума": "Stillness of Mind",
  "чистота тела": "Purity of Body",
  "умиротворение": "Tranquility",
  "язык солнца и луны": "Tongue of the Sun and Moon",
  "алмазная душа": "Diamond Soul",
  "дрожащая ладонь": "Quivering Palm",
  "пустое тело": "Empty Body",
  "совершенство": "Perfect Self",
  "божественное чувство": "Divine Sense",
  "наложение рук": "Lay on Hands",
  "божественная кара": "Divine Smite",
  "божественное здоровье": "Divine Health",
  "священная клятва": "Sacred Oath",
  "заклинания клятвы": "Oath Spells",
  "канал божественности: священное оружие": "Channel Divinity: Sacred Weapon",
  "канал божественности: изгнание нечестивых": "Channel Divinity: Turn the Unholy",
  "аура защиты": "Aura of Protection",
  "аура преданности": "Aura of Devotion",
  "аура отваги": "Aura of Courage",
  "улучшенная божественная кара": "Improved Divine Smite",
  "очищающее касание": "Cleansing Touch",
  "чистота духа": "Purity of Spirit",
  "священный ореол": "Holy Nimbus",
  "избранный враг": "Favored Enemy",
  "исследователь природы": "Natural Explorer",
  "архетип следопыта": "Ranger Archetype",
  "первобытная осведомлённость": "Primeval Awareness",
  "добыча охотника: убийца колоссов": "Hunter's Prey: Colossus Slayer",
  "добыча охотника: убийца великанов": "Hunter's Prey: Giant Killer",
  "добыча охотника: сокрушитель орд": "Hunter's Prey: Horde Breaker",
  "добыча охотника": "Hunter's Prey",
  "оборонительная тактика: побег от орды": "Defensive Tactics: Escape the Horde",
  "оборонительная тактика: защита от мультиатаки": "Defensive Tactics: Multiattack Defense",
  "оборонительная тактика: стальная воля": "Defensive Tactics: Steel Will",
  "оборонительная тактика": "Defensive Tactics",
  "тропами земли": "Land's Stride",
  "маскировка на виду": "Hide in Plain Sight",
  "мультиатака: залп": "Multiattack: Volley",
  "мультиатака: вихревая атака": "Multiattack: Whirlwind Attack",
  "мультиатака": "Multiattack",
  "исчезновение": "Vanish",
  "улучшенная защита охотника: увёртливость": "Superior Hunter's Defense: Evasion",
  "улучшенная защита охотника: наперекор волне": "Superior Hunter's Defense: Stand Against the Tide",
  "улучшенная защита охотника: невероятное уклонение": "Superior Hunter's Defense: Uncanny Dodge",
  "улучшенная защита охотника": "Superior Hunter's Defense",
  "дикие чувства": "Feral Senses",
  "убийца врагов": "Foe Slayer",
  "скрытая атака": "Sneak Attack",
  "воровской жаргон": "Thieves' Cant",
  "хитрое действие": "Cunning Action",
  "плутовской архетип": "Roguish Archetype",
  "быстрые руки": "Fast Hands",
  "верхолаз": "Second-Story Work",
  "невероятное уклонение": "Uncanny Dodge",
  "непревзойдённая скрытность": "Supreme Sneak",
  "надёжный талант": "Reliable Talent",
  "использование магических устройств": "Use Magic Device",
  "слепое чувство": "Blindsense",
  "скользкий разум": "Slippery Mind",
  "воровские рефлексы": "Thief's Reflexes",
  "неуловимость": "Elusive",
  "удачный случай": "Stroke of Luck",
  "происхождение чародея": "Sorcerous Origin",
  "предок-дракон": "Dragon Ancestor",
  "драконья устойчивость": "Draconic Resilience",
  "источник магии": "Font of Magic",
  "метамагия": "Metamagic",
  "аккуратное заклинание": "Careful Spell",
  "дальнобойное заклинание": "Distant Spell",
  "усиленное заклинание": "Empowered Spell",
  "продлённое заклинание": "Extended Spell",
  "усложнённое заклинание": "Heightened Spell",
  "ускоренное заклинание": "Quickened Spell",
  "неприметное заклинание": "Subtle Spell",
  "сдвоенное заклинание": "Twinned Spell",
  "родство со стихией": "Elemental Affinity",
  "драконьи крылья": "Dragon Wings",
  "драконье присутствие": "Draconic Presence",
  "чародейское восстановление": "Sorcerous Restoration",
  "потусторонний покровитель": "Otherworldly Patron",
  "магия договора": "Pact Magic",
  "расширенный список заклинаний": "Expanded Spell List",
  "благословение тёмного": "Dark One's Blessing",
  "договор цепи": "Pact of the Chain",
  "договор клинка": "Pact of the Blade",
  "договор гримуара": "Pact of the Tome",
  "удача тёмного": "Dark One's Own Luck",
  "стойкость исчадия": "Fiendish Resilience",
  "таинственный арканум": "Mystic Arcanum",
  "бросок через ад": "Hurl Through Hell",
  "мастер таинств": "Eldritch Master",
  "магическое восстановление": "Arcane Recovery",
  "магическая традиция": "Arcane Tradition",
  "знаток воплощения": "Evocation Savant",
  "формирование заклинаний": "Sculpt Spells",
  "мощный заговор": "Potent Cantrip",
  "усиленное воплощение": "Empowered Evocation",
  "перегрузка": "Overchannel",
  "мастерство заклинаний": "Spell Mastery",
  "фирменные заклинания": "Signature Spells",
  "стрельба": "Archery",
  "оборона": "Defense",
  "дуэль": "Dueling",
  "сражение большим оружием": "Great Weapon Fighting",
  "защита": "Protection",
  "сражение двумя оружиями": "Two-Weapon Fighting",
  "борец": "Grappler",
  "приют верующих": "Shelter of the Faithful",
  "увеличение характеристик": "Ability Score Increase",
  "размер, скорость, языки": "Size, Speed, Languages",
  "тёмное зрение": "Darkvision",
  "гномья хитрость": "Gnome Cunning",
  "знания ремесленника": "Artificer's Lore",
  "жестянщик": "Tinker",
  "дварфийская стойкость": "Dwarven Resilience",
  "владение оружием дварфов": "Dwarven Combat Training",
  "владение инструментами": "Tool Proficiency",
  "знание камня": "Stonecunning",
  "дварфийская выдержка": "Dwarven Toughness",
  "драконье происхождение": "Draconic Ancestry",
  "оружие дыхания": "Breath Weapon",
  "сопротивление урону": "Damage Resistance",
  "угрожающий вид": "Menacing",
  "непоколебимая стойкость": "Relentless Endurance",
  "свирепые атаки": "Savage Attacks",
  "везучий": "Lucky",
  "храбрый": "Brave",
  "проворство полуросликов": "Halfling Nimbleness",
  "естественная скрытность": "Naturally Stealthy",
  "наследие фей": "Fey Ancestry",
  "универсальность навыков": "Skill Versatility",
  "адское сопротивление": "Hellish Resistance",
  "дьявольское наследие": "Infernal Legacy",
  "обострённые чувства": "Keen Senses",
  "транс": "Trance",
  "владение эльфийским оружием": "Elf Weapon Training",
  "заговор": "Cantrip",
  "дополнительный язык": "Extra Language"
};

export function spellIconByName(sp) {
  if (!sp) return "";
  return SPELL_ICONS[String(sp.nameEn || "").trim()] || SPELL_ICONS[SPELL_RU[String(sp.name || "").trim().toLowerCase()]] || "";
}

export function featureIconByName(f) {
  if (!f) return "";
  const en = String(f.nameEn || FEATURE_RU[String(f.name || "").trim().toLowerCase()] || "").trim();
  if (en && FEATURE_ICONS[en]) return FEATURE_ICONS[en];
  if (en.includes(":") && FEATURE_ICONS[en.split(":")[0].trim()]) return FEATURE_ICONS[en.split(":")[0].trim()];
  return INV_BY_NAME.get(lower(f.name)) || "";
}
