export const SEED_ID = "kirion-thorndike";

export function kirion() {
  return {
    name: "Кирион Торндайк",
    archived: false,
    portrait: "",
    info: {
      race: "Тифлинг",
      subrace: "Потомок Мефистофеля",
      cls: "Колдун",
      subclass: "Исчадие",
      level: 5,
      background: "Механик",
      alignment: "Хаотично-добрый",
      age: "16",
      xp: 6500,
      setting: "Империя · готик-стимпанк · Средний город",
      patron: "Мефистофель",
      pactBoon: "Договор гримуара",
      player: "Weiss"
    },
    abilities: { str: 8, dex: 14, con: 16, int: 18, wis: 10, cha: 10 },
    saves: { wis: true, cha: true },
    skills: { history: 1, investigation: 1, perception: 1, sleightOfHand: 1, arcana: 1 },
    hitDie: "d8",
    casterType: "pact",
    spellAbility: "int",
    armor: { name: "Проклёпанная кожа", base: 12, dexCap: "full", shield: false, bonus: 0 },
    speed: 30,
    initBonus: 0,
    senses: "Тёмное зрение 60 фт",
    hp: { current: 43, temp: 0, maxOverride: null, bonusPerLevel: 0, hitDiceUsed: 0, deathSuccess: 0, deathFail: 0 },
    slotsUsed: {},
    pactUsed: 0,
    conditions: {},
    exhaustion: 0,
    concentration: "",
    damageSwap: { enabled: true, from: "fire", to: "cold", label: "Ледяная кровь" },
    resistances: "Огонь (Адское сопротивление)",
    proficiencies: {
      armor: "Лёгкие доспехи",
      weapons: "Простое оружие",
      tools: "Инструменты ремонтника, инструменты ювелира",
      languages: "Общий, Инфернальный, Гномий"
    },
    attacks: [
      {
        id: "at-eldritch-blast",
        name: "Мистический заряд",
        kind: "attack",
        ability: "spell",
        proficient: true,
        bonus: 0,
        damage: "1d10",
        addMod: false,
        dmgBonus: 0,
        damageType: "force",
        saveAbility: "",
        range: "120 фт",
        scaling: "cantrip-beams",
        count: 1,
        action: "action",
        notes: "Заговор колдуна. На 5 уровне выпускает 2 луча: для каждого совершается отдельный бросок атаки заклинанием (+7), и каждое попадание наносит 1d10 урона силовым полем. Лучи можно направить в одну цель или в разные."
      },
      {
        id: "at-frostbite",
        name: "Обморожение",
        kind: "save",
        ability: "spell",
        proficient: true,
        bonus: 0,
        damage: "1d6",
        addMod: false,
        dmgBonus: 0,
        damageType: "cold",
        saveAbility: "con",
        range: "60 фт",
        scaling: "cantrip-dice",
        count: 1,
        action: "action",
        notes: "Заговор колдуна. Спасбросок Телосложения против СЛ 15, при успехе урона нет. При провале цель получает 2d6 урона холодом и совершает с помехой следующий бросок атаки оружием до конца своего следующего хода."
      },
      {
        id: "at-dagger",
        name: "Кинжал",
        kind: "attack",
        ability: "dex",
        proficient: true,
        bonus: 0,
        damage: "1d4",
        addMod: true,
        dmgBonus: 0,
        damageType: "piercing",
        saveAbility: "",
        range: "5 фт / 20/60 фт",
        scaling: "none",
        count: 1,
        action: "action",
        notes: "Фехтовальное, лёгкое, метательное (20/60 фт). Атака +5, урон 1d4 + 2 колющего. Если вы атакуете одним кинжалом, вторым в другой руке можно атаковать бонусным действием, но без модификатора к урону."
      },
      {
        id: "at-light-crossbow",
        name: "Лёгкий арбалет",
        kind: "attack",
        ability: "dex",
        proficient: true,
        bonus: 0,
        damage: "1d8",
        addMod: true,
        dmgBonus: 0,
        damageType: "piercing",
        saveAbility: "",
        range: "80/320 фт",
        scaling: "none",
        count: 1,
        action: "action",
        notes: "Боеприпасы (болты), перезарядка: не больше одного выстрела за действие. Двуручное. Атака +5, урон 1d8 + 2 колющего. Стрельба по цели дальше 80 фт или когда враг стоит в 5 фт от вас совершается с помехой."
      }
    ],
    spells: [
      {
        id: "sp-eldritch-blast",
        name: "Мистический заряд",
        nameEn: "Eldritch Blast",
        level: 0,
        school: "evocation",
        action: "action",
        castTime: "",
        range: "120 фт",
        area: "",
        duration: "Мгновенная",
        concentration: false,
        ritual: false,
        components: "В, С",
        save: "",
        attack: true,
        damage: [{ dice: "1d10", type: "force", addMod: false }],
        scaling: "cantrip-beams",
        upcast: "",
        castAt: null,
        onSave: "",
        description: "Выпускает луч потрескивающей энергии в существо в пределах дальности. На 5 уровне вы создаёте 2 отдельных луча: их можно направить в одну цель или в разные. Для каждого луча совершается свой бросок атаки заклинанием (+7), каждое попадание наносит 1d10 урона силовым полем.",
        higher: "Количество лучей растёт с уровнем персонажа: 2 луча на 5 уровне, 3 на 11 уровне, 4 на 17 уровне.",
        source: "Колдун",
        cost: "free",
        uses: "",
        recharge: "always",
        used: 0,
        prepared: true
      },
      {
        id: "sp-frostbite",
        name: "Обморожение",
        nameEn: "Frostbite",
        level: 0,
        school: "evocation",
        action: "action",
        castTime: "",
        range: "60 фт",
        area: "",
        duration: "Мгновенная",
        concentration: false,
        ritual: false,
        components: "В, С",
        save: "con",
        attack: false,
        damage: [{ dice: "1d6", type: "cold", addMod: false }],
        scaling: "cantrip-dice",
        upcast: "",
        castAt: null,
        onSave: "При успехе: урона нет",
        description: "На существе, которое вы видите в пределах дальности, нарастает ледяная изморозь. Цель совершает спасбросок Телосложения против СЛ 15. При провале она получает 2d6 урона холодом и совершает с помехой следующий бросок атаки оружием до конца своего следующего хода.",
        higher: "Урон растёт с уровнем персонажа: 2d6 на 5 уровне, 3d6 на 11 уровне, 4d6 на 17 уровне.",
        source: "Колдун",
        cost: "free",
        uses: "",
        recharge: "always",
        used: 0,
        prepared: true
      },
      {
        id: "sp-prestidigitation",
        name: "Фокусы",
        nameEn: "Prestidigitation",
        level: 0,
        school: "transmutation",
        action: "action",
        castTime: "",
        range: "10 фт",
        area: "",
        duration: "До 1 часа",
        concentration: false,
        ritual: false,
        components: "В, С",
        save: "",
        attack: false,
        damage: [],
        scaling: "none",
        upcast: "",
        castAt: null,
        onSave: "",
        description: "Простой магический трюк на каждый день. Можно: создать безвредный сенсорный эффект (сноп искр, порыв ветра, тихую мелодию, странный запах); мгновенно зажечь или погасить свечу, факел или маленький костёр; очистить или испачкать предмет объёмом до 1 кубического фута; охладить, согреть или придать вкус неживому веществу объёмом до 1 кубического фута на 1 час; оставить на поверхности цветную метку или символ на 1 час; создать немагическую безделушку или иллюзорный образ размером с ладонь до конца следующего хода.",
        higher: "Не усиливается с уровнем. Одновременно могут действовать до трёх продолжительных эффектов, любой из них можно отменить действием.",
        source: "Колдун",
        cost: "free",
        uses: "",
        recharge: "always",
        used: 0,
        prepared: true
      },
      {
        id: "sp-mage-hand",
        name: "Волшебная рука",
        nameEn: "Mage Hand",
        level: 0,
        school: "conjuration",
        action: "action",
        castTime: "",
        range: "30 фт",
        area: "",
        duration: "1 минута",
        concentration: false,
        ritual: false,
        components: "В, С",
        save: "",
        attack: false,
        damage: [],
        scaling: "none",
        upcast: "",
        castAt: null,
        onSave: "",
        description: "В точке в пределах дальности появляется призрачная парящая рука. Действием вы управляете ей: перемещаете до 30 фт, открываете незапертые двери и контейнеры, достаёте или кладёте предметы, выливаете содержимое флакона. Рука не может атаковать, активировать магические предметы и переносить больше 10 фунтов. Она исчезает, если окажется дальше 30 фт от вас или если вы сотворите заговор снова.",
        higher: "Не усиливается с уровнем. Расовый заговор: заклинательная характеристика Интеллект по решению Мастера.",
        source: "Раса: Наследие Мефистофеля",
        cost: "free",
        uses: "",
        recharge: "always",
        used: 0,
        prepared: true
      },
      {
        id: "sp-message",
        name: "Послание",
        nameEn: "Message",
        level: 0,
        school: "transmutation",
        action: "action",
        castTime: "",
        range: "120 фт",
        area: "",
        duration: "1 раунд",
        concentration: false,
        ritual: false,
        components: "В, С, М (короткий кусок медной проволоки)",
        save: "",
        attack: false,
        damage: [],
        scaling: "none",
        upcast: "",
        castAt: null,
        onSave: "",
        description: "Вы указываете проволокой на существо в пределах дальности и шёпотом передаёте ему сообщение. Слышит его только цель, и она может так же шёпотом ответить: ответ слышите только вы. Магия проходит сквозь препятствия к знакомому существу, но её блокируют 1 фут камня, 1 дюйм обычного металла, тонкий лист свинца или 3 фута дерева.",
        higher: "Не усиливается с уровнем.",
        source: "Книга теней",
        cost: "free",
        uses: "",
        recharge: "always",
        used: 0,
        prepared: true
      },
      {
        id: "sp-mending",
        name: "Починка",
        nameEn: "Mending",
        level: 0,
        school: "transmutation",
        action: "minute",
        castTime: "1 минута",
        range: "Касание",
        area: "",
        duration: "Мгновенная",
        concentration: false,
        ritual: false,
        components: "В, С, М (два магнитных железняка)",
        save: "",
        attack: false,
        damage: [],
        scaling: "none",
        upcast: "",
        castAt: null,
        onSave: "",
        description: "Чинит одно повреждение на предмете, которого вы касаетесь: порванное звено цепи, сломанный ключ, треснувшую шестерню, прореху в плаще или протёкший бурдюк. Повреждение должно быть не больше 1 фута в любом измерении, после починки от него не остаётся и следа. Может восстановить и магический предмет, но не вернёт ему утраченную магию. Идеальный заговор для механика: полевой ремонт без мастерской и запчастей.",
        higher: "Не усиливается с уровнем.",
        source: "Книга теней",
        cost: "free",
        uses: "",
        recharge: "always",
        used: 0,
        prepared: true
      },
      {
        id: "sp-guidance",
        name: "Указание",
        nameEn: "Guidance",
        level: 0,
        school: "divination",
        action: "action",
        castTime: "",
        range: "Касание",
        area: "",
        duration: "Концентрация, вплоть до 1 минуты",
        concentration: true,
        ritual: false,
        components: "В, С",
        save: "",
        attack: false,
        damage: [],
        scaling: "none",
        upcast: "",
        castAt: null,
        onSave: "",
        description: "Вы касаетесь согласного существа. Один раз до окончания заклинания цель может бросить d4 и прибавить результат к одной проверке характеристики на свой выбор, до или после броска d20. После этого заклинание оканчивается.",
        higher: "Не усиливается с уровнем.",
        source: "Книга теней",
        cost: "free",
        uses: "",
        recharge: "always",
        used: 0,
        prepared: true
      },
      {
        id: "sp-armor-of-agathys",
        name: "Доспех Агатиса",
        nameEn: "Armor of Agathys",
        level: 1,
        school: "abjuration",
        action: "action",
        castTime: "",
        range: "На себя",
        area: "",
        duration: "1 час",
        concentration: false,
        ritual: false,
        components: "В, С, М (чашка воды)",
        save: "",
        attack: false,
        damage: [{ dice: "5", type: "cold", addMod: false }],
        scaling: "none",
        upcast: "5",
        castAt: null,
        onSave: "",
        description: "Вас окутывает призрачная ледяная броня. В ячейке договора 3 уровня вы получаете 15 временных хитов. Пока эти временные хиты не кончились, любое существо, попавшее по вам атакой ближнего боя, получает 15 урона холодом. Заклинание оканчивается, когда временные хиты исчерпаны, или через 1 час.",
        higher: "За каждый уровень ячейки выше 1 временные хиты и урон холодом растут на 5: 10 на 2 уровне, 15 на 3 уровне.",
        source: "Колдун",
        cost: "slot",
        uses: "",
        recharge: "short",
        used: 0,
        prepared: true
      },
      {
        id: "sp-misty-step",
        name: "Туманный шаг",
        nameEn: "Misty Step",
        level: 2,
        school: "conjuration",
        action: "bonus",
        castTime: "",
        range: "На себя",
        area: "",
        duration: "Мгновенная",
        concentration: false,
        ritual: false,
        components: "В",
        save: "",
        attack: false,
        damage: [],
        scaling: "none",
        upcast: "",
        castAt: null,
        onSave: "",
        description: "Окутавшись серебристым туманом, вы телепортируетесь на расстояние до 30 фт в свободное пространство, которое видите. Отличный способ вырваться из захвата, уйти от врага вплотную или занять позицию для заряда, не тратя основное действие. Тратит ячейку договора 3 уровня, но сам эффект от уровня ячейки не меняется.",
        higher: "Не усиливается от ячеек высокого уровня.",
        source: "Колдун",
        cost: "slot",
        uses: "",
        recharge: "short",
        used: 0,
        prepared: true
      },
      {
        id: "sp-suggestion",
        name: "Внушение",
        nameEn: "Suggestion",
        level: 2,
        school: "enchantment",
        action: "action",
        castTime: "",
        range: "30 фт",
        area: "",
        duration: "Концентрация, вплоть до 8 часов",
        concentration: true,
        ritual: false,
        components: "В, М (язык змеи и кусочек медовых сот или капля сладкого масла)",
        save: "wis",
        attack: false,
        damage: [],
        scaling: "none",
        upcast: "",
        castAt: null,
        onSave: "При успехе: внушение не действует",
        description: "Вы внушаете существу, которое видите и которое слышит и понимает вас, разумно звучащий курс действий в одну-две фразы. Цель совершает спасбросок Мудрости против СЛ 15 и при провале старается выполнить внушённое, пока длится заклинание или пока задача не выполнена. Существа, которых нельзя очаровать, невосприимчивы к нему, а явно вредное для цели внушение автоматически оканчивает заклинание.",
        higher: "Не усиливается от ячеек высокого уровня.",
        source: "Колдун",
        cost: "slot",
        uses: "",
        recharge: "short",
        used: 0,
        prepared: true
      },
      {
        id: "sp-hunger-of-hadar",
        name: "Голод Хадара",
        nameEn: "Hunger of Hadar",
        level: 3,
        school: "conjuration",
        action: "action",
        castTime: "",
        range: "150 фт",
        area: "сфера радиусом 20 фт",
        duration: "Концентрация, вплоть до 1 минуты",
        concentration: true,
        ritual: false,
        components: "В, С, М (маринованное щупальце осьминога)",
        save: "dex",
        attack: false,
        damage: [
          { dice: "2d6", type: "cold", addMod: false },
          { dice: "2d6", type: "acid", addMod: false }
        ],
        scaling: "none",
        upcast: "",
        castAt: null,
        onSave: "При успехе: кислотного урона нет",
        description: "Вы открываете врата в ледяную пустоту между звёздами: сферу абсолютной тьмы, которую не освещает никакой свет, а существа внутри ослеплены. Зона считается труднопроходимой местностью. Существо, начинающее ход в сфере, получает 2d6 урона холодом. Существо, заканчивающее ход в сфере, совершает спасбросок Ловкости против СЛ 15 или получает 2d6 урона кислотой от касания незримых щупалец.",
        higher: "Не усиливается от ячеек высокого уровня.",
        source: "Колдун",
        cost: "slot",
        uses: "",
        recharge: "short",
        used: 0,
        prepared: true
      },
      {
        id: "sp-counterspell",
        name: "Контрзаклинание",
        nameEn: "Counterspell",
        level: 3,
        school: "abjuration",
        action: "reaction",
        castTime: "",
        range: "60 фт",
        area: "",
        duration: "Мгновенная",
        concentration: false,
        ritual: false,
        components: "С",
        save: "",
        attack: false,
        damage: [],
        scaling: "none",
        upcast: "",
        castAt: null,
        onSave: "",
        description: "Реакцией, когда вы видите, как существо в пределах 60 фт творит заклинание, вы пытаетесь его прервать. Заклинание 3 уровня или ниже проваливается автоматически. Для заклинания 4 уровня и выше совершите проверку Интеллекта (+4) против СЛ 10 + уровень заклинания: при успехе оно тоже проваливается.",
        higher: "Ячейка более высокого уровня автоматически прерывает заклинания вплоть до своего уровня.",
        source: "Колдун",
        cost: "slot",
        uses: "",
        recharge: "short",
        used: 0,
        prepared: true
      },
      {
        id: "sp-fireball",
        name: "Огненный шар",
        nameEn: "Fireball",
        level: 3,
        school: "evocation",
        action: "action",
        castTime: "",
        range: "150 фт",
        area: "сфера радиусом 20 фт",
        duration: "Мгновенная",
        concentration: false,
        ritual: false,
        components: "В, С, М (крошечный шарик из гуано летучей мыши и серы)",
        save: "dex",
        attack: false,
        damage: [{ dice: "8d6", type: "fire", addMod: false }],
        scaling: "none",
        upcast: "1d6",
        castAt: null,
        onSave: "При успехе: половина урона",
        description: "Яркая искра срывается с пальца к точке в пределах дальности и взрывается. Каждое существо в сфере радиусом 20 фт совершает спасбросок Ловкости против СЛ 15 и при провале получает 8d6 урона. Благодаря дару Ледяная кровь у Кириона это не пламя, а взрыв ледяных осколков, и весь урон наносится холодом.",
        higher: "За каждый уровень ячейки выше 3 урон растёт на 1d6.",
        source: "Исчадие (расширенный список)",
        cost: "slot",
        uses: "",
        recharge: "short",
        used: 0,
        prepared: true
      },
      {
        id: "sp-burning-hands",
        name: "Огненные ладони",
        nameEn: "Burning Hands",
        level: 1,
        school: "evocation",
        action: "action",
        castTime: "",
        range: "На себя",
        area: "конус 15 фт",
        duration: "Мгновенная",
        concentration: false,
        ritual: false,
        components: "В, С",
        save: "dex",
        attack: false,
        damage: [{ dice: "3d6", type: "fire", addMod: false }],
        scaling: "none",
        upcast: "1d6",
        castAt: 2,
        onSave: "При успехе: половина урона",
        description: "Вы сводите большие пальцы, и из растопыренных ладоней вырывается тонкий веер пламени. С Ледяной кровью это не пламя, а поток ледяного ветра и инея. Каждое существо в конусе 15 фт совершает спасбросок Ловкости против СЛ 15 и при провале получает 4d6 урона холодом. Расовое заклинание: 1 раз за длинный отдых без ячейки, всегда как заклинание 2 уровня.",
        higher: "Как расовое заклинание всегда творится на 2 уровне: 4d6 вместо базовых 3d6.",
        source: "Раса: Наследие Мефистофеля",
        cost: "uses",
        uses: "1",
        recharge: "long",
        used: 0,
        prepared: true
      },
      {
        id: "sp-flame-blade",
        name: "Пылающий клинок",
        nameEn: "Flame Blade",
        level: 2,
        school: "evocation",
        action: "bonus",
        castTime: "",
        range: "На себя",
        area: "",
        duration: "Концентрация, вплоть до 10 минут",
        concentration: true,
        ritual: false,
        components: "В, С, М (лист сумаха)",
        save: "",
        attack: true,
        damage: [{ dice: "3d6", type: "fire", addMod: false }],
        scaling: "none",
        upcast: "",
        castAt: 3,
        onSave: "",
        description: "В свободной руке возникает клинок, у Кириона благодаря Ледяной крови выкованный из сияющего льда. Пока заклинание длится, действием вы совершаете им рукопашную атаку заклинанием (+7) и при попадании наносите 3d6 урона холодом. Клинок излучает яркий свет в радиусе 10 фт и тусклый ещё на 10 фт. Если вы его отпустите, его можно призвать снова бонусным действием.",
        higher: "Расовое заклинание: 1 раз за длинный отдых без ячейки, всегда как заклинание 3 уровня. Урон этого заклинания растёт на 1d6 только начиная с 4 уровня, поэтому он остаётся 3d6.",
        source: "Раса: Наследие Мефистофеля",
        cost: "uses",
        uses: "1",
        recharge: "long",
        used: 0,
        prepared: true
      }
    ],
    features: [
      {
        id: "f-pact-magic",
        name: "Магия договора",
        nameEn: "Pact Magic",
        category: "class",
        source: "class",
        action: "passive",
        recharge: "short",
        uses: "",
        used: 0,
        slot: "none",
        range: "",
        duration: "",
        save: "",
        damage: [],
        description: "Магия колдуна идёт от договора с Мефистофелем. У Кириона 2 ячейки договора, и обе всегда 3 уровня: любое заклинание колдуна творится сразу на 3 уровне. Потраченные ячейки восстанавливаются после короткого или длинного отдыха. По решению Мастера заклинательная характеристика Интеллект (+4): СЛ спасброска 15, бонус атаки заклинанием +7.",
        effect: "2 ячейки 3 уровня, восстанавливаются после короткого отдыха"
      },
      {
        id: "f-dark-ones-blessing",
        name: "Благословение Тёмного",
        nameEn: "Dark One's Blessing",
        category: "class",
        source: "class",
        action: "passive",
        recharge: "always",
        uses: "",
        used: 0,
        slot: "none",
        range: "",
        duration: "",
        save: "",
        damage: [{ dice: "9", type: "temp", addMod: false }],
        description: "Когда вы опускаете хиты враждебного существа до 0, вы получаете временные хиты, равные модификатору Интеллекта + уровень колдуна: 4 + 5 = 9. Срабатывает автоматически при каждом таком добивании и не требует действия. Временные хиты не складываются: вы выбираете, оставить имеющиеся или взять новые. По домашнему правилу используется Интеллект вместо Харизмы.",
        effect: "Добил врага: 9 временных хитов"
      },
      {
        id: "f-pact-of-the-tome",
        name: "Договор гримуара",
        nameEn: "Pact of the Tome",
        category: "class",
        source: "class",
        action: "passive",
        recharge: "always",
        uses: "",
        used: 0,
        slot: "none",
        range: "",
        duration: "",
        save: "",
        damage: [],
        description: "Мефистофель вручил Кириону Книгу теней. Пока книга при нём, он знает 3 дополнительных заговора из списков любых классов: Послание, Починка и Указание; для него они считаются заговорами колдуна. Если книга утеряна, часовой церемонией во время короткого или длинного отдыха можно получить новую, а старая при этом обращается в прах.",
        effect: "+3 заговора из Книги теней"
      },
      {
        id: "f-eldritch-invocations",
        name: "Таинственные воззвания",
        nameEn: "Eldritch Invocations",
        category: "class",
        source: "class",
        action: "passive",
        recharge: "always",
        uses: "",
        used: 0,
        slot: "none",
        range: "",
        duration: "",
        save: "",
        damage: [],
        description: "Фрагменты запретного знания, которые навсегда усиливают колдуна. На 5 уровне Кирион знает 3 воззвания: Мистическое зрение, Маска многих лиц и Дьявольская живучесть. При получении нового уровня колдуна одно известное воззвание можно заменить другим.",
        effect: "3 воззвания на 5 уровне"
      },
      {
        id: "inv-eldritch-sight",
        name: "Мистическое зрение",
        nameEn: "Eldritch Sight",
        category: "invocation",
        source: "class",
        action: "action",
        recharge: "always",
        uses: "",
        used: 0,
        slot: "none",
        range: "На себя (30 фт)",
        duration: "Концентрация, вплоть до 10 минут",
        save: "",
        damage: [],
        description: "Вы можете неограниченно творить Обнаружение магии без траты ячейки. Пока заклинание действует, вы чувствуете присутствие магии в пределах 30 фт, а действием видите слабую ауру вокруг любого видимого магического существа или предмета и узнаёте её школу. Для охотника за артефактами это первый инструмент: прежде чем трогать находку, Кирион всегда смотрит, что в ней светится.",
        effect: "Обнаружение магии без ячейки, сколько угодно раз"
      },
      {
        id: "inv-mask-of-many-faces",
        name: "Маска многих лиц",
        nameEn: "Mask of Many Faces",
        category: "invocation",
        source: "class",
        action: "action",
        recharge: "always",
        uses: "",
        used: 0,
        slot: "none",
        range: "На себя",
        duration: "1 час",
        save: "",
        damage: [],
        description: "Вы можете неограниченно творить Маскировку без траты ячейки. На 1 час вы меняете внешность, одежду и снаряжение: рост в пределах 1 фута, телосложение, цвет кожи, можно даже спрятать синеву и рога. Иллюзия не выдерживает касания. Существо, которое тратит действие на изучение, распознаёт её успешной проверкой Интеллекта (Анализ) против СЛ 15.",
        effect: "Маскировка без ячейки на 1 час, раскрыть: Анализ СЛ 15"
      },
      {
        id: "inv-fiendish-vigor",
        name: "Дьявольская живучесть",
        nameEn: "Fiendish Vigor",
        category: "invocation",
        source: "class",
        action: "action",
        recharge: "always",
        uses: "",
        used: 0,
        slot: "none",
        range: "На себя",
        duration: "1 час",
        save: "",
        damage: [{ dice: "1d4+4", type: "temp", addMod: false }],
        description: "Вы можете неограниченно творить на себя Псевдожизнь как заклинание 1 уровня без траты ячейки. Вы получаете 1d4 + 4 временных хита на 1 час. Временные хиты не складываются, но заклинание можно повторять сколько угодно, пока не выпадет хороший результат: удобно делать это перед каждой подозрительной дверью.",
        effect: "1d4 + 4 временных хита без ячейки"
      },
      {
        id: "g-voice-in-the-head",
        name: "Голос в голове",
        nameEn: "Voice in the Head",
        category: "gift",
        source: "dm",
        action: "passive",
        recharge: "always",
        uses: "",
        used: 0,
        slot: "none",
        range: "Любое расстояние",
        duration: "",
        save: "",
        damage: [],
        description: "Между Кирионом и Мефистофелем существует телепатическая связь. Они могут мысленно говорить друг с другом на любом расстоянии. Связь открыта всякий раз, когда этого пожелает Мефистофель.",
        effect: "Телепатия с Мефистофелем на любом расстоянии"
      },
      {
        id: "g-ice-blood",
        name: "Ледяная кровь",
        nameEn: "Ice Blood",
        category: "gift",
        source: "dm",
        action: "passive",
        recharge: "always",
        uses: "",
        used: 0,
        slot: "none",
        range: "",
        duration: "",
        save: "",
        damage: [],
        description: "Весь урон Кириона, который должен быть огненным, становится уроном холодом. Это касается всего: заклинаний, оружия, предметов и любых других источников его урона. Огненный шар оборачивается взрывом ледяных осколков, Огненные ладони превращаются в веер инея, а Пылающий клинок становится клинком изо льда.",
        effect: "Весь огненный урон становится холодом: применяется на листе автоматически"
      },
      {
        id: "g-forbidden-scholar",
        name: "Знаток запретного",
        nameEn: "Forbidden Scholar",
        category: "gift",
        source: "dm",
        action: "passive",
        recharge: "always",
        uses: "",
        used: 0,
        slot: "none",
        range: "",
        duration: "",
        save: "",
        damage: [],
        description: "Годы чтения запрещённых книг не прошли даром. Кирион получает владение навыком Магия (+7). Если бы он уже владел этим навыком, владение стало бы компетентностью и бонус мастерства удваивался бы. Владение уже отмечено на листе навыков.",
        effect: "Владение Магией (+7)"
      },
      {
        id: "g-archive-of-knowledge",
        name: "Архив знаний",
        nameEn: "Archive of Knowledge",
        category: "gift",
        source: "own",
        action: "special",
        recharge: "long",
        uses: "=pb",
        used: 0,
        slot: "none",
        range: "",
        duration: "",
        save: "",
        damage: [],
        description: "Кирион цепко запоминает прочитанное. Когда он пытается вспомнить что-то из прочитанного (строку из книги, чертёж или формулу), он совершает проверку Истории (+7) с преимуществом. Количество использований равно бонусу мастерства (3), они восстанавливаются после длинного отдыха.",
        effect: "Преимущество на Историю, когда вспоминаешь прочитанное"
      },
      {
        id: "g-contract-genius",
        name: "Гений договоров",
        nameEn: "Contract Genius",
        category: "gift",
        source: "own",
        action: "passive",
        recharge: "always",
        uses: "",
        used: 0,
        slot: "none",
        range: "",
        duration: "",
        save: "",
        damage: [],
        description: "Кирион всегда знает точную формулировку любого проклятия или магического договора, наложенного на него самого или на существо, которое он видит. Все условия, оговорки и мелкий шрифт открываются ему так, будто он читает контракт с листа.",
        effect: "Точная формулировка любого проклятия или договора"
      },
      {
        id: "r-darkvision",
        name: "Тёмное зрение",
        nameEn: "Darkvision",
        category: "race",
        source: "race",
        action: "passive",
        recharge: "always",
        uses: "",
        used: 0,
        slot: "none",
        range: "60 фт",
        duration: "",
        save: "",
        damage: [],
        description: "В пределах 60 фт вы видите при тусклом освещении как при ярком, а в темноте как при тусклом. В темноте вы не различаете цвета, только оттенки серого. Магическую тьму, например сферу Голода Хадара, тёмное зрение не пробивает.",
        effect: "Видит в темноте на 60 фт"
      },
      {
        id: "r-hellish-resistance",
        name: "Адское сопротивление",
        nameEn: "Hellish Resistance",
        category: "race",
        source: "race",
        action: "passive",
        recharge: "always",
        uses: "",
        used: 0,
        slot: "none",
        range: "",
        duration: "",
        save: "",
        damage: [],
        description: "Адская кровь даёт сопротивление урону огнём: такой урон уменьшается вдвое. С учётом дара Ледяная кровь можно обсудить с Мастером замену сопротивления огню на сопротивление холоду, чтобы черта соответствовала ледяной природе Кириона.",
        effect: "Сопротивление урону огнём"
      },
      {
        id: "r-legacy-of-mephistopheles",
        name: "Наследие Мефистофеля",
        nameEn: "Legacy of Mephistopheles",
        category: "race",
        source: "race",
        action: "passive",
        recharge: "long",
        uses: "",
        used: 0,
        slot: "none",
        range: "",
        duration: "",
        save: "",
        damage: [],
        description: "Вы знаете заговор Волшебная рука. С 3 уровня вы можете 1 раз за длинный отдых сотворить Огненные ладони как заклинание 2 уровня, а с 5 уровня 1 раз за длинный отдых Пылающий клинок как заклинание 3 уровня. По домашнему правилу заклинательная характеристика для них Интеллект: СЛ 15, атака +7. Сами заклинания находятся на вкладке Магия.",
        effect: "Волшебная рука, Огненные ладони и Пылающий клинок 1 раз за длинный отдых"
      },
      {
        id: "b-mechanic",
        name: "Механик",
        nameEn: "Mechanic",
        category: "background",
        source: "",
        action: "passive",
        recharge: "always",
        uses: "",
        used: 0,
        slot: "none",
        range: "",
        duration: "",
        save: "",
        damage: [],
        description: "Кирион вырос среди шестерёнок, паровых котлов и мастерских Среднего Города. Он владеет навыками Внимательность и Ловкость рук, а также инструментами ремонтника. Умение «Свой в мастерских»: мастерские и инженеры Среднего Города охотно одолжат ему инструменты и уголок для работы, а заодно поговорят о деле.",
        effect: "Свой в мастерских: инструменты, место для работы и разговор о деле"
      }
    ],
    items: [
      {
        id: "it-engineering-monocle",
        name: "Инженерный монокль",
        type: "artifact",
        rarity: "uncommon",
        qty: 1,
        weight: 0,
        equipped: true,
        attuned: false,
        requiresAttunement: false,
        action: "passive",
        uses: "",
        recharge: "always",
        used: 0,
        damage: [],
        description: "Самодельная линза в латунной оправе, по ободку которой Кирион собственноручно выгравировал руны. Сквозь неё видны мельчайшие зазоры, следы пайки и тонкие линии рунных цепей. Пока монокль надет, Кирион совершает с преимуществом проверки Анализа (+7) и Магии (+7), когда разбирает механизм или определяет, какой артефакт перед ним.",
        effect: "Преимущество на Анализ и Магию при разборе механизмов и опознании артефактов",
        value: "Самодельный"
      },
      {
        id: "it-trophy-capacitor",
        name: "Трофейный конденсатор",
        type: "artifact",
        rarity: "rare",
        qty: 1,
        weight: 2,
        equipped: false,
        attuned: false,
        requiresAttunement: false,
        action: "bonus",
        uses: "1",
        recharge: "long",
        used: 0,
        damage: [],
        description: "Аккумулятор на паровой тяге, вытащенный из чужого артефакта: латунный цилиндр с манометром, внутри которого до сих пор что-то гудит. Бонусным действием Кирион восстанавливает одно потраченное использование дара покровителя, артефакта или расового заклинания, как будто его и не тратили. Срабатывает 1 раз и перезаряжается после длинного отдыха.",
        effect: "Вернуть 1 использование дара, артефакта или расового заклинания",
        value: "около 800 зм"
      },
      {
        id: "it-patron-quill",
        name: "Перо покровителя",
        type: "artifact",
        rarity: "uncommon",
        qty: 1,
        weight: 0,
        equipped: false,
        attuned: false,
        requiresAttunement: false,
        action: "action",
        uses: "",
        recharge: "always",
        used: 0,
        damage: [],
        description: "Подарок Мефистофеля: перо цвета запёкшейся крови с покрытым инеем кончиком. Действием Кирион призывает его спектральную копию, которая в течение 1 минуты сама стенографирует разговор или переписывает надпись прямо на бумагу. Перо пишет само, так что руки Кириона остаются свободными.",
        effect: "1 минута стенографии разговора или надписи",
        value: "Не продаётся (дар покровителя)"
      },
      {
        id: "it-magic-trace-compass",
        name: "Компас магического следа",
        type: "artifact",
        rarity: "rare",
        qty: 1,
        weight: 1,
        equipped: false,
        attuned: false,
        requiresAttunement: false,
        action: "action",
        uses: "",
        recharge: "always",
        used: 0,
        damage: [],
        description: "Зачарованный компас в потёртом латунном корпусе, стрелка которого выкована из тёмного металла и едва заметно светится. Действием Кирион сверяется с ним, и стрелка указывает направление к ближайшей значительной магической аномалии или артефакту в пределах 1 мили.",
        effect: "Направление к ближайшей магической аномалии или артефакту в пределах 1 мили",
        value: "около 1000 зм"
      },
      {
        id: "it-book-of-shadows",
        name: "Книга теней",
        type: "book",
        rarity: "story",
        qty: 1,
        weight: 3,
        equipped: true,
        attuned: false,
        requiresAttunement: false,
        action: "",
        uses: "",
        recharge: "always",
        used: 0,
        damage: [],
        description: "Гримуар, полученный по Договору гримуара: переплёт из тёмной кожи с серебряным тиснением, страницы холодные на ощупь, а пометки на полях Кирион уже делает сам. Пока книга при нём, он знает три заговора: Послание, Починка и Указание. Если книга утеряна, её можно воссоздать часовой церемонией во время отдыха.",
        effect: "Предмет договора: 3 дополнительных заговора",
        value: "Не продаётся"
      },
      {
        id: "it-studded-leather",
        name: "Проклёпанная кожа",
        type: "armor",
        rarity: "common",
        qty: 1,
        weight: 13,
        equipped: true,
        attuned: false,
        requiresAttunement: false,
        action: "",
        uses: "",
        recharge: "always",
        used: 0,
        damage: [],
        description: "Длинное кожаное пальто, укреплённое заклёпками, с множеством карманов, которые Кирион пришил сам. Лёгкий доспех: КД 12 + модификатор Ловкости, итого КД 14. Не мешает ни скрытности, ни сотворению заклинаний.",
        effect: "КД 14 (12 + Ловкость)",
        value: "45 зм"
      },
      {
        id: "it-dagger",
        name: "Кинжал",
        type: "weapon",
        rarity: "common",
        qty: 2,
        weight: 1,
        equipped: true,
        attuned: false,
        requiresAttunement: false,
        action: "action",
        uses: "",
        recharge: "always",
        used: 0,
        damage: [{ dice: "1d4", type: "piercing", addMod: true }],
        description: "Простой стальной кинжал. Фехтовальное, лёгкое, метательное оружие (20/60 фт). Атака +5, урон 1d4 + 2 колющего. Второй кинжал спрятан в сапоге, на всякий случай.",
        effect: "Атака +5, 1d4 + 2 колющего",
        value: "2 зм"
      },
      {
        id: "it-light-crossbow",
        name: "Лёгкий арбалет",
        type: "weapon",
        rarity: "common",
        qty: 1,
        weight: 5,
        equipped: true,
        attuned: false,
        requiresAttunement: false,
        action: "action",
        uses: "",
        recharge: "always",
        used: 0,
        damage: [{ dice: "1d8", type: "piercing", addMod: true }],
        description: "Компактный арбалет, в механизм натяжения которого Кирион, конечно же, уже успел залезть. Дальность 80/320 фт, перезарядка, двуручное. Атака +5, урон 1d8 + 2 колющего.",
        effect: "Атака +5, 1d8 + 2 колющего",
        value: "25 зм"
      },
      {
        id: "it-crossbow-bolts",
        name: "Арбалетные болты",
        type: "ammo",
        rarity: "common",
        qty: 20,
        weight: 0.075,
        equipped: false,
        attuned: false,
        requiresAttunement: false,
        action: "",
        uses: "",
        recharge: "always",
        used: 0,
        damage: [],
        description: "Болты для лёгкого арбалета в кожаном колчане. После боя половину выпущенных болтов можно найти и собрать.",
        effect: "Боеприпасы для лёгкого арбалета",
        value: "1 зм за 20 шт."
      },
      {
        id: "it-tinkers-tools",
        name: "Инструменты ремонтника",
        type: "tool",
        rarity: "common",
        qty: 1,
        weight: 10,
        equipped: false,
        attuned: false,
        requiresAttunement: false,
        action: "",
        uses: "",
        recharge: "always",
        used: 0,
        damage: [],
        description: "Набор механика: отвёртки, щипцы, пинцеты, крошечные гаечные ключи, паяльник и коробочка винтиков. Владение позволяет добавлять бонус мастерства (+3) к проверкам ремонта, сборки и разборки механизмов. Каждый час работы восстанавливает повреждённому предмету 10 хитов.",
        effect: "Ремонт и сборка механизмов, +3 к проверкам",
        value: "50 зм"
      },
      {
        id: "it-jewelers-tools",
        name: "Инструменты ювелира",
        type: "tool",
        rarity: "common",
        qty: 1,
        weight: 2,
        equipped: false,
        attuned: false,
        requiresAttunement: false,
        action: "",
        uses: "",
        recharge: "always",
        used: 0,
        damage: [],
        description: "Маленькая пила и молоточек, напильники, щипцы и лупа. Нужны для огранки камней, тонкой гравировки и работы с мельчайшими деталями: именно ими выгравированы руны на инженерном монокле. Владение добавляет бонус мастерства (+3) к проверкам с этими инструментами.",
        effect: "Огранка, гравировка и оценка драгоценностей",
        value: "25 зм"
      },
      {
        id: "it-component-pouch",
        name: "Мешочек с компонентами",
        type: "gear",
        rarity: "common",
        qty: 1,
        weight: 2,
        equipped: false,
        attuned: false,
        requiresAttunement: false,
        action: "",
        uses: "",
        recharge: "always",
        used: 0,
        damage: [],
        description: "Водонепроницаемый поясной мешочек с отделениями для материальных компонентов. Заменяет все материальные компоненты без указанной цены: чашку воды для Доспеха Агатиса, маринованное щупальце для Голода Хадара и прочее.",
        effect: "Заменяет материальные компоненты без цены",
        value: "25 зм"
      },
      {
        id: "it-backpack",
        name: "Рюкзак",
        type: "gear",
        rarity: "common",
        qty: 1,
        weight: 5,
        equipped: false,
        attuned: false,
        requiresAttunement: false,
        action: "",
        uses: "",
        recharge: "always",
        used: 0,
        damage: [],
        description: "Вместительный кожаный рюкзак с медными пряжками. Вмещает до 1 кубического фута или 30 фунтов снаряжения, и, судя по весу, Кирион всегда набивает его до предела.",
        effect: "Вмещает 30 фунтов снаряжения",
        value: "2 зм"
      },
      {
        id: "it-hooded-lantern",
        name: "Фонарь с колпаком",
        type: "gear",
        rarity: "common",
        qty: 1,
        weight: 2,
        equipped: false,
        attuned: false,
        requiresAttunement: false,
        action: "action",
        uses: "",
        recharge: "always",
        used: 0,
        damage: [],
        description: "Масляный фонарь с откидным колпаком. Горит 6 часов на одной фляге масла и даёт яркий свет в радиусе 30 фт и тусклый ещё на 30 фт. Опустив колпак действием, свет можно приглушить до тусклого в радиусе 5 фт.",
        effect: "Яркий свет 30 фт, 6 часов на фляге масла",
        value: "5 зм"
      },
      {
        id: "it-oil-flask",
        name: "Масло, фляга",
        type: "consumable",
        rarity: "common",
        qty: 2,
        weight: 1,
        equipped: false,
        attuned: false,
        requiresAttunement: false,
        action: "action",
        uses: "",
        recharge: "none",
        used: 0,
        damage: [],
        description: "Глиняная фляга лампового масла. Её хватает, чтобы заправить фонарь на 6 часов. Действием флягу можно выплеснуть на существо в 5 фт или метнуть на 20 фт: это дальнобойная атака импровизированным оружием (+2), и при попадании цель покрывается маслом. Если до того, как масло высохнет (1 минута), цель получит урон огнём, она получает ещё 5 урона огнём. Сам Кирион поджечь масло не может: Ледяная кровь превращает его огненный урон в холод, так что нужен огонь союзника или другой посторонний источник.",
        effect: "Заправка фонаря на 6 часов",
        value: "1 см"
      },
      {
        id: "it-hempen-rope",
        name: "Верёвка пеньковая 50 фт",
        type: "gear",
        rarity: "common",
        qty: 1,
        weight: 10,
        equipped: false,
        attuned: false,
        requiresAttunement: false,
        action: "",
        uses: "",
        recharge: "always",
        used: 0,
        damage: [],
        description: "Пятьдесят футов крепкой пеньковой верёвки, аккуратно смотанной и перехваченной ремешком. Порвать её можно проверкой Силы против СЛ 17.",
        effect: "50 фт верёвки",
        value: "1 зм"
      },
      {
        id: "it-healers-kit",
        name: "Набор целителя",
        type: "consumable",
        rarity: "common",
        qty: 1,
        weight: 3,
        equipped: false,
        attuned: false,
        requiresAttunement: false,
        action: "action",
        uses: "10",
        recharge: "none",
        used: 0,
        damage: [],
        description: "Кожаная сумка с бинтами, мазями и шинами. Действием можно потратить одно использование и стабилизировать существо с 0 хитов без проверки Медицины. Кирион всегда носит с собой больше, чем нужно: лучше лишний бинт, чем потерянный друг.",
        effect: "Стабилизировать существо с 0 хитов, 10 использований",
        value: "5 зм"
      },
      {
        id: "it-rations",
        name: "Рационы",
        type: "consumable",
        rarity: "common",
        qty: 3,
        weight: 2,
        equipped: false,
        attuned: false,
        requiresAttunement: false,
        action: "",
        uses: "",
        recharge: "none",
        used: 0,
        damage: [],
        description: "Сухари, вяленое мясо, сушёные фрукты и орехи, упакованные по дневной порции. Каждая порция кормит одного человека в течение дня.",
        effect: "Еда на 1 день за порцию",
        value: "5 см за порцию"
      },
      {
        id: "it-blueprint-notebook",
        name: "Блокнот с чертежами",
        type: "misc",
        rarity: "common",
        qty: 1,
        weight: 1,
        equipped: false,
        attuned: false,
        requiresAttunement: false,
        action: "",
        uses: "",
        recharge: "always",
        used: 0,
        damage: [],
        description: "Потрёпанный блокнот в кожаной обложке, исписанный схемами механизмов, зарисовками рунных цепей и заметками на полях. Сюда Кирион заносит всё, что узнал об артефактах, прежде чем рассказать об этом покровителю.",
        effect: "Чертежи, формулы и заметки об артефактах",
        value: "Бесценен для владельца"
      },
      {
        id: "it-tin-mug",
        name: "Жестяная кружка",
        type: "misc",
        rarity: "common",
        qty: 1,
        weight: 0.5,
        equipped: false,
        attuned: false,
        requiresAttunement: false,
        action: "",
        uses: "",
        recharge: "always",
        used: 0,
        damage: [],
        description: "Помятая жестяная кружка, с которой Кирион почти не расстаётся. Когда он нервничает, чай в ней стынет за секунду, а по стенкам бежит иней: выдаёт его надёжнее любого детектора лжи.",
        effect: "Чай стынет за секунду, когда Кирион нервничает",
        value: "2 мм"
      }
    ],
    coins: { cp: 0, sp: 8, ep: 0, gp: 15, pp: 0 },
    personality: {
      appearance: "Шестнадцатилетний тифлинг с синей кожей и тёмными изогнутыми рогами. На глазу поблёскивает инженерный монокль в латунной оправе, а пальцы вечно в саже и машинном масле. Носит длинное пальто с бесчисленными карманами, набитыми винтиками и записками, и почти никогда не расстаётся с жестяной кружкой.",
      traits: "Не умеет врать спокойно: когда нервничает или недоговаривает, воздух вокруг сам холодает, а чай в кружке стынет за секунду. С родителями играет ровно в обратное: всегда говорит, что всё в порядке, даже когда это не так, лишь бы не заставлять их волноваться и доказать, что на него можно положиться.",
      ideals: "Знание - сила. В этом мире твоя сила равна сумме твоего интеллекта, и ничего больше. Хочет быть как Рэй: свободно изучать всё, что есть в мире, от обычных часовых механизмов до самых немыслимых техник, и повидать самые разные инженерные решения.",
      bonds: "Семья - это всё. Готов сделать что угодно ради родителей и искренне переживает за каждого из них. Смерти в деле боится меньше, чем того, что она разобьёт им сердце, поэтому должен доказать, что способен на многое и что им можно гордиться.",
      flaws: "Боится опасности, и именно поэтому всегда готов к худшему: перестраховывается, берёт с собой больше, чем нужно, всегда начеку и ни на миг не расслабляется. Со стороны это выглядит как сила характера, но на деле это постоянное напряжение на грани паранойи, которое выматывает в первую очередь его самого.",
      backstory: "Кирион Торндайк, приёмный сын Халвара и Маргарэт Торндайк, владельцев крупной таверны в Среднем Городе. Семья достаточно влиятельна, чтобы с ней считались Верхний Город и правительство. В семье 9 приёмных детей, трое из них синие тифлинги, включая Кириона. Друг семьи, Рэй, бронзовый драконорождённый лет 45, торговец артефактами и древностями, осел в городе несколько лет назад после странствий по континенту и стал для Кириона как старший брат. В 16 лет Кирион рвётся в дело: искать артефакты, изучать всё подряд, быть крутым, как Рэй, а теперь ещё и добывать знания для Мефистофеля.",
      allies: "Семья Торндайк, таверна в Среднем Городе. Рэй, торговец артефактами."
    },
    notes: {
      patron: [
        {
          id: "n-patron-pact",
          title: "Как был заключён договор",
          subtitle: "",
          status: "",
          attitude: "",
          text: "Систематически изучал магию и артефакты не из праздного любопытства, а чтобы Рэй наконец начал воспринимать его всерьёз и взял в дело. В этих поисках прочитал не одну запрещённую книгу и докопался слишком глубоко, до самого Мефистофеля. Именно упёртость, одержимость делом и готовность копать до победного: то, что тот в нём особенно ценит. Договор заключён ещё в предыстории, до начала игры."
        },
        {
          id: "n-patron-terms",
          title: "Условия контракта",
          subtitle: "",
          status: "",
          attitude: "",
          text: "Как указано в контракте, Мефистофель ждёт исследований, поиска артефактов и всего прочего, что может его заинтересовать. За нахождение информации об артефакте и её разъяснение положена награда (возможно, артефакт придётся отдать)."
        }
      ],
      quests: [
        {
          id: "q-mephisto-research",
          title: "Исследования для Мефистофеля",
          subtitle: "Условия контракта с покровителем",
          status: "active",
          attitude: "",
          text: "Находить артефакты и сведения о них, разбираться, как они устроены, и разъяснять это покровителю. По контракту за найденную и объяснённую информацию положена награда, но сам артефакт, возможно, придётся отдать."
        },
        {
          id: "q-prove-to-ray",
          title: "Доказать Рэю, что я готов",
          subtitle: "Попасть в дело",
          status: "active",
          attitude: "",
          text: "Показать Рэю, что Кирион уже не ребёнок, а надёжный напарник: знает своё дело, не теряет голову рядом с опасными находками и умеет работать с артефактами. Цель: чтобы Рэй наконец взял его в дело."
        }
      ],
      people: [
        {
          id: "p-ray",
          title: "Рэй",
          subtitle: "Бронзовый драконорождённый, около 45 лет, торговец артефактами и древностями",
          status: "",
          attitude: "ally",
          text: "Осел в городе несколько лет назад после долгих странствий по континенту. Для Кириона он как старший брат и пример для подражания: свободно изучает всё, что есть в мире, и знает об артефактах больше всех, кого Кирион встречал. Скорее всего, именно он возьмёт на себя ответственность за Кириона перед Халваром и Маргарэт."
        },
        {
          id: "p-halvar",
          title: "Халвар Торндайк",
          subtitle: "Приёмный отец, владелец крупной таверны в Среднем Городе",
          status: "",
          attitude: "ally",
          text: "Приёмный отец Кириона. Вместе с Маргарэт держит крупную таверну в Среднем Городе и растит девятерых приёмных детей. Кирион готов на всё ради него и никогда не признается, если что-то пошло не так."
        },
        {
          id: "p-margaret",
          title: "Маргарэт Торндайк",
          subtitle: "Приёмная мать, совладелица таверны",
          status: "",
          attitude: "ally",
          text: "Приёмная мать Кириона и совладелица таверны. Семья Торндайк достаточно влиятельна, чтобы с ней считались Верхний Город и правительство. Кирион всегда говорит ей, что всё в порядке, лишь бы она не волновалась."
        },
        {
          id: "p-siblings",
          title: "Братья и сёстры",
          subtitle: "9 приёмных детей в семье",
          status: "",
          attitude: "ally",
          text: "В семье Торндайк 9 приёмных детей, трое из них синие тифлинги, включая Кириона. Родство по крови с одним или обоими другими синими тифлингами ещё предстоит решить."
        },
        {
          id: "p-mephistopheles",
          title: "Мефистофель",
          subtitle: "Архидьявол, покровитель",
          status: "",
          attitude: "neutral",
          text: "Архидьявол и покровитель Кириона. Договор заключён, когда Кирион в поисках знаний докопался слишком глубоко. Мефистофель ценит в нём упёртость, одержимость делом и готовность копать до победного, ждёт исследований и артефактов по условиям контракта и может заговорить с Кирионом в любой момент через Голос в голове."
        }
      ],
      misc: ""
    }
  };
}
