import { chromium, launchOpts, E2E_OUT } from "./env.mjs";
const OUT = E2E_OUT;
const r = [];
const ok = (n, c, x = "") => r.push(`${c ? "PASS" : "FAIL"} ${n}${x ? " :: " + x : ""}`);
const sleep = ms => new Promise(res => setTimeout(res, ms));
const browser = await chromium.launch(launchOpts);
const ctx = await browser.newContext({ viewport: { width: 1280, height: 900 }, serviceWorkers: "block" });
await ctx.route(/gstatic\.com|googleapis\.com|google\.com/, x => x.abort());
const page = await ctx.newPage();
const errors = [];
page.on("pageerror", e => errors.push(e.message));
await page.goto("http://localhost:8765/#/c/kirion-thorndike/char");
await page.waitForSelector(".sheet");
await page.locator(".tb-id[data-act=edit-info]").click();
await sleep(300);
await page.selectOption(".modal-back.in select[data-k='accent'], .modal-back.in select[name='accent']", "ice").catch(async () => {
  const sel = page.locator(".modal-back.in select").filter({ has: page.locator("option[value=ice]") });
  await sel.selectOption("ice");
});
await page.locator(".modal-back.in .btn.gold").last().click();
await sleep(400);
const rootGold = await page.evaluate(() => getComputedStyle(document.documentElement).getPropertyValue("--gold-2").trim());
ok("root accent is ice", rootGold === "#86cbea", rootGold);
await page.locator("[data-card='stat:pb']").first().hover().catch(() => {});
await sleep(700);
let card = page.locator(".hover-card, .info-card").first();
if (!(await card.count())) {
  await page.locator("[data-card='stat:pb']").first().click();
  await sleep(400);
  card = page.locator(".modal-back.in .card-art").first();
}
const artColor = await page.evaluate(() => {
  const a = document.querySelector(".card-art");
  return a ? getComputedStyle(a).color : "";
});
ok("card art uses accent", artColor === "rgb(134, 203, 234)", artColor);
await page.screenshot({ path: OUT + "accent-card.png" });
await page.keyboard.press("Escape");
await page.goto("http://localhost:8765/#/");
await sleep(500);
const rootAfter = await page.evaluate(() => document.documentElement.style.getPropertyValue("--gold-2"));
ok("accent reset on home", rootAfter === "", rootAfter);
await page.goto("http://localhost:8765/#/c/kirion-thorndike/combat");
await page.waitForSelector(".sheet");
await page.click("[data-act=dice]").catch(() => {});
await sleep(300);
if (!(await page.locator(".modal-back.in .dice-tray").count())) {
  const btn = page.locator("button", { hasText: "Кубы" }).first();
  await btn.click().catch(() => {});
  await sleep(300);
}
ok("roller open", (await page.locator(".modal-back.in .dice-tray.empty").count()) === 1);
for (let i = 0; i < 4; i++) await page.click(".modal-back.in [data-f='20']");
await page.click(".modal-back.in [data-f='6']");
await page.click(".modal-back.in [data-f='6']");
await page.click(".modal-back.in [data-mod='2']");
ok("expr built", (await page.inputValue(".modal-back.in [data-expr]")) === "4d20+2d6+2", await page.inputValue(".modal-back.in [data-expr]"));
await page.click(".modal-back.in [data-go]");
await sleep(150);
ok("rolling state", (await page.locator(".modal-back.in .dice-tray.rolling").count()) === 1);
await sleep(800);
const dice = await page.locator(".modal-back.in .tray-die").count();
const total = Number(await page.locator(".modal-back.in .tray-total b").innerText());
const faces = await page.$$eval(".modal-back.in .tray-die text", ts => ts.map(t => Number(t.textContent)));
ok("6 dice shown", dice === 6, String(dice));
ok("total matches faces", total === faces.reduce((a, b) => a + b, 0) + 2, `${faces} -> ${total}`);
await page.screenshot({ path: OUT + "roller.png" });
await page.fill(".modal-back.in [data-expr]", "1d20-1d4");
await page.click(".modal-back.in [data-go]");
await sleep(900);
ok("negative die", (await page.locator(".modal-back.in .tray-die.neg").count()) === 1);
await page.setViewportSize({ width: 390, height: 844 });
await page.fill(".modal-back.in [data-expr]", "10d20");
await page.click(".modal-back.in [data-go]");
await sleep(900);
await page.screenshot({ path: OUT + "roller-mobile.png" });
const wide = await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth + 1);
ok("no horizontal scroll", wide);
ok("no errors", errors.length === 0, errors.join(" | "));
console.log(r.join("\n"));
await browser.close();
