import { chromium, launchOpts, E2E_OUT } from "./env.mjs";
const OUT = E2E_OUT;
const r = [];
const ok = (n, c, x = "") => r.push(`${c ? "PASS" : "FAIL"} ${n}${x ? " :: " + x : ""}`);
const sleep = ms => new Promise(res => setTimeout(res, ms));
const browser = await chromium.launch(launchOpts);
const ctx = await browser.newContext({ viewport: { width: 390, height: 844 }, hasTouch: true, isMobile: true, serviceWorkers: "block" });
await ctx.route(/gstatic\.com|googleapis\.com|google\.com/, x => x.abort());
const page = await ctx.newPage();
const errors = [];
page.on("pageerror", e => errors.push(e.message));
await page.goto("http://localhost:8765/#/c/kirion-thorndike/combat");
await page.waitForSelector(".sheet");
await page.screenshot({ path: OUT + "am-bar.png" });
await page.click("[data-act=turn-open][data-k=bonus]");
await sleep(300);
const bonus = await page.$$eval(".modal-back.in .am-row b", bs => bs.map(b => b.textContent.trim()));
ok("bonus lists misty step and flame blade", bonus.includes("Туманный шаг") && bonus.includes("Пылающий клинок"), bonus.join(", "));
await page.screenshot({ path: OUT + "am-bonus.png" });
await page.click(".modal-back.in [data-am-open^='spell:']");
await sleep(300);
ok("opens spell card", (await page.locator(".modal-back.in .bg-card").count()) === 1);
await page.goBack();
await sleep(300);
await page.click("[data-act=turn-open][data-k=action]");
await sleep(300);
const act = await page.$$eval(".modal-back.in .am-row b", bs => bs.map(b => b.textContent.trim()));
ok("action lists attacks, spells, standard", act.includes("Кинжал") && act.includes("Огненный шар") && act.includes("Рывок") && act.includes("Засада"), act.length + "");
await page.screenshot({ path: OUT + "am-action.png" });
await page.click(".modal-back.in [data-am-std=hide]");
await sleep(300);
ok("hide rolls stealth", (await page.locator("#toasts .toast", { hasText: "Скрытность" }).count()) === 1);
ok("action marked", (await page.locator(".turn-slot[data-k=action].used").count()) === 1);
await page.click("[data-act=turn-open][data-k=action]");
await page.click(".modal-back.in [data-am-std=dodge]");
await sleep(300);
ok("dodge adds effect", (await page.locator(".eff-row", { hasText: "Уклонение" }).count()) === 1);
await page.click("[data-act=turn-open][data-k=reaction]");
await sleep(300);
const re = await page.$$eval(".modal-back.in .am-row b", bs => bs.map(b => b.textContent.trim()));
ok("reaction lists counterspell", re.includes("Контрзаклинание") && re.includes("Атака по возможности"), re.join(", "));
await page.keyboard.press("Escape").catch(() => {});
await page.goBack();
await sleep(300);
await page.click("[data-act=turn-open][data-k=move]");
await sleep(300);
const mv = await page.locator(".modal-back.in").innerText();
ok("movement jump from Str 8", mv.includes("8 фт с разбега") && mv.includes("2 фт с разбега"), mv.slice(0, 160).replace(/\n/g, " | "));
await page.screenshot({ path: OUT + "am-move.png" });
ok("no errors", errors.length === 0, errors.join("|"));
await browser.close();
console.log(r.join("\n"));
