import { chromium, launchOpts, E2E_OUT } from "./env.mjs";
const OUT = E2E_OUT;
const r = [];
const ok = (n, c, x = "") => r.push(`${c ? "PASS" : "FAIL"} ${n}${x ? " :: " + x : ""}`);
const sleep = ms => new Promise(res => setTimeout(res, ms));
const browser = await chromium.launch(launchOpts);
for (const mobile of [false, true]) {
  const ctx = await browser.newContext(mobile ? { viewport: { width: 390, height: 844 }, hasTouch: true, isMobile: true, serviceWorkers: "block" } : { viewport: { width: 1280, height: 900 }, serviceWorkers: "block" });
  await ctx.route(/gstatic\.com|googleapis\.com|google\.com/, x => x.abort());
  const page = await ctx.newPage();
  const errors = [];
  page.on("pageerror", e => errors.push(e.message));
  await page.goto("http://localhost:8765/#/c/kirion-thorndike/combat");
  await page.waitForSelector(".sheet");
  const names = async () => page.$$eval(".p-attacks .atk-name b", bs => bs.map(b => b.textContent));
  const n0 = await names();
  ok("no duplicate rows", new Set(n0).size === n0.length, n0.join(","));
  ok("dupe bar shown", (await page.locator(".dupe-bar").count()) === 1);
  await page.locator(".atk-row", { hasText: "Мистический заряд" }).locator(".chip.hit").click();
  await sleep(200);
  ok("EB from spell rolls 2 beams", (await page.locator("#toasts .roll.beams .r-beam").count()) === 2);
  await page.locator("#toasts .roll.beams [data-hit-dmg]").last().click();
  await sleep(200);
  ok("EB damage", (await page.locator("#toasts .roll.dmg").count()) >= 1);
  await page.click(".tab[data-tab=inventory]");
  await page.click("[data-act=gear-table]");
  await page.fill(".modal-back.in [data-q]", "рапира");
  await sleep(100);
  await page.click(".modal-back.in [data-g]");
  await sleep(200);
  await page.keyboard.press("Escape");
  await sleep(300);
  await page.click(".slot:has-text('Рапира')");
  await sleep(300);
  await page.click(".modal-back.in [data-x=equip]");
  await sleep(200);
  ok("rapier attack button", (await page.locator(".modal-back.in [data-x=w-atk]").count()) === 1, await page.locator(".modal-back.in [data-x=w-atk]").innerText().catch(() => ""));
  await page.keyboard.press("Escape");
  await sleep(300);
  await page.click(".tab[data-tab=combat]");
  ok("rapier in combat", (await page.locator(".p-attacks .atk-name b", { hasText: "Рапира" }).count()) === 1);
  await page.click("[data-act=dedupe-attacks]");
  await page.click(".modal-back.in [data-yes]");
  await sleep(300);
  const n1 = await names();
  ok("dupes removed", (await page.locator(".dupe-bar").count()) === 0 && n1.includes("Мистический заряд") && n1.includes("Кинжал"), n1.join(","));
  await page.screenshot({ path: OUT + (mobile ? "m" : "d") + "-atk.png", fullPage: !mobile });
  await page.click("[data-act=dice]");
  await page.click(".modal-back.in [data-f='6']");
  await page.click(".modal-back.in [data-f='6']");
  await page.click(".modal-back.in [data-mod='2']");
  ok("dice expression", (await page.inputValue(".modal-back.in [data-expr]")) === "2d6+2", await page.inputValue(".modal-back.in [data-expr]"));
  await page.click(".modal-back.in [data-go]");
  await sleep(900);
  ok("dice tray", (await page.locator(".modal-back.in .tray-die").count()) === 2);
  await page.screenshot({ path: OUT + (mobile ? "m" : "d") + "-dice.png" });
  ok("no errors", errors.length === 0, errors.join("|"));
  await ctx.close();
}
await browser.close();
console.log(r.join("\n"));
