import { chromium, launchOpts, E2E_OUT } from "./env.mjs";
const r = [];
const ok = (n, c, x = "") => r.push(`${c ? "PASS" : "FAIL"} ${n}${x ? " :: " + x : ""}`);
const sleep = ms => new Promise(res => setTimeout(res, ms));
const browser = await chromium.launch(launchOpts);
const ctx = await browser.newContext({ viewport: { width: 1280, height: 900 }, serviceWorkers: "block" });
await ctx.route(/gstatic\.com|googleapis\.com|google\.com/, x => x.abort());
const page = await ctx.newPage();
const errors = [];
page.on("pageerror", e => errors.push(e.message));
await page.goto("http://localhost:8765/#/c/kirion-thorndike/combat");
await page.waitForSelector(".sheet");
const hp = async () => Number(await page.locator("[data-calc=hp]").first().innerText());
const fails = async () => page.locator(".death-row .ds.bad.on").count();
const dmg = async (n, btn = "Урон") => {
  await page.locator("[data-act=hp][data-mode=dmg]").first().click();
  await page.fill(".modal-back.in .num-big", String(n));
  await page.locator(".modal-back.in .form-actions button", { hasText: btn }).click();
  await sleep(200);
};
const toastHas = async t => (await page.locator("#toasts .toast", { hasText: t }).count()) > 0;
const sceneHas = async t => (await page.locator(".modal-back.in .death-scene", { hasText: t }).count()) > 0;
const closeScene = async () => {
  await page.locator(".modal-back.in .death-scene [data-close]").last().click();
  await sleep(250);
};
await dmg(43);
ok("drop to 0 exactly", (await hp()) === 0 && (await fails()) === 0, `${await hp()} / ${await fails()}`);
await page.locator("[data-act=long-rest]").first().click();
await sleep(200);
ok("long rest refused at 0", await toastHas("не даёт пользы"));
ok("no confirm opened", (await page.locator(".modal-back.in").count()) === 0);
await page.locator("[data-act=hp][data-mode=dmg]").first().click();
await sleep(250);
ok("crit button at 0 hp", (await page.locator(".modal-back.in .form-actions button", { hasText: "Крит. удар" }).count()) === 1);
await page.keyboard.press("Escape");
await sleep(150);
await dmg(3, "Крит. удар");
ok("crit = two failures", (await fails()) === 2, String(await fails()));
await dmg(1);
ok("third failure", (await fails()) === 3);
ok("death scene on third failure", await sceneHas("Персонаж погиб"));
await closeScene();
await page.locator("[data-act=hp][data-mode=heal]").first().click();
await page.fill(".modal-back.in .num-big", "10");
await page.locator(".modal-back.in .form-actions button", { hasText: "Лечение" }).click();
await sleep(200);
ok("heal refused when dead", (await hp()) === 0 && (await toastHas("Погибшего не вылечить")), String(await hp()));
await page.locator("[data-act=hp]").first().click();
await page.fill(".modal-back.in .num-big", "20");
await page.locator(".modal-back.in .form-actions button", { hasText: "Задать" }).click();
await sleep(200);
ok("set revives", (await hp()) === 20 && (await fails()) === 0);
await dmg(20 + 43);
ok("massive damage kills", (await hp()) === 0 && (await fails()) === 3 && (await sceneHas("Мгновенная смерть")));
await closeScene();
await page.locator("[data-act=hp]").first().click();
await page.fill(".modal-back.in .num-big", "43");
await page.locator(".modal-back.in .form-actions button", { hasText: "Задать" }).click();
await sleep(200);
await page.evaluate(() => document.querySelectorAll("#toasts .toast").forEach(t => t.remove()));
await page.click("[data-act=add-effect]");
await page.click(".modal-back.in [data-pre=huntersMark]");
await sleep(200);
await page.locator(".atk-row", { hasText: "Кинжал" }).locator(".chip").filter({ hasText: /d4/ }).first().click().catch(() => {});
await sleep(300);
const t1 = await page.locator("#toasts .toast").last().innerText().catch(() => "");
ok("weapon damage button adds hunters mark", /Метка охотника/.test(t1), t1.replace(/\s+/g, " ").slice(0, 160));
await page.evaluate(() => document.querySelectorAll("#toasts .toast").forEach(t => t.remove()));
await page.locator(".atk-row", { hasText: "Мистический заряд" }).locator(".chip").filter({ hasText: /d10/ }).first().click().catch(() => {});
await sleep(300);
const t2 = await page.locator("#toasts .toast").last().innerText().catch(() => "");
ok("spell damage has no hunters mark", t2 && !/Метка охотника/.test(t2), t2.replace(/\s+/g, " ").slice(0, 160));
ok("no errors", errors.length === 0, errors.join(" | "));
console.log(r.join("\n"));
await browser.close();
