import { chromium, launchOpts, E2E_OUT } from "./env.mjs";
const OUT = E2E_OUT;
const r = [];
const ok = (n, c, x = "") => r.push(`${c ? "PASS" : "FAIL"} ${n}${x ? " :: " + x : ""}`);
const sleep = ms => new Promise(res => setTimeout(res, ms));
const browser = await chromium.launch(launchOpts);
for (const mobile of [false, true]) {
  const ctx = await browser.newContext({ viewport: mobile ? { width: 390, height: 844 } : { width: 1280, height: 900 }, hasTouch: mobile, isMobile: mobile, serviceWorkers: "block" });
  await ctx.route(/gstatic\.com|googleapis\.com|google\.com/, x => x.abort());
  const page = await ctx.newPage();
  const errors = [];
  page.on("pageerror", e => errors.push(e.message));
  const M = ".modal-back.in";
  const tag = mobile ? "m" : "d";
  await page.goto("http://localhost:8765/#/c/kirion-thorndike/notes");
  await page.waitForSelector(".sheet");
  await page.click("[data-journal]");
  await page.keyboard.type("Рэй и Халвар Торндайк спорили о Мефистофеле");
  await page.keyboard.press("Enter");
  await sleep(300);
  await page.click("[data-act=board]");
  await sleep(700);
  const nodes = await page.locator(`${M} .bd-node`).count();
  const edges = await page.locator(`${M} .bd-edge`).count();
  ok(tag + " nodes", nodes >= 5, String(nodes));
  ok(tag + " edges", edges >= 1, String(edges));
  await page.screenshot({ path: OUT + `board-${tag}.png` });
  const node = page.locator(`${M} .bd-node`, { hasText: "Рэй" }).first();
  await node.click();
  await sleep(300);
  ok(tag + " card shows", (await page.locator(`${M} [data-bd-card]:not([hidden])`).count()) === 1);
  ok(tag + " neighbours dimmed", (await page.locator(`${M} .bd-node.dim`).count()) >= 1);
  if (!mobile) {
    const box = await page.locator(`${M} .bd-node`, { hasText: "Мефистофель" }).first().boundingBox();
    await page.mouse.move(box.x + box.width / 2, box.y + 10);
    await page.mouse.down();
    await page.mouse.move(box.x + box.width / 2 + 120, box.y + 70, { steps: 6 });
    await page.mouse.up();
    await sleep(200);
    const saved = await page.evaluate(() => Object.keys(JSON.parse(localStorage.getItem("dnd.board.kirion-thorndike") || "{}")).length);
    ok("d drag saved", saved === 1, String(saved));
    await page.mouse.move(640, 400);
    await page.mouse.wheel(0, -300);
    await sleep(100);
    const tr = await page.locator(`${M} [data-bd-view]`).getAttribute("transform");
    ok("d wheel zoom", /scale\((?!1\))/.test(tr), tr);
  }
  await page.click(`${M} [data-bd-open]`);
  await sleep(600);
  ok(tag + " opens note", (await page.locator(".subtab.on").innerText()).includes("Люди"));
  await page.click("[data-act=board]");
  await sleep(500);
  await page.click(`${M} [data-bd-sec=sessions]`);
  await sleep(300);
  ok(tag + " sessions toggle", (await page.locator(`${M} .bd-node`, { hasText: "Сессия" }).count()) >= 1);
  await page.fill(`${M} [data-bd-q]`, "мефист");
  await sleep(200);
  ok(tag + " search highlight", (await page.locator(`${M} .bd-node.hit`).count()) >= 1 && (await page.locator(`${M} .bd-node.dim`).count()) >= 1);
  const wide = await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth + 1);
  ok(tag + " no horizontal scroll", wide);
  ok(tag + " no errors", errors.length === 0, errors.join(" | "));
  await ctx.close();
}
console.log(r.join("\n"));
await browser.close();
