import { fileURLToPath } from "node:url";
import { chromium, launchOpts, E2E_OUT } from "./env.mjs";
const r = [];
const ok = (n, c, x = "") => r.push(`${c ? "PASS" : "FAIL"} ${n}${x ? " :: " + x : ""}`);
const sleep = ms => new Promise(res => setTimeout(res, ms));
const BOARD = fileURLToPath(new URL("../../assets/templates/wizard-board.webp", import.meta.url));
const browser = await chromium.launch(launchOpts);
const ctx = await browser.newContext({ viewport: { width: 390, height: 844 }, hasTouch: true, isMobile: true, serviceWorkers: "block" });
await ctx.route(/gstatic\.com|googleapis\.com|google\.com/, x => x.abort());
const page = await ctx.newPage();
const errors = [];
page.on("pageerror", e => errors.push(e.message));
await page.goto("http://localhost:8765/#/");
await page.waitForSelector(".tpl-hero.own");
ok("no board chip before upload", (await page.locator(".own-board").count()) === 0);
await page.goto("http://localhost:8765/#/c/kirion-thorndike/combat");
await page.waitForSelector(".sheet");
await page.click(".tb-portrait[data-act=profile]");
await page.click(".modal.profile [data-pf-go=portrait]");
await page.waitForSelector(".pb-board [data-board-up]");
const [chooser] = await Promise.all([page.waitForEvent("filechooser"), page.click(".pb-board [data-board-up]")]);
await chooser.setFiles(BOARD);
await page.waitForSelector(".modal-back.in .portrait-big", { state: "detached", timeout: 10000 }).catch(() => {});
await sleep(400);
const stored = await page.evaluate(() => (localStorage.getItem("dnd.board.kirion-thorndike") || "").length);
ok("board is stored compressed", stored > 10000 && stored <= 950000, String(stored));
await page.goto("http://localhost:8765/#/");
await page.waitForSelector(".tpl-hero.own");
ok("home card offers the board", (await page.locator(".own-board").count()) === 1);
await page.click(".own-board");
await page.waitForSelector(".modal.tpl-board img");
await sleep(300);
ok("board opens from home", await page.locator(".modal.tpl-board img").evaluate(x => x.complete && x.naturalWidth > 800));
await page.screenshot({ path: E2E_OUT + "cboard-open.png" });
const box = await page.locator(".modal.tpl-board .bz").boundingBox();
ok("board fills the phone screen", box && box.width >= 380 && box.height >= 700, JSON.stringify(box));
await page.dblclick(".modal.tpl-board .bz", { position: { x: box.width / 2, y: box.height / 3 } });
await sleep(200);
ok("double tap zooms in", /scale\(2\.5\)/.test(await page.locator(".modal.tpl-board img").getAttribute("style")));
await page.screenshot({ path: E2E_OUT + "cboard-zoom.png" });
await page.dblclick(".modal.tpl-board .bz");
await sleep(200);
ok("double tap again zooms out", /scale\(1\)/.test(await page.locator(".modal.tpl-board img").getAttribute("style")));
await page.keyboard.press("Escape");
await page.goto("http://localhost:8765/#/c/kirion-thorndike/combat");
await page.waitForSelector(".sheet");
await page.click(".tb-portrait[data-act=profile]");
await page.click(".modal.profile [data-pf-go=portrait]");
await page.waitForSelector(".pb-board [data-board-open]");
ok("sheet offers open and replace", (await page.locator(".pb-board [data-board-up]").count()) === 1);
await page.click(".pb-board [data-board-rm]");
await page.waitForSelector(".modal-back.in .btn.danger");
await page.locator(".modal-back.in .btn.danger").last().click();
await sleep(400);
ok("board removed", (await page.evaluate(() => localStorage.getItem("dnd.board.kirion-thorndike"))) === null);
ok("no errors", errors.length === 0, errors.join("|"));
await browser.close();
console.log(r.join("\n"));
