import { chromium, launchOpts, E2E_OUT } from "./env.mjs";
const OUT = E2E_OUT;
const r = [];
const ok = (n, c, x = "") => r.push(`${c ? "PASS" : "FAIL"} ${n}${x ? " :: " + x : ""}`);
const sleep = ms => new Promise(res => setTimeout(res, ms));
const browser = await chromium.launch(launchOpts);
const ctx = await browser.newContext({ viewport: { width: 390, height: 844 }, hasTouch: true, isMobile: true, serviceWorkers: "block" });
await ctx.route(/gstatic\.com|googleapis\.com|google\.com/, x => x.abort());
const page = await ctx.newPage();
const errors = [];
page.on("pageerror", e => errors.push(e.message));
await page.goto("http://localhost:8765/#/c/kirion-thorndike/combat");
await page.waitForSelector(".sheet");
const hp = async () => Number(await page.locator("[data-calc=hp]").first().innerText());
await page.click("[data-act=hp-quick][data-n='-5']");
await sleep(150);
ok("undo bar shows", await page.locator("#undo-bar.in").count() === 1);
await page.click("#undo-bar [data-undo]");
await sleep(200);
ok("undo restores hp", (await hp()) === 43, String(await hp()));
await page.locator(".atk-row", { hasText: "Лёгкий арбалет" }).locator(".chip.hit").click();
await sleep(300);
const sub = await page.locator(".atk-row", { hasText: "Лёгкий арбалет" }).locator("small").innerText();
ok("crossbow uses bolts", /болты: 19/i.test(sub), sub);
ok("collect bar", (await page.locator(".ammo-bar").count()) === 1);
await page.click("[data-act=cover][data-k=cover2]");
await sleep(150);
ok("half cover +2 AC", (await page.locator(".combat-strip [data-calc=ac]").innerText()) === "16");
await page.click("[data-act=cover][data-k=cover5]");
await sleep(150);
ok("three-quarters replaces", (await page.locator(".combat-strip [data-calc=ac]").innerText()) === "19");
await page.click(".tab[data-tab=inventory]");
await page.click("[data-act=coin-pay]");
await page.fill(".modal-back.in .num-big", "3");
await page.selectOption(".modal-back.in [data-sel]", "sp");
await page.click(".modal-back.in [data-i='0']");
await sleep(200);
ok("paid 3 sp", (await page.inputValue("input[data-path='coins.sp']")) === "5");
await page.click("[data-act=coin-pay]");
await page.fill(".modal-back.in .num-big", "500");
await page.click(".modal-back.in [data-i='0']");
await sleep(200);
ok("not enough money", (await page.locator("#toasts .toast", { hasText: "Не хватает денег" }).count()) === 1);
await page.click(".tab[data-tab=char]");
await sleep(100);
ok("xp row", (await page.locator(".xp-row .xp-t").innerText()).includes("14000"));
await page.click("[data-act=add-xp]");
await page.fill(".modal-back.in .num-big", "8000");
await page.click(".modal-back.in [data-i='0']");
await sleep(200);
ok("level up hint", (await page.locator(".xp-row.ready").count()) === 1);
await page.click("[data-act=menu]");
await page.click("[data-m=search-all]");
await page.fill(".modal-back.in [data-q]", "шар");
await sleep(150);
const found = await page.$$eval(".modal-back.in .am-row b", bs => bs.map(b => b.textContent));
ok("search finds fireball", found.includes("Огненный шар"), found.join(","));
await page.click(".modal-back.in .am-row:has-text('Огненный шар')");
await sleep(300);
ok("opens spell card", (await page.locator(".modal-back.in .bg-card h3").innerText()) === "Огненный шар");
await page.goBack();
await sleep(300);
await page.click("[data-act=menu]");
await page.click("[data-m=long-rest]");
await page.click(".modal-back.in [data-yes]");
await sleep(400);
const rest = await page.locator("#toasts .toast", { hasText: "Длинный отдых" }).innerText();
ok("rest summary", rest.includes("Закончилось") || rest.includes("Восстановлено") || rest.includes("Кости"), rest.replace(/\n/g, " | "));
await page.click("[data-act=edit-info]");
await page.selectOption(".modal-back.in select[data-k=accent]", "ice");
await page.click(".modal-back.in button[type=submit]");
await sleep(300);
const accent = await page.$eval(".sheet", el => getComputedStyle(el).getPropertyValue("--gold").trim());
ok("accent applied", accent === "#5aa5c9", accent);
await page.screenshot({ path: OUT + "conv-ice.png" });
await page.click("[data-act=menu]");
await page.click("[data-m=switch-char]");
await sleep(400);
ok("switch dialog", (await page.locator(".modal-back.in .switch-list").count()) === 1);
await page.screenshot({ path: OUT + "conv-switch.png" });
ok("no errors", errors.length === 0, errors.join("|"));
await browser.close();
console.log(r.join("\n"));
