import { chromium, launchOpts, E2E_OUT } from "./env.mjs";
const OUT = E2E_OUT;
const r = [];
const ok = (n, c, x = "") => r.push(`${c ? "PASS" : "FAIL"} ${n}${x ? " :: " + x : ""}`);
const sleep = ms => new Promise(res => setTimeout(res, ms));
const browser = await chromium.launch(launchOpts);
const ctx = await browser.newContext({ viewport: { width: 390, height: 844 }, hasTouch: true, isMobile: true, serviceWorkers: "block" });
await ctx.route(/gstatic\.com|googleapis\.com|google\.com/, x => x.abort());
const page = await ctx.newPage();
const errors = [];
page.on("pageerror", e => errors.push(e.message));
const M = ".modal-back.in";
await page.goto("http://localhost:8765/#/");
await page.waitForSelector("[data-new]");
await page.click("[data-new]");
await sleep(1200);
ok("creator opens", (await page.locator(`${M} .cr-steps .cr-step`).count()) >= 7);
await page.click(`${M} [data-race=tiefling]`);
await sleep(200);
ok("race detail", (await page.locator(`${M} .cr-detail`).innerText()).includes("Тёмное зрение"));
await page.screenshot({ path: OUT + "cr-race.png" });
await page.click(`${M} [data-next]`);
await sleep(200);
await page.click(`${M} [data-cls=warlock]`);
await sleep(200);
ok("subclass auto Исчадие", (await page.locator(`${M} [data-sub].on`).innerText()).includes("Исчадие"));
await page.click(`${M} [data-next]`);
await sleep(200);
await page.click(`${M} [data-bg=custom]`);
await sleep(200);
await page.fill(`${M} [data-bg-name]`, "Механик");
await page.click(`${M} [data-bg-skill=history]`);
await page.click(`${M} [data-bg-skill=investigation]`);
await sleep(100);
await page.click(`${M} [data-next]`);
await sleep(200);
await page.click(`${M} [data-suggest]`);
await sleep(200);
const totals = await page.locator(`${M} .cr-total`).allInnerTexts();
ok("abilities filled", totals.every(t => /\d/.test(t)), totals.join(","));
ok("cha 17 with race", totals[5] === "17", totals[5]);
await page.click(`${M} [data-method=point]`);
await sleep(150);
ok("point buy budget", (await page.locator(`${M} .cr-body`).innerText()).includes("из 27"));
await page.click(`${M} [data-method=standard]`);
await sleep(150);
await page.click(`${M} [data-next]`);
await sleep(200);
await page.click(`${M} [data-skill=arcana]`);
await page.click(`${M} [data-skill=deception]`);
await sleep(100);
ok("skills step done", (await page.locator(`${M} .cr-step.on`).innerText()).includes("Навыки"));
await page.click(`${M} [data-next]`);
await sleep(300);
ok("spells step", (await page.locator(`${M} [data-picker=cantrips]`).count()) === 1 && (await page.locator(`${M} [data-picker=spells]`).count()) === 1);
await page.fill(`${M} [data-spq=cantrips]`, "мистич");
await sleep(150);
await page.click(`${M} [data-picker=cantrips] .lu-pick >> nth=0`);
await page.fill(`${M} [data-spq=cantrips]`, "");
await sleep(150);
await page.click(`${M} [data-picker=cantrips] .lu-pick:not([aria-pressed=true]) >> nth=0`);
await sleep(150);
await page.click(`${M} [data-picker=spells] .lu-pick >> nth=0`);
await sleep(150);
await page.click(`${M} [data-picker=spells] .lu-pick:not([aria-pressed=true]) >> nth=0`);
await sleep(150);
const counters = await page.locator(`${M} .lu-picker-h b`).allInnerTexts();
ok("spells picked", counters.join() === "2 из 2,2 из 2", counters.join());
await page.click(`${M} [data-next]`);
await sleep(300);
const feats = await page.locator(`${M} .cr-body`).innerText();
ok("features preview", feats.includes("Благословение Тёмного") && feats.includes("Адское сопротивление"), feats.slice(0, 200));
await page.click(`${M} [data-next]`);
await sleep(300);
await page.fill(`${M} [data-name]`, "Тестовый Колдун");
await page.locator(`${M} [data-name]`).blur();
await sleep(200);
const sum = await page.locator(`${M} .cr-sum`).innerText();
ok("summary hp", sum.includes("10"), sum.replace(/\n/g, " "));
ok("no missing", (await page.locator(`${M} .cr-warn`).count()) === 0, await page.locator(`${M} .cr-warn`).innerText().catch(() => ""));
await page.screenshot({ path: OUT + "cr-final.png" });
await page.click(`${M} [data-create]`);
await page.waitForSelector(".sheet", { timeout: 8000 });
await sleep(500);
ok("sheet name", (await page.locator(".tb-name").innerText()).includes("Тестовый Колдун"));
ok("sheet hp", (await page.locator("[data-calc=hp]").first().innerText()) === "10");
await page.click(".tab[data-tab=features]");
await sleep(300);
const ft = await page.locator(".sheet").innerText();
ok("features on sheet", ft.includes("Магия договора") && ft.includes("Тёмное зрение"));
await page.click(".tab[data-tab=spells]");
await sleep(300);
const sp = await page.locator(".sheet").innerText();
ok("spells on sheet", sp.includes("Мистический заряд") && sp.includes("Чудотворство"));
await page.click(".tab[data-tab=inventory]");
await sleep(300);
ok("gear on sheet", (await page.locator(".sheet").innerText()).includes("Кожаный доспех"));
const wide = await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth + 1);
ok("no horizontal scroll", wide);
ok("no errors", errors.length === 0, errors.join(" | "));
console.log(r.join("\n"));
await browser.close();
