import { chromium, launchOpts } from "./env.mjs";
const r = [];
const ok = (n, c, x = "") => r.push(`${c ? "PASS" : "FAIL"} ${n}${x ? " :: " + x : ""}`);
const sleep = ms => new Promise(res => setTimeout(res, ms));
const browser = await chromium.launch({ ...launchOpts, args: ["--use-gl=angle", "--enable-unsafe-swiftshader"] });
const ctx = await browser.newContext({ viewport: { width: 390, height: 844 }, hasTouch: true, isMobile: true, serviceWorkers: "block" });
await ctx.route(/gstatic\.com|googleapis\.com|google\.com/, x => x.abort());
await ctx.addInitScript(() => localStorage.setItem("dnd.dice3d", "1"));
const page = await ctx.newPage();
const errors = [];
page.on("pageerror", e => errors.push(e.message));
await page.goto("http://localhost:8765/#/c/kirion-thorndike/character");
await page.waitForSelector(".sheet");
await page.waitForFunction(() => document.querySelector("#dice3d canvas"), null, { timeout: 20000 }).catch(() => {});
ok("3D dice load after the sheet opens", (await page.locator("#dice3d canvas").count()) === 1);
await sleep(4000);
await page.click("[data-roll='check:dex']");
await sleep(400);
ok("dice overlay shows while rolling", (await page.locator("#dice3d.on").count()) === 1);
ok("result waits for the dice", (await page.locator("#toasts .roll").count()) === 0);
await page.waitForSelector("#toasts .roll", { timeout: 8000 });
const one = await page.locator("#toasts .roll .r-calc").first().innerText();
ok("result comes from the die", /^\d{1,2} \+ 2/.test(one.trim()), one);
await sleep(2200);
ok("overlay hides after landing", (await page.locator("#dice3d.on").count()) === 0);
await page.click("[data-act=roll-mode]");
await sleep(300);
await page.click("[data-roll='check:wis']");
await page.waitForSelector("#toasts .roll .r-both", { timeout: 8000 });
const both = await page.locator("#toasts .roll .r-both").first().innerText();
const m = both.match(/(\d+) \/ (\d+)/);
const pick = Number((await page.locator("#toasts .roll .r-calc").first().innerText()).trim().split(" ")[0]);
ok("advantage throws two dice and keeps the higher", m && pick === Math.max(Number(m[1]), Number(m[2])), both + " -> " + pick);
ok("no errors", errors.length === 0, errors.join("|"));
await browser.close();
console.log(r.join("\n"));
