import { chromium, launchOpts } from "./env.mjs";
const r = [];
const ok = (n, c, x = "") => r.push(`${c ? "PASS" : "FAIL"} ${n}${x ? " :: " + x : ""}`);
const sleep = ms => new Promise(res => setTimeout(res, ms));
const browser = await chromium.launch({ ...launchOpts, args: ["--use-gl=angle", "--enable-unsafe-swiftshader"] });
const ctx = await browser.newContext({ viewport: { width: 390, height: 844 }, hasTouch: true, isMobile: true, serviceWorkers: "block" });
await ctx.route(/gstatic\.com|googleapis\.com|google\.com/, x => x.abort());
await ctx.addInitScript(() => localStorage.setItem("dnd.dice3d", "1"));
const page = await ctx.newPage();
const errors = [];
page.on("pageerror", e => errors.push(e.message));
await page.goto("http://localhost:8765/#/c/kirion-thorndike/character");
await page.waitForSelector(".sheet");
await page.waitForFunction(() => document.querySelector("#dice3d canvas"), null, { timeout: 20000 }).catch(() => {});
ok("3D dice load after the sheet opens", (await page.locator("#dice3d canvas").count()) === 1);
await sleep(4000);
await page.click("[data-roll='check:dex']");
await sleep(400);
ok("dice overlay shows while rolling", (await page.locator("#dice3d.on").count()) === 1);
ok("result waits for the dice", (await page.locator("#toasts .roll").count()) === 0);
await page.evaluate(() => ["check:str", "check:con", "check:int"].forEach(k => document.querySelector(`[data-roll='${k}']`).click()));
await sleep(200);
ok("taps while dice roll are ignored", (await page.locator("#toasts .roll").count()) === 0);
await page.waitForSelector("#toasts .roll", { timeout: 8000 });
const one = await page.locator("#toasts .roll .r-calc").first().innerText();
ok("result comes from the die", /^\d{1,2} \+ 2/.test(one.trim()), one);
ok("only one roll went through", (await page.locator("#toasts .roll").count()) === 1);
const shown = (await page.locator("#dice3d .d3-total").innerText()).trim();
const total = (await page.locator("#toasts .roll .r-total").first().innerText()).trim();
ok("total shows over the dice", shown === total, shown + " vs " + total);
await sleep(3000);
ok("overlay hides after landing", (await page.locator("#dice3d.on").count()) === 0);
await page.click("[data-act=roll-mode]");
await sleep(300);
await page.click("[data-roll='check:wis']");
await page.waitForSelector("#toasts .roll .r-both", { timeout: 8000 });
const both = await page.locator("#toasts .roll .r-both").first().innerText();
const m = both.match(/(\d+) \/ (\d+)/);
const pick = Number((await page.locator("#toasts .roll .r-calc").first().innerText()).trim().split(" ")[0]);
ok("advantage throws two dice and keeps the higher", m && pick === Math.max(Number(m[1]), Number(m[2])), both + " -> " + pick);
await sleep(3000);
await page.goto("http://localhost:8765/#/c/kirion-thorndike/combat");
await page.waitForSelector(".sheet");
await page.waitForFunction(() => document.querySelector("#dice3d canvas"), null, { timeout: 20000 }).catch(() => {});
await sleep(4000);
await page.locator("[data-roll^='dmg:'], [data-roll^='idmg:']").first().click();
await sleep(400);
ok("damage throws 3D dice", (await page.locator("#dice3d.on").count()) === 1 && (await page.locator("#toasts .roll.dmg").count()) === 0);
await page.waitForSelector("#toasts .roll.dmg", { timeout: 8000 });
const rolls = await page.locator("#toasts .roll.dmg .r-rolls").first().innerText();
ok("damage dice values listed", /\[\d+/.test(rolls), rolls);
await sleep(3200);
await page.locator("[data-act=dice]").first().click();
await page.waitForSelector("[data-expr]");
await page.fill("[data-expr]", "2d6+1d4");
await page.click("[data-go]");
await sleep(400);
ok("free roller throws 3D dice above the window", (await page.locator("#dice3d.on").count()) === 1);
await page.waitForSelector("[data-tray]:not(.empty)", { timeout: 8000 });
await sleep(300);
const tray = await page.locator("[data-tray]").innerText();
ok("free roller shows the landed total", (await page.locator("#dice3d .d3-total").innerText()).trim() !== "" && /\d/.test(tray), tray.replace(/\s+/g, " "));
ok("no errors", errors.length === 0, errors.join("|"));
await browser.close();
console.log(r.join("\n"));
