import { chromium, launchOpts, E2E_OUT } from "./env.mjs";
const OUT = E2E_OUT;
const r = [];
const ok = (n, c, x = "") => r.push(`${c ? "PASS" : "FAIL"} ${n}${x ? " :: " + x : ""}`);
const sleep = ms => new Promise(res => setTimeout(res, ms));
const browser = await chromium.launch(launchOpts);
const ctx = await browser.newContext({ viewport: { width: 390, height: 844 }, hasTouch: true, isMobile: true, serviceWorkers: "block" });
await ctx.route(/gstatic\.com|googleapis\.com|google\.com/, x => x.abort());
const page = await ctx.newPage();
const errors = [];
page.on("pageerror", e => errors.push(e.message));
await page.goto("http://localhost:8765/#/c/kirion-thorndike/combat");
await page.waitForSelector(".sheet");
await page.click("[data-act=add-effect]");
await page.click("[data-pre=bless]");
await sleep(200);
await page.click("[data-act=add-effect]");
await page.click("[data-pre=shieldOfFaith]");
await sleep(200);
await page.click("[data-act=add-effect]");
await page.click("[data-pre=hex]");
await sleep(200);
ok("three effects listed", (await page.locator(".eff-row").count()) === 3);
ok("AC raised", (await page.locator(".combat-strip [data-calc=ac]").innerText()) === "16");
await page.locator(".atk-row", { hasText: "Мистический заряд" }).locator(".chip.hit").click();
await sleep(200);
const t = await page.locator("#toasts .roll.beams").innerText();
ok("bless in beam toast", t.includes("Благословение"), t.replace(/\n/g, " | "));
await page.locator("#toasts .roll.beams [data-hit-dmg]").last().click();
await sleep(200);
const dmg = await page.locator("#toasts .roll.dmg").last().innerText();
ok("hex damage per beam", (dmg.match(/Сглаз/g) || []).length === 2, dmg.replace(/\n/g, " | "));
await page.click("[data-act=next-round]");
await sleep(150);
ok("round ticks", (await page.locator(".eff-row", { hasText: "Благословение" }).locator(".eff-left").innerText()).startsWith("9"));
await page.screenshot({ path: OUT + "eff-m.png", fullPage: true });
await page.click("[data-act=end-combat]");
await sleep(150);
const left = await page.$$eval(".eff-row .eff-name b", bs => bs.map(b => b.textContent));
ok("end combat keeps long effects", left.join(",") === "Щит веры,Сглаз", left.join(","));
await page.click("[data-act=add-effect]");
await page.click("[data-pre='']");
await page.fill(".modal-back.in input[data-k=name]", "Зелье ловкости");
await page.fill(".modal-back.in input[data-k=check]", "2");
await page.click(".modal-back.in [data-flags][data-k=adv] label:has(input[value='save:dex'])");
await page.click(".modal-back.in button[type=submit]");
await sleep(200);
ok("custom effect", (await page.locator(".eff-row", { hasText: "Зелье ловкости" }).count()) === 1);
await page.click(".tab[data-tab=char]");
ok("effect chips on character tab", (await page.locator(".cond-active .chip.eff").count()) === 3);
await page.click("[data-act=menu]");
await page.click("[data-m=long-rest]");
await page.click(".modal-back.in [data-yes]");
await sleep(300);
ok("long rest shows campfire scene", (await page.locator(".modal-back.in .scene-card.camp.long").count()) === 1);
await page.click(".modal-back.in .scene-card [data-close]");
await sleep(250);
ok("long rest clears effects", (await page.locator(".cond-active .chip.eff").count()) === 0);
ok("no errors", errors.length === 0, errors.join("|"));
await browser.close();
console.log(r.join("\n"));
