import { chromium, launchOpts, E2E_OUT } from "./env.mjs";
const OUT = E2E_OUT;
const r = [];
const ok = (n, c, x = "") => r.push(`${c ? "PASS" : "FAIL"} ${n}${x ? " :: " + x : ""}`);
const sleep = ms => new Promise(res => setTimeout(res, ms));
const browser = await chromium.launch(launchOpts);
const ctx = await browser.newContext({ viewport: { width: 390, height: 844 }, hasTouch: true, isMobile: true, serviceWorkers: "block" });
await ctx.route(/gstatic\.com|googleapis\.com|google\.com/, x => x.abort());
const page = await ctx.newPage();
const errors = [];
page.on("pageerror", e => errors.push(e.message));
const M = ".modal-back.in";
await page.goto("http://localhost:8765/#/c/kirion-thorndike/features");
await page.waitForSelector(".sheet");
await page.click("[data-act=feature-library]");
await sleep(800);
ok("opens on features tab", (await page.locator(`${M} [data-lib-tab=features].on`).count()) === 1);
ok("title", (await page.locator(`${M} .modal-head h2`).innerText()).includes("умения"));
const names = await page.locator(`${M} .lib-names b`).allInnerTexts();
ok("warlock features up to level 5", names.includes("Благословение Тёмного") && !names.includes("Удача Тёмного") && names.includes("Договор цепи"), names.slice(0, 12).join(","));
ok("owned marked", (await page.locator(`${M} .lib-row`, { hasText: "Благословение Тёмного" }).locator(".badge").count()) === 1);
await page.uncheck(`${M} [data-mine]`);
await sleep(200);
ok("all levels when unchecked", (await page.locator(`${M} .lib-names b`).allInnerTexts()).includes("Удача Тёмного"));
await page.click(`${M} [data-fg=race]`);
await sleep(200);
const race = await page.locator(`${M} .lib-names b`).allInnerTexts();
ok("race preselected tiefling", race.length >= 4 && (await page.locator(`${M} [data-race]`).inputValue()) === "Тифлинг", race.join(","));
await page.fill(`${M} [data-q]`, "ярость");
await sleep(200);
await page.locator(`${M} .lib-row`, { hasText: "Ярость" }).first().locator(".lib-head").click();
await sleep(200);
ok("card shows meta", (await page.locator(`${M} .lib-meta`).innerText()).length > 3);
await page.screenshot({ path: OUT + "flib-card.png" });
await page.click(`${M} [data-add]`);
await sleep(300);
ok("rage added", (await page.locator(`${M} .lib-row`, { hasText: "Ярость" }).first().locator(".badge").count()) === 1);
await page.click(`${M} [data-lib-tab=gear]`);
await sleep(300);
ok("gear tab", (await page.locator(`${M} .gear-row`).count()) > 20);
await page.fill(`${M} [data-q]`, "кинжал");
await sleep(150);
await page.click(`${M} .gear-row >> nth=0`);
await sleep(300);
await page.click(`${M} [data-lib-tab=spells]`);
await sleep(800);
ok("spells tab", (await page.locator(`${M} .lib-row`).count()) > 10);
await page.keyboard.press("Escape");
await sleep(300);
const feat = await page.locator(".sheet").innerText();
ok("rage in features", feat.includes("Ярость"));
await page.click(".tab[data-tab=inventory]");
await sleep(300);
ok("dagger added", (await page.locator(".sheet").innerText()).match(/Кинжал/g).length >= 2);
await page.click("[data-act=gear-table]");
await sleep(500);
ok("inventory opens gear tab", (await page.locator(`${M} [data-lib-tab=gear].on`).count()) === 1);
await page.keyboard.press("Escape");
await sleep(300);
await page.click(".tab[data-tab=char]");
await page.locator(".tb-id[data-act=edit-info]").click();
await sleep(400);
await page.fill(`${M} [data-k="info.cls"]`, "Чародей");
await page.fill(`${M} [data-k="info.subclass"]`, "Наследие драконьей крови");
await page.fill(`${M} [data-k="info.level"]`, "2");
await page.locator(`${M} button[type=submit]`).click();
await sleep(400);
await page.click("[data-act=menu]");
await page.click("[data-m=level-up]");
await sleep(1200);
const lu = await page.locator(M).innerText();
ok("metamagic feature", lu.includes("Метамагия"), lu.slice(0, 200).replace(/\n/g, " | "));
ok("metamagic choose 2", lu.includes("Метамагия: выбери 2") && (await page.locator(`${M} input[data-choice]`).count()) === 8);
const boxes = page.locator(`${M} input[data-choice]`);
await boxes.nth(0).check();
await boxes.nth(5).check();
await boxes.nth(2).click();
await sleep(200);
ok("third pick blocked", !(await boxes.nth(2).isChecked()));
await page.screenshot({ path: OUT + "flib-lvl.png" });
await page.click(`${M} [data-go]`);
await sleep(600);
await page.click(".modal-back.in .levelup-card .form-actions [data-close]");
await sleep(250);
await page.click(".tab[data-tab=features]");
await sleep(300);
const ft = await page.locator(".sheet").innerText();
ok("options added", ft.includes("Аккуратное заклинание") && ft.includes("Ускоренное заклинание") && !ft.includes("Усиленное заклинание"));
ok("no errors", errors.length === 0, errors.join(" | "));
console.log(r.join("\n"));
await browser.close();
