import { chromium, launchOpts, E2E_OUT } from "./env.mjs";
const OUT = E2E_OUT;
const r = [];
const ok = (n, c, x = "") => r.push(`${c ? "PASS" : "FAIL"} ${n}${x ? " :: " + x : ""}`);
const sleep = ms => new Promise(res => setTimeout(res, ms));
const browser = await chromium.launch(launchOpts);
const ctx = await browser.newContext({ viewport: { width: 1280, height: 900 }, serviceWorkers: "block" });
await ctx.route(/gstatic\.com|googleapis\.com|google\.com/, x => x.abort());
const page = await ctx.newPage();
const errors = [];
page.on("pageerror", e => errors.push(e.message));
await page.addInitScript(() => { window.print = () => { window.__printed = (window.__printed || 0) + 1; }; });
await page.goto("http://localhost:8765/#/c/kirion-thorndike/combat");
await page.waitForSelector(".sheet");
ok("turn bar", (await page.locator(".turn-slot").count()) === 4);
await page.locator(".atk-row", { hasText: "Мистический заряд" }).locator(".chip.hit").click();
await sleep(120);
ok("rolling animation", await page.locator("#toasts .toast.rolling").count() === 1);
await sleep(700);
ok("landed", await page.locator("#toasts .toast.rolling").count() === 0);
ok("action marked", (await page.locator(".turn-slot[data-k=action].used").count()) === 1);
await page.click(".tab[data-tab=spells]");
await page.click(".tile:has-text('Туманный шаг')");
await page.click(".modal-back.in [data-x=cast]");
await page.keyboard.press("Escape");
await page.click(".tab[data-tab=combat]");
ok("bonus marked by misty step", (await page.locator(".turn-slot[data-k=bonus].used").count()) === 1);
await page.click("[data-act=new-turn]");
ok("new turn resets", (await page.locator(".turn-slot.used").count()) === 0);
await page.reload();
await page.waitForSelector(".sheet");
await page.click("[data-act=turn-open][data-k=reaction]");
await page.click(".modal-back.in [data-am-toggle]");
await sleep(250);
await page.reload();
await page.waitForSelector(".sheet");
ok("turn remembered on device", (await page.locator(".turn-slot[data-k=reaction].used").count()) === 1);
await page.evaluate(() => { Math.random = () => 0.999; });
await page.locator(".atk-row", { hasText: "Кинжал" }).locator(".chip.hit").click();
await sleep(800);
ok("crit effect", (await page.locator("#toasts .toast.crit-fx").count()) === 1);
await page.screenshot({ path: OUT + "fx-crit.png" });
await page.evaluate(() => { Math.random = () => 0.001; });
await page.locator(".atk-row", { hasText: "Кинжал" }).locator(".chip.hit").click();
await sleep(800);
ok("fumble effect", (await page.locator("#toasts .toast.fumble-fx").count()) === 1);
await page.reload();
await page.waitForSelector(".sheet");
await page.click("[data-act=menu]");
await page.click("[data-m=print]");
await page.click(".modal-back.in [data-go]");
await sleep(500);
ok("print called", await page.evaluate(() => window.__printed === 1));
await page.emulateMedia({ media: "print" });
await page.pdf({ path: OUT + "sheet.pdf", format: "A4", printBackground: true });
await page.emulateMedia({ media: "screen" });
ok("no errors", errors.length === 0, errors.join("|"));
await browser.close();
console.log(r.join("\n"));
