import { chromium, launchOpts, E2E_OUT } from "./env.mjs";
const r = [];
const ok = (n, c, x = "") => r.push(`${c ? "PASS" : "FAIL"} ${n}${x ? " :: " + x : ""}`);
const sleep = ms => new Promise(res => setTimeout(res, ms));
const browser = await chromium.launch(launchOpts);
const ctx = await browser.newContext({ viewport: { width: 390, height: 844 }, serviceWorkers: "block", isMobile: true, hasTouch: true });
await ctx.route(/gstatic\.com|googleapis\.com|google\.com/, x => x.abort());
const page = await ctx.newPage();
const errors = [];
page.on("pageerror", e => errors.push(e.message));
await page.goto("http://localhost:8765/#/c/kirion-thorndike/spells");
await page.waitForSelector(".sheet");
await page.click("[data-act=spell-library]");
await page.waitForSelector(".modal-back.in .lib-ic");
const rows = await page.locator(".modal-back.in .lib-row").count();
ok("every spell row has an icon", rows > 0 && (await page.locator(".modal-back.in .lib-row .lib-ic").count()) === rows, String(rows));
await page.fill(".modal-back.in [data-q]", "паутина");
await sleep(300);
const webIc = await page.evaluate(async () => {
  const d = document.createElement("div");
  d.innerHTML = (await import("/js/icons.js")).icon((await import("/js/icon-map.js")).SPELL_ICONS.Web);
  return d.innerHTML;
});
const first = await page.locator(".modal-back.in .lib-row").first();
ok("web spell shows the web icon", (await first.locator("b").innerText()) === "Паутина" && (await first.locator(".lib-ic").innerHTML()) === webIc);
await page.click(".modal-back.in .lib-tabs button:has-text('Умения')");
await page.waitForSelector(".modal-back.in .lib-row .lib-ic");
const frows = await page.locator(".modal-back.in .lib-row").count();
ok("every feature row has an icon", frows > 0 && (await page.locator(".modal-back.in .lib-row .lib-ic").count()) === frows, String(frows));
await page.click(".modal-back.in .lib-tabs button:has-text('Снаряжение')");
await sleep(300);
const g = await page.locator(".modal-back.in .gear-row").count();
ok("every gear row has an icon", g > 0 && (await page.locator(".modal-back.in .gear-row .lib-ic").count()) === g, String(g));
ok("rows fit the phone", await page.$eval(".modal-back.in .modal", el => el.scrollWidth <= el.clientWidth + 1));
await page.screenshot({ path: E2E_OUT + "icons-gear.png" });
ok("no errors", errors.length === 0, errors.join("|"));
await browser.close();
console.log(r.join("\n"));
