import { chromium, launchOpts, E2E_OUT } from "./env.mjs";
const r = [];
const ok = (n, c, x = "") => r.push(`${c ? "PASS" : "FAIL"} ${n}${x ? " :: " + x : ""}`);
const sleep = ms => new Promise(res => setTimeout(res, ms));
const browser = await chromium.launch(launchOpts);
const ctx = await browser.newContext({ viewport: { width: 430, height: 900 }, serviceWorkers: "block", isMobile: true, hasTouch: true });
await ctx.route(/gstatic\.com|googleapis\.com|google\.com/, x => x.abort());
await ctx.addInitScript(() => localStorage.setItem("dnd.fx", JSON.stringify({ anim: false, sound: false })));
const page = await ctx.newPage();
const errors = [];
page.on("pageerror", e => errors.push(e.message));
const M = ".modal-back.in";
await page.goto("http://localhost:8765/#/c/kirion-thorndike/inventory");
await page.waitForSelector(".sheet");
await sleep(800);
await page.locator("[data-open^='item:']", { hasText: "Кинжал" }).first().click();
await page.waitForSelector(`${M} [data-x=edit]`);
await page.click(`${M} [data-x=edit]`);
await page.waitForSelector(`${M} [data-icon-q]`);
const before = await page.locator(`${M} [data-icons] .icon-opt`).count();
ok("picker starts small", before > 1 && before <= 62, String(before));
await page.fill(`${M} [data-icon-q]`, "меч");
await page.waitForFunction(() => [...document.querySelectorAll(".modal-back.in [data-icons] .icon-opt input")].some(i => i.value.startsWith("gi/") && i.value.includes("sword")));
const found = await page.$$eval(`${M} [data-icons] .icon-opt input`, els => els.map(e => e.value));
ok("search finds swords", found.some(v => v.startsWith("gi/") && v.includes("sword")) && !found.includes("acLow"), found.slice(0, 6).join(","));
const pick = found.find(v => v.startsWith("gi/") && v.includes("sword"));
await page.locator(`${M} [data-icons] .icon-opt`, { has: page.locator(`input[value="${pick}"]`) }).click();
await page.press(`${M} [data-icon-q]`, "Enter");
await sleep(200);
ok("enter in search does not close the form", (await page.locator(`${M} [data-icon-q]`).count()) === 1);
await page.screenshot({ path: E2E_OUT + "iconpick-found.png" });
await page.fill(`${M} [data-icon-q]`, "zzzz");
await sleep(500);
ok("chosen icon stays while searching", (await page.locator(`${M} [data-icons] input:checked`).getAttribute("value")) === pick);
ok("empty result says so", (await page.locator(`${M} .icon-none`).count()) === 1);
await page.screenshot({ path: E2E_OUT + "iconpick.png" });
await page.locator(`${M} button[type=submit]`).last().evaluate(b => b.click());
await sleep(500);
const html = await page.locator("[data-open^='item:']", { hasText: "Кинжал" }).first().innerHTML();
ok("item shows the picked icon", html.includes(pick.split("/").pop()), pick);
ok("no errors", errors.length === 0, errors.join("|"));
await browser.close();
console.log(r.join("\n"));
