import { chromium, launchOpts, E2E_OUT } from "./env.mjs";
const OUT = E2E_OUT;
const r = [];
const ok = (n, c, x = "") => r.push(`${c ? "PASS" : "FAIL"} ${n}${x ? " :: " + x : ""}`);
const sleep = ms => new Promise(res => setTimeout(res, ms));
const browser = await chromium.launch(launchOpts);
const ctx = await browser.newContext({ viewport: { width: 390, height: 844 }, hasTouch: true, isMobile: true, serviceWorkers: "block" });
await ctx.route(/gstatic\.com|googleapis\.com|google\.com/, x => x.abort());
const page = await ctx.newPage();
const errors = [];
page.on("pageerror", e => errors.push(e.message));
const M = ".modal-back.in";
await page.goto("http://localhost:8765/#/c/kirion-thorndike/inventory");
await page.waitForSelector(".sheet");
await sleep(300);
const before = await page.locator("[data-calc=weight]").innerText();
await page.click("[data-act=add-item]");
await sleep(300);
await page.fill(`${M} [data-k=name]`, "Рюкзак");
await page.fill(`${M} [data-k=weight]`, "5");
await page.locator(`${M} button[type=submit]`).click();
await sleep(400);
ok("container section", (await page.locator(".box-sec").count()) >= 1);
ok("load text", (await page.locator(".load-t").innerText()).length > 3, await page.locator(".load-t").innerText());
const slot = page.locator(".inv-grid .slot", { hasText: "Компас" }).first();
await slot.click();
await sleep(300);
await page.click(`${M} [data-x=move]`);
await sleep(300);
await page.locator(`${M} [data-to]`, { hasText: "Рюкзак" }).click();
await sleep(400);
ok("moved into backpack", (await page.locator(".box-sec", { hasText: "Рюкзак" }).locator(".slot", { hasText: "Компас" }).count()) === 1);
await page.locator(".box-sec", { hasText: "Рюкзак" }).locator("[data-act=box-stored]").click();
await sleep(300);
ok("stored marks section", (await page.locator(".box-sec.stored").count()) === 1);
const after = await page.locator("[data-calc=weight]").innerText();
ok("stored weight excluded", Number(after.replace(",", ".")) < Number(before.replace(",", ".")) + 5, `${before} -> ${after}`);
await page.screenshot({ path: OUT + "inv-boxes.png", fullPage: true });
await page.click(".tb-id[data-act=profile]");
await sleep(300);
await page.click("[data-m=backups]");
await sleep(300);
ok("backup dialog", (await page.locator(`${M} [data-bk-now]`).count()) === 1);
await page.click(`${M} [data-bk-now]`);
await sleep(300);
ok("backup listed", (await page.locator(`${M} .bk-row`).count()) >= 1);
const [dl] = await Promise.all([page.waitForEvent("download", { timeout: 5000 }).catch(() => null), page.click(`${M} [data-bk-file]`)]);
ok("file download", !!dl && /\.json$/.test(dl.suggestedFilename()), dl ? dl.suggestedFilename() : "none");
ok("no errors", errors.length === 0, errors.join(" | "));
console.log(r.join("\n"));
await browser.close();
