import { chromium, launchOpts, E2E_OUT } from "./env.mjs";
const OUT = E2E_OUT;
const r = [];
const ok = (n, c, x = "") => r.push(`${c ? "PASS" : "FAIL"} ${n}${x ? " :: " + x : ""}`);
const sleep = ms => new Promise(res => setTimeout(res, ms));
const browser = await chromium.launch(launchOpts);
for (const vp of [{ width: 1280, height: 900 }, { width: 390, height: 844, mobile: true }]) {
  const ctx = await browser.newContext({ viewport: { width: vp.width, height: vp.height }, hasTouch: !!vp.mobile, isMobile: !!vp.mobile });
  await ctx.route(/gstatic\.com|googleapis\.com|google\.com/, x => x.abort());
  const page = await ctx.newPage();
  const errors = [];
  page.on("pageerror", e => errors.push(e.message));
  await page.goto("http://localhost:8765/#/c/kirion-thorndike/spells");
  await page.waitForSelector(".sheet");
  await page.click("[data-act=spell-library]");
  await page.waitForSelector(".lib-row");
  const cls = await page.$eval("[data-cls]", s => s.value);
  ok("class guessed warlock", cls === "warlock", cls);
  const n0 = await page.locator(".lib-row").count();
  await page.fill("[data-q]", "невидим");
  await sleep(100);
  const n1 = await page.locator(".lib-row").count();
  ok("search narrows", n1 >= 1 && n1 < n0, `${n0} -> ${n1}`);
  await page.click(".lib-head >> nth=0");
  await sleep(100);
  ok("preview card", (await page.locator(".lib-card .bg-card").count()) === 1);
  await page.screenshot({ path: OUT + (vp.mobile ? "m" : "d") + "-lib.png" });
  const before = await page.evaluate(() => 0);
  await page.locator("[data-add]").dispatchEvent("click");
  await sleep(300);
  ok("marked as owned", (await page.locator(".lib-row .badge").count()) >= 1);
  await page.goBack();
  await sleep(400);
  ok("back closes library", (await page.locator(".modal-back.in").count()) === 0);
  ok("spell in sheet", (await page.locator(".tile-name", { hasText: "Невидимый слуга" }).count()) === 1);
  ok("no errors", errors.length === 0, errors.join("|"));
  await ctx.close();
}
await browser.close();
console.log(r.join("\n"));
