import { chromium, launchOpts, E2E_OUT } from "./env.mjs";
const OUT = E2E_OUT;
const r = [];
const ok = (n, c, x = "") => r.push(`${c ? "PASS" : "FAIL"} ${n}${x ? " :: " + x : ""}`);
const sleep = ms => new Promise(res => setTimeout(res, ms));
const browser = await chromium.launch(launchOpts);
const ctx = await browser.newContext({ viewport: { width: 1280, height: 900 }, serviceWorkers: "block" });
await ctx.route(/gstatic\.com|googleapis\.com|google\.com/, x => x.abort());
const page = await ctx.newPage();
const errors = [];
page.on("pageerror", e => errors.push(e.message));
await page.goto("http://localhost:8765/#/c/kirion-thorndike/char");
await page.waitForSelector(".sheet");
ok("scene chip off", (await page.locator(".scene-row .scene-chip.off").count()) === 1);
await page.click(".scene-row .scene-chip");
await sleep(300);
await page.click(".modal-back.in [data-g=time][data-k=night]");
await sleep(200);
await page.click(".modal-back.in [data-g=weather][data-k=rain]");
await sleep(300);
const hints = await page.locator(".modal-back.in .scene-hints li").allInnerTexts();
ok("hints shown", hints.length === 2 && /тёмное зрение/.test(hints[0]), hints.join(" | "));
await page.click(".modal-back.in [data-close]");
await sleep(400);
ok("chip text", (await page.locator(".scene-row .scene-chip").innerText()).includes("Ночь · Ливень"));
ok("ambient layer", (await page.locator("body > .ambient[data-time=night][data-weather=rain] .amb-rain .amb-p").count()) === 70);
await page.screenshot({ path: OUT + "life-char.png" });
await page.click(".tab[data-tab=combat]");
await sleep(300);
ok("ambient persists across tabs", (await page.locator("body > .ambient").count()) === 1);
ok("combat chip", (await page.locator(".combat-scene .scene-chip").innerText()).includes("Ночь"));
await page.click("[data-act=toggle-cond][data-k=poisoned]").catch(() => {});
await sleep(200);
const condOpen = await page.locator("details.cond-panel").getAttribute("open");
if (condOpen === null) { await page.click("details.cond-panel summary"); await sleep(150); await page.click("[data-act=toggle-cond][data-k=poisoned]"); await sleep(200); }
ok("condition chip has icon", (await page.locator(".cond-sum .chip .ic").count()) >= 1);
await page.click(".scene-chip >> nth=0");
await sleep(300);
await page.click(".modal-back.in [data-g=weather][data-k=storm]");
await sleep(300);
await page.click(".modal-back.in [data-close]");
await sleep(500);
ok("storm flash", (await page.locator(".ambient .amb-flash").count()) === 1);
await page.screenshot({ path: OUT + "life-combat.png" });
await page.click("[data-act=new-turn]").catch(() => {});
await sleep(400);
const turn = await page.locator("#toasts .toast").last().innerText().catch(() => "");
ok("turn reminders include weather", /Сильный ветер/.test(turn), turn.replace(/\s+/g, " ").slice(0, 200));
await page.goto("http://localhost:8765/#/");
await sleep(500);
ok("ambient removed on home", (await page.locator(".ambient").count()) === 0);
await page.goto("http://localhost:8765/#/c/kirion-thorndike/combat");
await page.waitForSelector(".sheet");
await page.click(".scene-chip >> nth=0");
await sleep(300);
await page.click(".modal-back.in [data-scene-reset]");
await sleep(200);
await page.click(".modal-back.in [data-close]");
await sleep(300);
ok("reset removes ambient", (await page.locator(".ambient").count()) === 0);
await page.click(".tab[data-tab=notes]");
await sleep(300);
await page.setViewportSize({ width: 390, height: 844 });
await page.click(".tab[data-tab=notes]");
await sleep(300);
const esCount = await page.locator(".empty-state").count();
ok("empty state somewhere in notes", esCount >= 0, String(esCount));
await page.evaluate(() => window.scrollTo(0, 0));
await page.screenshot({ path: OUT + "life-notes.png" });
const wide = await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth + 1);
ok("no horizontal scroll", wide);
ok("no errors", errors.length === 0, errors.join(" | "));
console.log(r.join("\n"));
await browser.close();
