import { chromium, launchOpts, E2E_OUT } from "./env.mjs";
const OUT = E2E_OUT;
const r = [];
const ok = (n, c, x = "") => r.push(`${c ? "PASS" : "FAIL"} ${n}${x ? " :: " + x : ""}`);
const sleep = ms => new Promise(res => setTimeout(res, ms));
const browser = await chromium.launch(launchOpts);
const ctx = await browser.newContext({ viewport: { width: 390, height: 844 }, hasTouch: true, isMobile: true, serviceWorkers: "block" });
await ctx.route(/gstatic\.com|googleapis\.com|google\.com/, x => x.abort());
const page = await ctx.newPage();
const errors = [];
page.on("pageerror", e => errors.push(e.message));
await page.goto("http://localhost:8765/#/c/kirion-thorndike/char");
await page.waitForSelector(".sheet");
await page.click("[data-act=menu]");
await page.click("[data-m=level-up]");
await sleep(300);
ok("wizard opens", (await page.locator(".modal-back.in .levelup").count()) === 1);
const txt = await page.locator(".modal-back.in").innerText();
ok("shows warlock notes", txt.includes("Удача Тёмного") && txt.includes("Новое заклинание"), txt.slice(0, 300).replace(/\n/g, " | "));
ok("hp preview 43 → 51", txt.includes("43 → 51"));
await page.screenshot({ path: OUT + "lvl-1.png", fullPage: false });
await page.click(".modal-back.in [data-roll-hp]");
await sleep(150);
const res = await page.locator(".modal-back.in [data-roll-res]").innerText();
ok("hp roll shown", /= \d+/.test(res), res);
await page.click(".modal-back.in [data-go]");
await sleep(400);
ok("level is 6", (await page.locator("[data-calc=level]").innerText()) === "6");
const t = await page.locator("#toasts .toast", { hasText: "6 уровень" }).innerText();
ok("toast with library button", t.includes("Не забудь") && (await page.locator("#toasts [data-lu-lib]").count()) === 1, t.replace(/\n/g, " "));
ok("undo available", (await page.locator("#undo-bar.in").count()) === 1);
await page.click("[data-act=menu]");
await page.click("[data-m=level-up]");
await sleep(200);
await page.click(".modal-back.in [data-go]");
await sleep(300);
await page.click("[data-act=menu]");
await page.click("[data-m=level-up]");
await sleep(300);
ok("level 8 has ASI", (await page.locator(".modal-back.in input[name=lu-asi]").count()) === 4);
await page.click(".modal-back.in input[name=lu-asi][value=two]");
await page.selectOption(".modal-back.in [data-a1]", "int");
await page.selectOption(".modal-back.in [data-a2]", "con");
await sleep(100);
const ch = await page.locator(".modal-back.in [data-changes]").innerText();
ok("ASI preview shown", ch.includes("Хиты"), ch.replace(/\n/g, " | "));
await page.screenshot({ path: OUT + "lvl-asi.png" });
await page.click(".modal-back.in [data-go]");
await sleep(300);
ok("int 19 con 17", (await page.inputValue("input[data-path='abilities.int']")) === "19" && (await page.inputValue("input[data-path='abilities.con']")) === "17");
ok("no errors", errors.length === 0, errors.join("|"));
await browser.close();
console.log(r.join("\n"));
