import { chromium, launchOpts, E2E_OUT } from "./env.mjs";
const OUT = E2E_OUT;
const r = [];
const ok = (n, c, x = "") => r.push(`${c ? "PASS" : "FAIL"} ${n}${x ? " :: " + x : ""}`);
const sleep = ms => new Promise(res => setTimeout(res, ms));
const browser = await chromium.launch(launchOpts);
const ctx = await browser.newContext({ viewport: { width: 390, height: 844 }, hasTouch: true, isMobile: true, serviceWorkers: "block" });
await ctx.route(/gstatic\.com|googleapis\.com|google\.com/, x => x.abort());
const page = await ctx.newPage();
const errors = [];
page.on("pageerror", e => errors.push(e.message));
await page.goto("http://localhost:8765/#/c/kirion-thorndike/char");
await page.waitForSelector(".sheet");
const open = async () => { await page.click("[data-act=menu]"); await page.click("[data-m=level-up]"); await sleep(700); };
await open();
const M = ".modal-back.in";
const txt = await page.locator(M).innerText();
ok("fiend feature 6", txt.includes("Удача Тёмного"), txt.slice(0, 200).replace(/\n/g, " | "));
ok("no generic patron note", !txt.includes("Умение покровителя 6 уровня"));
ok("spell picker", (await page.locator(`${M} [data-picker=spells] .lu-opt`).count()) > 20, String(await page.locator(`${M} [data-picker=spells] .lu-opt`).count()));
const names = await page.$$eval(`${M} [data-picker=spells] .lu-name b`, bs => bs.map(b => b.textContent));
ok("fiend expanded list present", names.includes("Палящий луч") && names.includes("Зловонное облако"), names.slice(0, 12).join(","));
ok("known spells hidden", !names.includes("Огненный шар") && !names.includes("Туманный шаг"));
ok("no 4th level", !names.includes("Огненная стена"));
await page.fill(`${M} [data-lu-q=spells]`, "удержание");
await sleep(150);
await page.click(`${M} [data-picker=spells] .lu-pick:has-text("Удержание личности")`);
await sleep(100);
ok("picked counter", (await page.locator(`${M} [data-count=spells]`).innerText()) === "1 из 1");
await page.click(`${M} [data-picker=spells] [data-info]`);
await sleep(100);
ok("description opens", (await page.locator(`${M} [data-picker=spells] .lu-desc`).count()) === 1);
await page.screenshot({ path: OUT + "lvl2-a.png" });
await page.click(`${M} details[data-swap=spell] summary`);
await page.selectOption(`${M} [data-swap-out]`, { label: "Голод Хадара (3 круг)" });
await sleep(700);
await page.fill(`${M} [data-lu-q=swapSpell]`, "невидим");
await sleep(150);
await page.click(`${M} [data-picker=swapSpell] .lu-pick:has-text("Невидимость")`);
await sleep(100);
ok("left all done", (await page.locator(`${M} [data-left]`).innerText()).includes("Всё выбрано"), await page.locator(`${M} [data-left]`).innerText());
await page.click(`${M} [data-go]`);
await sleep(500);
const toastT = await page.locator(".modal-back.in .levelup-card .lu-got").innerText();
ok("card lists new", toastT.includes("Удача Тёмного") && toastT.includes("Удержание личности") && toastT.includes("Невидимость"), toastT.replace(/\n/g, " "));
await page.click(".modal-back.in .levelup-card .form-actions [data-close]");
await sleep(250);
await page.click(".tab[data-tab=spells]");
await sleep(300);
const sp = await page.locator(".sheet").innerText();
ok("spells updated", sp.includes("Удержание личности") && sp.includes("Невидимость") && !sp.includes("Голод Хадара"));
await page.click(".tab[data-tab=features]");
await sleep(300);
ok("feature added", (await page.locator(".sheet").innerText()).includes("Удача Тёмного"));
await open();
const t7 = await page.locator(M).innerText();
ok("level 7 invocation picker", (await page.locator(`${M} [data-picker=invocations]`).count()) === 1);
const agon = page.locator(`${M} [data-picker=invocations] .lu-opt:has-text("Мучительный заряд")`);
ok("agonizing available", (await agon.count()) === 1 && !(await agon.getAttribute("class")).includes("locked"));
const lifed = page.locator(`${M} [data-picker=invocations] .lu-opt:has-text("Пьющий жизнь")`);
ok("lifedrinker locked", (await lifed.getAttribute("class")).includes("locked"));
ok("owned hidden", (await page.locator(`${M} [data-picker=invocations] .lu-opt:has-text("Маска многих лиц")`).count()) === 0);
await agon.locator(".lu-pick").click();
await sleep(100);
await page.screenshot({ path: OUT + "lvl2-b.png" });
await page.click(`${M} [data-go]`);
await sleep(500);
await page.click(".modal-back.in .levelup-card .form-actions [data-close]");
await sleep(250);
await page.click(".tab[data-tab=features]");
await sleep(300);
ok("invocation added", (await page.locator(".sheet").innerText()).includes("Мучительный заряд"));
await page.click("#undo-bar [data-undo]").catch(() => {});
await sleep(300);
ok("undo removes invocation", !(await page.locator(".sheet").innerText()).includes("Мучительный заряд"));
const wide = await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth + 1);
ok("no horizontal scroll", wide);
ok("no errors", errors.length === 0, errors.join(" | "));
console.log(r.join("\n"));
await browser.close();
