import { chromium, launchOpts, E2E_OUT } from "./env.mjs";
const OUT = E2E_OUT;
const r = [];
const ok = (n, c, x = "") => r.push(`${c ? "PASS" : "FAIL"} ${n}${x ? " :: " + x : ""}`);
const sleep = ms => new Promise(res => setTimeout(res, ms));
const browser = await chromium.launch(launchOpts);
const ctx = await browser.newContext({ viewport: { width: 390, height: 844 }, hasTouch: true, isMobile: true, serviceWorkers: "block" });
await ctx.route(/gstatic\.com|googleapis\.com|google\.com/, x => x.abort());
const page = await ctx.newPage();
const errors = [];
page.on("pageerror", e => errors.push(e.message));
const M = ".modal-back.in";
await page.goto("http://localhost:8765/#/c/kirion-thorndike/notes");
await page.waitForSelector(".sheet");
await sleep(300);
ok("journal is default", (await page.locator(".subtab.on").innerText()).includes("Журнал"));
ok("journal box", (await page.locator("[data-journal]").count()) === 1);
ok("seven sections", (await page.locator(".notes-tabs .subtab").count()) === 7);
await page.click("[data-journal]");
await page.keyboard.type("Пришли в порт, говорили с [[Рэ");
await sleep(200);
const sg = await page.locator(".rt-suggest:not([hidden]) .rt-sg b").allInnerTexts();
ok("link suggest shows Рэй", sg.includes("Рэй"), sg.join(","));
await page.keyboard.press("Enter");
await sleep(100);
ok("suggest inserts link", (await page.inputValue("[data-journal]")).endsWith("[[Рэй]]"), await page.inputValue("[data-journal]"));
await page.keyboard.press("Enter");
await sleep(400);
ok("session created", (await page.locator("article.note[data-sec=sessions]").count()) === 1);
const sesText = await page.locator("article.note[data-sec=sessions] .note-text").innerText();
ok("entry with time", /\d\d:\d\d\s+Пришли в порт/.test(sesText), sesText);
ok("link rendered", (await page.locator("article.note[data-sec=sessions] .wl:not(.soft):not(.missing)").count()) === 1);
ok("journal keeps focus", await page.evaluate(() => document.activeElement && document.activeElement.matches("[data-journal]")));
await page.keyboard.type("Халвар просил передать письмо, [[Капитан Сорн]] ждёт ответа");
await page.keyboard.press("Enter");
await sleep(400);
ok("mention of Халвар soft link", (await page.locator("article.note[data-sec=sessions] .wl.soft").count()) >= 1);
ok("missing link shown", (await page.locator("article.note[data-sec=sessions] .wl.missing").count()) === 1);
await page.click("[data-act=quick-note]");
await sleep(300);
await page.click(`${M} [data-to=places]`);
await page.fill(`${M} [data-qn-title]`, "Порт Сильверхолл");
await page.fill(`${M} [data-qn-text]`, "Склады, контрабанда, люди [[Рэй]]");
await page.click(`${M} [data-qn-save]`);
await sleep(400);
ok("quick note to places", (await page.locator(".notes-tabs [data-k=places] small").innerText()) === "1");
await page.click("article.note[data-sec=sessions] .wl.missing");
await sleep(300);
ok("create from link dialog", (await page.locator(`${M} [data-sec=people]`).count()) === 1);
await page.click(`${M} [data-sec=people]`);
await sleep(400);
ok("editor prefilled", (await page.inputValue(`${M} [data-k=title]`)) === "Капитан Сорн");
await page.fill(`${M} [data-k=aliases]`, "Сорн");
await page.click(`${M} button[type=submit]`);
await sleep(400);
await page.click(".notes-tabs [data-k=sessions]");
await sleep(300);
ok("link now resolves", (await page.locator("article.note[data-sec=sessions] .wl.missing").count()) === 0);
await page.locator("article.note[data-sec=sessions] .wl", { hasText: "Рэй" }).first().click();
await sleep(700);
ok("jumped to people", (await page.locator(".subtab.on").innerText()).includes("Люди"));
const ray = page.locator("article.note[data-sec=people]", { hasText: "Рэй" }).first();
ok("target expanded", !(await ray.getAttribute("class")).includes("collapsed"));
const backTxt = await ray.locator(".note-back").innerText().catch(() => "");
ok("backlinks listed", backTxt.includes("Сессия 1") && backTxt.includes("Порт Сильверхолл"), backTxt);
await ray.locator("[data-act=pin-note]").click();
await sleep(300);
ok("pinned strip", (await page.locator(".pinned-strip .pin-chip").count()) === 1);
await page.fill("[data-ui=notes-q]", "капитана");
await sleep(300);
const found = await page.locator("[data-notes-list] article.note").count();
ok("smart search by case form", found >= 1, String(found));
ok("search highlights", (await page.locator("[data-notes-list] mark").count()) >= 1);
await page.screenshot({ path: OUT + "notes-search.png" });
await page.fill("[data-ui=notes-q]", "");
await sleep(200);
await page.click(".tab[data-tab=combat]");
await sleep(300);
ok("important on combat", (await page.locator(".p-important .imp-row").count()) === 1);
await page.click(".p-important .imp-row");
await sleep(600);
ok("important opens note", (await page.locator(".subtab.on").innerText()).includes("Люди"));
await page.click(".notes-tabs [data-k=clues]");
await page.click("[data-act=add-note][data-sec=clues]");
await sleep(300);
await page.fill(`${M} [data-k=title]`, "Следы сажи");
await page.selectOption(`${M} [data-k=state]`, "lead");
await page.click(`${M} button[type=submit]`);
await sleep(300);
ok("clue with badge", (await page.locator("article.note[data-sec=clues] .badge", { hasText: "Зацепка" }).count()) === 1);
await page.click("[data-act=clue-state][data-k=confirmed]");
await sleep(200);
ok("clue filter", (await page.locator("article.note[data-sec=clues]").count()) === 0);
await page.click(".notes-tabs [data-k=sessions]");
await sleep(300);
await page.evaluate(() => window.scrollTo(0, 0));
await page.screenshot({ path: OUT + "notes-journal.png" });
await page.click("[data-act=menu]"); await sleep(200); await page.click("[data-m=search-all]");
await sleep(300);
await page.fill(`${M} [data-q]`, "сорна");
await sleep(200);
const gs = await page.locator(`${M} .am-row b`).allInnerTexts();
ok("global search finds note", gs.includes("Капитан Сорн"), gs.join(","));
await page.locator(`${M} .am-row`, { hasText: "Капитан Сорн" }).click();
await sleep(600);
ok("global search opens note", (await page.locator(".subtab.on").innerText()).includes("Люди"));
const wide = await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth + 1);
ok("no horizontal scroll", wide);
const tb = await page.evaluate(() => { const t = document.querySelector(".topbar"); return t.scrollWidth <= t.clientWidth + 1; });
ok("topbar fits", tb);
ok("no errors", errors.length === 0, errors.join(" | "));
console.log(r.join("\n"));
await browser.close();
