import { chromium, launchOpts, E2E_OUT } from "./env.mjs";
const OUT = E2E_OUT;
const r = [];
const ok = (n, c, x = "") => r.push(`${c ? "PASS" : "FAIL"} ${n}${x ? " :: " + x : ""}`);
const sleep = ms => new Promise(res => setTimeout(res, ms));
const browser = await chromium.launch(launchOpts);
const ctx = await browser.newContext({ viewport: { width: 390, height: 844 }, hasTouch: true, isMobile: true });
await ctx.route(/googleapis\.com|google\.com|firebasejs/, x => x.abort());
const page = await ctx.newPage();
const errors = [];
page.on("pageerror", e => errors.push(e.message));
await page.goto("http://localhost:8765/#/c/kirion-thorndike/char");
await page.waitForSelector(".sheet");
const active = await page.evaluate(async () => { const reg = await navigator.serviceWorker.ready; return !!reg.active; });
ok("service worker active", active);
await page.reload();
await page.waitForSelector(".sheet");
const cached = await page.evaluate(async () => { const keys = await caches.keys(); let n = 0; for (const k of keys) n += (await (await caches.open(k)).keys()).length; return keys.join(",") + " " + n; });
ok("files cached", /dnd-shell-v\d+/.test(cached) && Number(cached.split(" ")[1]) >= 20, cached);
await ctx.setOffline(true);
await page.reload();
await page.waitForSelector(".sheet", { timeout: 15000 });
ok("sheet opens offline", (await page.locator(".hero-name").innerText()).includes("Кирион"));
await page.click(".tab[data-tab=spells]");
await page.click("[data-act=spell-library]");
await page.waitForSelector(".lib-row", { timeout: 8000 }).catch(() => {});
ok("library works offline", (await page.locator(".lib-row").count()) > 10);
await page.screenshot({ path: OUT + "offline.png" });
await ctx.setOffline(false);
ok("no errors", errors.length === 0, errors.join("|"));
await browser.close();
console.log(r.join("\n"));
