import { chromium, launchOpts, E2E_OUT } from "./env.mjs";
const OUT = E2E_OUT;
const r = [];
const ok = (n, c, x = "") => r.push(`${c ? "PASS" : "FAIL"} ${n}${x ? " :: " + x : ""}`);
const sleep = ms => new Promise(res => setTimeout(res, ms));
const browser = await chromium.launch(launchOpts);
{
  const ctx = await browser.newContext({ viewport: { width: 1280, height: 900 } });
  await ctx.route(/gstatic\.com|googleapis\.com|google\.com/, x => x.abort());
  const page = await ctx.newPage();
  const errors = [];
  page.on("pageerror", e => errors.push(e.message));
  await page.goto("http://localhost:8765/#/c/kirion-thorndike/inventory");
  await page.waitForSelector(".sheet");
  await page.screenshot({ path: OUT + "o-inv-icons.png" });
  await page.click(".order-btn");
  await sleep(150);
  const names = async () => page.$$eval(".inv-grid > [data-rid] .slot-name", ns => ns.map(n => n.textContent));
  const before = await names();
  const h0 = await page.locator(".inv-grid > [data-rid] .drag-h").nth(0).boundingBox();
  const t2 = await page.locator(".inv-grid > [data-rid]").nth(2).boundingBox();
  await page.mouse.move(h0.x + h0.width / 2, h0.y + h0.height / 2);
  await page.mouse.down();
  for (let i = 1; i <= 10; i++) await page.mouse.move(h0.x + (t2.x + t2.width * 0.7 - h0.x) * i / 10, h0.y + 30 * i / 10, { steps: 2 });
  await page.mouse.up();
  await sleep(300);
  const after = await names();
  ok("drag reorders items", after[2] === before[0] && after[0] === before[1], after.slice(0, 3).join(","));
  await page.click(".order-bar [data-act=toggle-order]");
  await page.reload();
  await page.waitForSelector(".sheet");
  await page.selectOption("[data-ui=inv-sort]", "added");
  await page.click("[data-act=inv-eq-first]").catch(() => {});
  const persisted = await names();
  ok("order persisted", persisted.slice(0, 3).join(",") === after.slice(0, 3).join(",") || persisted.includes(after[0]), persisted.slice(0, 3).join(","));
  await page.click(".tab[data-tab=spells]");
  await page.click("[data-act=spell-library]");
  await page.waitForSelector(".lib-row");
  ok("target select lists items with charges", (await page.locator("[data-target] option").count()) >= 2);
  await page.keyboard.press("Escape");
  ok("no errors desktop", errors.length === 0, errors.join("|"));
  await ctx.close();
}
{
  const ctx = await browser.newContext({ viewport: { width: 390, height: 844 }, hasTouch: true, isMobile: true });
  await ctx.route(/gstatic\.com|googleapis\.com|google\.com/, x => x.abort());
  const page = await ctx.newPage();
  const errors = [];
  page.on("pageerror", e => errors.push(e.message));
  await page.goto("http://localhost:8765/#/c/kirion-thorndike/inventory");
  await page.waitForSelector(".sheet");
  await page.click("[data-act=add-item]");
  await page.fill(".modal-back.in input[data-k=name]", "Палочка холода");
  await page.fill(".modal-back.in input[data-k=uses]", "7");
  await page.click(".modal-back.in button[type=submit]");
  await sleep(300);
  await page.click(".tab[data-tab=spells]");
  await page.click("[data-act=spell-library]");
  await page.waitForSelector("[data-target]");
  await page.fill("[data-q]", "Град");
  await sleep(100);
  await page.selectOption("[data-target]", { label: "Палочка холода (заряды)" });
  await page.locator(".lib-head").first().click();
  await sleep(150);
  const addLabel = await page.locator("[data-add]").innerText();
  ok("add label mentions wand", addLabel.includes("Палочка холода"), addLabel);
  await page.locator("[data-add]").dispatchEvent("click");
  await sleep(200);
  await page.selectOption("[data-target]", "");
  await page.fill("[data-q]", "Метель");
  await sleep(100);
  await page.locator(".lib-head").first().click();
  await sleep(150);
  await page.locator("[data-add]").dispatchEvent("click");
  await sleep(200);
  await page.goBack();
  await sleep(400);
  const panelTitle = await page.locator(".item-spells-panel h3").innerText().catch(() => "");
  ok("wand panel in spells tab", panelTitle === "Палочка холода", panelTitle);
  ok("hail inside wand panel", (await page.locator(".item-spells-panel .tile-name", { hasText: "Град" }).count()) === 1);
  await page.locator(".tile", { hasText: "Метель" }).click();
  await sleep(300);
  await page.click(".modal-back.in [data-x=to-item]");
  await sleep(300);
  await page.click(".modal-back.in [data-it] >> nth=0");
  await sleep(300);
  ok("sleet moved into wand", (await page.locator(".item-spells-panel .tile-name", { hasText: "Метель" }).count()) === 1);
  await page.screenshot({ path: OUT + "o-m-spells.png", fullPage: true });
  await page.click(".order-btn >> nth=0");
  await sleep(200);
  const tiles = async () => page.$$eval(".panel:has(h3:text-is('Заговоры')) .tiles > [data-rid] .tile-name", ns => ns.map(n => n.textContent));
  const b = await tiles();
  const h = await page.locator(".panel:has(h3:text-is('Заговоры')) .tiles > [data-rid] .drag-h").nth(0);
  await page.evaluate(() => document.querySelector(".panel:has(.tiles)").scrollIntoView({ block: "start" }));
  await page.evaluate(() => window.scrollBy(0, -260));
  await sleep(200);
  const hb = await h.boundingBox();
  const tb = await page.locator(".panel:has(h3:text-is('Заговоры')) .tiles > [data-rid]").nth(2).boundingBox();
  const cdp = await ctx.newCDPSession(page);
  const tp = async (type, x, y) => cdp.send("Input.dispatchTouchEvent", { type, touchPoints: type === "touchEnd" ? [] : [{ x, y }] });
  await tp("touchStart", hb.x + 10, hb.y + 10);
  for (let i = 1; i <= 12; i++) { await tp("touchMove", hb.x + 10, hb.y + 10 + (tb.y + tb.height * 0.6 - hb.y) * i / 12); await sleep(16); }
  await tp("touchEnd", 0, 0);
  await sleep(300);
  const a = await tiles();
  ok("touch drag reorders cantrips", a[2] === b[0] || a[1] === b[0], `${b.slice(0, 3)} -> ${a.slice(0, 3)}`);
  await page.screenshot({ path: OUT + "o-m-ordering.png" });
  ok("no errors mobile", errors.length === 0, errors.join("|"));
  await ctx.close();
}
await browser.close();
console.log(r.join("\n"));
