import { chromium, launchOpts, E2E_OUT } from "./env.mjs";
const r = [];
const ok = (n, c, x = "") => r.push(`${c ? "PASS" : "FAIL"} ${n}${x ? " :: " + x : ""}`);
const sleep = ms => new Promise(res => setTimeout(res, ms));
const browser = await chromium.launch(launchOpts);
const ctx = await browser.newContext({ viewport: { width: 390, height: 844 }, serviceWorkers: "block", isMobile: true, hasTouch: true });
await ctx.route(/gstatic\.com|googleapis\.com|google\.com/, x => x.abort());
const page = await ctx.newPage();
const errors = [];
page.on("pageerror", e => errors.push(e.message));
const add = async name => {
  await page.click("[data-act=add-item]");
  await page.fill(".modal-back.in input[data-k=name]", name);
  await page.click(".modal-back.in button[type=submit]");
  await sleep(300);
};
const open = async name => {
  await page.click(`[data-open^='item:']:has-text('${name}')`);
  await page.waitForSelector(".modal-back.in");
};
await page.goto("http://localhost:8765/#/c/kirion-thorndike/inventory");
await page.waitForSelector(".sheet");
await add("Рюкзак");
await add("Мешочек с компонентами");
const icOf = async name => page.locator(`[data-open^='item:']:has-text('${name}') svg`).first().innerHTML();
ok("backpack and pouch have different icons", (await icOf("Рюкзак")) !== (await icOf("Мешочек с компонентами")));
await open("Мешочек с компонентами");
ok("pouch offers an explanation, not a pack", (await page.locator(".modal-back.in [data-x=pouch-info]").count()) === 1 && (await page.locator(".modal-back.in [data-x=pack]").count()) === 0);
await page.click(".modal-back.in [data-x=pouch-info]");
await sleep(300);
ok("explanation mentions costly components", /с ценой/.test(await page.locator(".modal-back.in").last().innerText()));
await page.keyboard.press("Escape");
await sleep(200);
await page.keyboard.press("Escape");
await sleep(300);
await open("Рюкзак");
await page.click(".modal-back.in [data-x=pack]");
await page.waitForSelector(".modal-back.in .pack-row");
ok("seven standard packs", (await page.locator(".modal-back.in .pack-row").count()) === 7);
await sleep(400);
await page.screenshot({ path: E2E_OUT + "packs.png" });
await page.click(".modal-back.in [data-pack=explorer]");
await sleep(500);
ok("undo offered for the pack", (await page.locator("#undo-bar.in").count()) === 1);
const inv = await page.locator(".sheet").innerText();
ok("pack items appear", /Спальник/.test(inv) && /Факел/.test(inv) && /Рацион/.test(inv), inv.slice(0, 200));
await open("Факел");
ok("torches sit in the backpack", /В «Рюкзак»/.test(await page.locator(".modal-back.in").innerText()));
ok("no errors", errors.length === 0, errors.join("|"));
await browser.close();
console.log(r.join("\n"));
