import { chromium, launchOpts, E2E_OUT } from "./env.mjs";
const r = [];
const ok = (n, c, x = "") => r.push(`${c ? "PASS" : "FAIL"} ${n}${x ? " :: " + x : ""}`);
const sleep = ms => new Promise(res => setTimeout(res, ms));
const browser = await chromium.launch(launchOpts);
const ctx = await browser.newContext({ viewport: { width: 1280, height: 900 }, serviceWorkers: "block" });
await ctx.route(/gstatic\.com|googleapis\.com|google\.com/, x => x.abort());
const page = await ctx.newPage();
const errors = [];
page.on("pageerror", e => errors.push(e.message));
await page.goto("http://localhost:8765/#/c/kirion-thorndike/features");
await page.waitForSelector(".sheet");
await page.click(".tile:has-text('Архив знаний')");
await page.click(".modal-back.in [data-x=edit]");
await page.selectOption(".modal-back.in select[data-k=combat]", "yes");
await page.click(".modal-back.in button[type=submit]");
await sleep(300);
await page.click(".tab[data-tab=combat]");
ok("pinned group", (await page.locator(".atk-group", { hasText: "Закреплено" }).count()) === 1);
await page.click("[data-act=pin-use]");
await sleep(200);
ok("pinned use spends", (await page.locator("[data-act=pin-use]").innerText()).includes("2/3"));
ok("undo for pinned use", await page.locator(".st-btn.has-undo").count() === 1);
ok("no errors", errors.length === 0, errors.join("|"));
await browser.close();
console.log(r.join("\n"));
