import { chromium, launchOpts, E2E_OUT } from "./env.mjs";
const OUT = E2E_OUT;
const r = [];
const ok = (n, c, x = "") => r.push(`${c ? "PASS" : "FAIL"} ${n}${x ? " :: " + x : ""}`);
const sleep = ms => new Promise(res => setTimeout(res, ms));
const browser = await chromium.launch(launchOpts);
const ctx = await browser.newContext({ viewport: { width: 390, height: 844 }, hasTouch: true, isMobile: true, serviceWorkers: "block" });
await ctx.route(/gstatic\.com|googleapis\.com|google\.com/, x => x.abort());
const page = await ctx.newPage();
const errors = [];
page.on("pageerror", e => errors.push(e.message));
const P = ".modal.profile";

await page.goto("http://localhost:8765/#/c/kirion-thorndike/story");
await page.waitForSelector(".sheet");
ok("old story link opens the hero tab", (await page.locator(".tab.on[data-tab=char]").count()) === 1);
ok("six tabs at the bottom", (await page.locator(".tab").count()) === 6);
ok("hint about the profile", (await page.locator(".hero-hint").count()) === 1);
await page.evaluate(() => {
  const fire = (type, x) => document.dispatchEvent(new TouchEvent(type, { touches: [new Touch({ identifier: 1, target: document.body, clientX: x, clientY: 400 })], bubbles: true }));
  fire("touchstart", 5);
  fire("touchmove", 120);
});
await page.waitForSelector(`${P} .pf-head`);
ok("swipe from the left edge opens the profile", true);
await page.keyboard.press("Escape");
await sleep(300);

await page.click(".hero-id");
await page.waitForSelector(`${P} .pf-head`);
ok("hero name opens the profile", (await page.locator(`${P} .pf-id b`).innerText()) === "Кирион Торндайк");
await page.click(`${P} [data-pf-go=who]`);
ok("who page has the race", (await page.locator(`${P} [data-k="info.race"]`).inputValue()) === "Тифлинг");
await page.fill(`${P} [data-k="info.race"]`, "Тифлинг-северянин");
await page.fill(`${P} [data-k=name]`, "Кирион Торн");
await page.click(`${P} [data-pf-back]`);
ok("drawer header shows new name", (await page.locator(`${P} .pf-id b`).innerText()) === "Кирион Торн");
await page.click(`${P} [data-pf-go=story]`);
await page.fill(`${P} [data-k="personality.ideals"]`, "Знание дороже золота");
await page.click(`${P} [data-pf-back]`);
await page.click(`${P} [data-pf-go=mech]`);
await page.fill(`${P} [data-k=speed]`, "35");
await page.press(`${P} [data-k=speed]`, "Tab");
await sleep(300);
ok("mechanics change recalculates the sheet", (await page.locator("[data-calc=speed]").first().innerText()).includes("35"));
await page.screenshot({ path: OUT + "profile-mech.png" });
await page.keyboard.press("Escape");
await sleep(400);
ok("drawer closed", (await page.locator(`${P}`).count()) === 0);
ok("hero shows new race", (await page.locator(".hero-id").innerText()).includes("Тифлинг-северянин"));
ok("top bar shows new name", (await page.locator(".tb-name").innerText()) === "Кирион Торн");
await sleep(800);
const saved = await page.evaluate(() => localStorage.getItem("dnd.chars") || "");
ok("personality saved", saved.includes("Знание дороже золота"));

await page.click(".hero-portrait");
await page.waitForSelector(`${P} .pf-head`);
await page.click(`${P} [data-pf-go=portrait]`);
ok("portrait page has the board", (await page.locator(`${P} .pb-board`).count()) === 1);
await page.click(`${P} [data-pf-back]`);
await page.click(`${P} [data-pf-toggle]`);
ok("my characters list", (await page.locator(`${P} .pf-list:not([hidden]) .pf-char.on`).count()) === 1);
ok("new character entry", (await page.locator(`${P} [data-new]`).count()) === 1);
ok("sheet files in drawer", (await page.locator(`${P} [data-m=export]`).count()) === 1);
await page.screenshot({ path: OUT + "profile-root.png" });
await page.keyboard.press("Escape");
await sleep(300);
await page.click("[data-act=menu]");
ok("menu has no sheet files", (await page.locator(".modal-back.in [data-m=export]").count()) === 0);
await page.keyboard.press("Escape");

await page.goto("http://localhost:8765/#/t/wizard/char");
await page.waitForSelector(".sheet.viewer");
await page.click(".tb-id[data-act=profile]");
await page.click(`${P} [data-pf-go=who]`);
ok("template profile is read only", (await page.locator(`${P} .pf-page input:not(:disabled)`).count()) === 0);
ok("no errors", errors.length === 0, errors.join("|"));
console.log(r.join("\n"));
await browser.close();
