import { chromium, launchOpts, E2E_OUT } from "./env.mjs";
const OUT = E2E_OUT;
const r = [];
const ok = (n, c, x = "") => r.push(`${c ? "PASS" : "FAIL"} ${n}${x ? " :: " + x : ""}`);
const sleep = ms => new Promise(res => setTimeout(res, ms));
const browser = await chromium.launch(launchOpts);
const ctx = await browser.newContext({ viewport: { width: 390, height: 844 }, hasTouch: true, isMobile: true, serviceWorkers: "block", userAgent: "Mozilla/5.0 (iPhone; CPU iPhone OS 17_0 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.0 Mobile/15E148 Safari/604.1" });
await ctx.route(/gstatic\.com|googleapis\.com|google\.com/, x => x.abort());
const page = await ctx.newPage();
const errors = [];
page.on("pageerror", e => errors.push(e.message));
const man = await (await page.request.get("http://localhost:8765/manifest.webmanifest")).json();
ok("manifest icons", man.icons.length === 4 && man.display === "standalone", man.short_name);
for (const f of ["icon-192.png", "icon-512.png", "apple-touch-icon.png", "icon-maskable-512.png"]) ok("served " + f, (await page.request.get("http://localhost:8765/" + f)).ok());
await page.goto("http://localhost:8765/#/");
await page.waitForSelector(".home");
ok("install banner on iPhone", (await page.locator(".install-bar").count()) === 1);
await page.click("[data-install]");
await sleep(300);
ok("iOS instructions", (await page.locator(".modal-back.in .install-steps").count()) === 1);
await page.screenshot({ path: OUT + "pwa-ios.png" });
await page.goBack();
await sleep(300);
await page.click("[data-install-hide]");
await page.reload();
await page.waitForSelector(".home");
ok("banner hidden after dismiss", (await page.locator(".install-bar").count()) === 0);
await page.goto("http://localhost:8765/#/c/kirion-thorndike/combat");
await page.waitForSelector(".sheet");
await page.click("[data-act=menu]");
await page.click("[data-m=rules-ref]");
await sleep(300);
await page.fill(".modal-back.in [data-q]", "падение");
await sleep(100);
const vis = await page.$$eval(".ref-item", els => els.filter(e => !e.hidden).map(e => e.querySelector("summary span").textContent));
ok("rules search", vis.length === 1 && vis[0] === "Падение", vis.join(","));
await page.screenshot({ path: OUT + "ref.png" });
await page.goBack();
await sleep(300);
await page.click("[data-act=toggle-cond][data-k=poisoned]").catch(async () => { await page.click("summary.panel-h"); await page.click("[data-act=toggle-cond][data-k=poisoned]"); });
await page.click("[data-act=new-turn]");
await sleep(300);
const t = await page.locator("#toasts .toast", { hasText: "Новый ход" }).innerText();
ok("turn reminders", t.includes("Отравлен") && t.includes("Бонусным действием можно"), t.replace(/\n/g, " | "));
await page.click("[data-act=hp-quick][data-n='-10']");
for (let i = 0; i < 4; i++) await page.click("[data-act=hp-quick][data-n='-10']");
await sleep(300);
ok("unconscious hint", (await page.locator("#toasts .toast", { hasText: "0 хитов" }).count()) === 1);
await page.click("[data-act=new-turn]");
await sleep(300);
ok("death save button in reminders", (await page.locator("#toasts [data-rem-death]").count()) === 1);
await page.screenshot({ path: OUT + "remind.png" });
ok("no errors", errors.length === 0, errors.join("|"));
await browser.close();
console.log(r.join("\n"));
