import { chromium, launchOpts, E2E_OUT } from "./env.mjs";
const r = [];
const ok = (n, c, x = "") => r.push(`${c ? "PASS" : "FAIL"} ${n}${x ? " :: " + x : ""}`);
const sleep = ms => new Promise(res => setTimeout(res, ms));
const browser = await chromium.launch(launchOpts);
const ctx = await browser.newContext({ viewport: { width: 390, height: 844 }, hasTouch: true, isMobile: true, serviceWorkers: "block" });
await ctx.route(/gstatic\.com|googleapis\.com|google\.com/, x => x.abort());
await ctx.addInitScript(() => localStorage.setItem("dnd.rollcard", "1"));
const page = await ctx.newPage();
const errors = [];
page.on("pageerror", e => errors.push(e.message));
await page.goto("http://localhost:8765/#/c/kirion-thorndike/combat");
await page.waitForSelector(".sheet");
const attack = page.locator("[data-roll^='attack:'], [data-roll^='iattack:']").first();
await attack.click();
await page.waitForSelector("#roll-card.in");
ok("attack shows a center card", (await page.locator("#roll-card .rc-entry").count()) === 1);
ok("no bottom toast for the roll", (await page.locator("#toasts .roll").count()) === 0);
const big = await page.locator("#roll-card .r-total").first().evaluate(x => parseFloat(getComputedStyle(x).fontSize));
ok("total is big", big >= 48, String(big));
await sleep(5000);
ok("card stays until a tap", (await page.locator("#roll-card.in").count()) === 1);
await page.screenshot({ path: E2E_OUT + "rollcard-attack.png" });
const dmgBtn = page.locator("#roll-card [data-hit-dmg]").first();
if (await dmgBtn.count()) await dmgBtn.click();
else await page.evaluate(() => document.querySelector("[data-roll^='dmg:'], [data-roll^='idmg:']").click());
await page.waitForSelector("#roll-card .roll.dmg");
ok("damage buttons are spent after the damage roll", (await page.locator("#roll-card [data-hit-dmg], #roll-card [data-crit]").count()) === 0);
ok("damage joins the attack card", (await page.locator("#roll-card .rc-entry").count()) === 2 && (await page.locator("#roll-card .rc-entry").first().locator(".roll:not(.dmg)").count()) === 1);
await page.screenshot({ path: E2E_OUT + "rollcard-both.png" });
await page.mouse.click(20, 300);
await sleep(300);
ok("tap anywhere closes the card", (await page.locator("#roll-card.in").count()) === 0);
await attack.click();
await page.waitForSelector("#roll-card.in");
await page.evaluate(() => {
  const b = document.querySelector("[data-roll^='dmg:'], [data-roll^='idmg:']");
  b.dispatchEvent(new PointerEvent("pointerdown", { bubbles: true }));
  b.click();
});
await page.waitForSelector("#roll-card .roll.dmg");
ok("damage chip on the sheet also joins the attack", (await page.locator("#roll-card .rc-entry").count()) === 2);
ok("and spends the attack damage buttons", (await page.locator("#roll-card [data-hit-dmg]").count()) === 0);
await page.goto("http://localhost:8765/#/c/kirion-thorndike/character");
await page.waitForSelector(".sheet");
await page.click("[data-roll='check:str']");
await page.waitForSelector("#roll-card.in");
await page.evaluate(() => {
  const b = document.querySelector("[data-roll='check:dex']");
  b.dispatchEvent(new PointerEvent("pointerdown", { bubbles: true }));
  b.click();
});
await sleep(300);
ok("a new check replaces the card", (await page.locator("#roll-card .rc-entry").count()) === 1 && /Ловкость/.test(await page.locator("#roll-card .r-label").innerText()));
await page.click("#roll-card .r-total");
await sleep(300);
ok("tap on the card itself closes it", (await page.locator("#roll-card.in").count()) === 0);
ok("no errors", errors.length === 0, errors.join("|"));
await browser.close();
console.log(r.join("\n"));
