import { chromium, launchOpts } from "./env.mjs";
const r = [];
const ok = (n, c, x = "") => r.push(`${c ? "PASS" : "FAIL"} ${n}${x ? " :: " + x : ""}`);
const sleep = ms => new Promise(res => setTimeout(res, ms));
const browser = await chromium.launch(launchOpts);
const ctx = await browser.newContext({ viewport: { width: 390, height: 844 }, serviceWorkers: "block", isMobile: true, hasTouch: true });
await ctx.route(/gstatic\.com|googleapis\.com|google\.com/, x => x.abort());
const page = await ctx.newPage();
const errors = [];
page.on("pageerror", e => errors.push(e.message));
const shake = () => page.evaluate(async () => {
  const jolt = () => window.dispatchEvent(new DeviceMotionEvent("devicemotion", { acceleration: { x: 22, y: 0, z: 0 }, accelerationIncludingGravity: { x: 22, y: 0, z: 9.8 } }));
  jolt();
  await new Promise(r => setTimeout(r, 200));
  jolt();
});
await page.goto("http://localhost:8765/#/c/kirion-thorndike/combat");
await page.waitForSelector(".sheet");
await shake();
await sleep(400);
ok("off by default: shaking does nothing", (await page.locator("#toasts .toast", { hasText: "Встряска" }).count()) === 0);
await page.click("[data-act=menu]");
ok("switch is off", (await page.locator("[data-sw=shake-toggle]:not(.on)").count()) === 1);
await page.click("[data-sw=shake-toggle]");
await sleep(200);
ok("switch turns on", (await page.locator("[data-sw=shake-toggle].on").count()) === 1);
await page.keyboard.press("Escape");
await sleep(300);
await shake();
await sleep(900);
const t = await page.locator("#toasts .toast", { hasText: "Встряска" }).first().innerText().catch(() => "");
ok("shake rolls a d20", /Встряска: d20/.test(t) && /\d/.test(t), t.replace(/\n/g, " "));
await page.reload();
await page.waitForSelector(".sheet");
await shake();
await sleep(900);
ok("setting survives reload", (await page.locator("#toasts .toast", { hasText: "Встряска" }).count()) >= 1);
ok("no errors", errors.length === 0, errors.join("|"));
await browser.close();
console.log(r.join("\n"));
