import { chromium, launchOpts, E2E_OUT } from "./env.mjs";
const r = [];
const ok = (n, c, x = "") => r.push(`${c ? "PASS" : "FAIL"} ${n}${x ? " :: " + x : ""}`);
const sleep = ms => new Promise(res => setTimeout(res, ms));
const browser = await chromium.launch(launchOpts);
const ctx = await browser.newContext({ viewport: { width: 390, height: 844 }, serviceWorkers: "block", isMobile: true, hasTouch: true });
await ctx.route(/gstatic\.com|googleapis\.com|google\.com/, x => x.abort());
const page = await ctx.newPage();
const errors = [];
page.on("pageerror", e => errors.push(e.message));
await page.goto("http://localhost:8765/#/");
await page.waitForSelector(".ch-card.tpl");
const secs = await page.locator(".home-sec-h h2").allInnerTexts();
ok("ready characters come right after my characters", secs[0] === "Персонажи" && secs[1] === "Готовые персонажи", secs.join(","));
ok("three ready characters", (await page.locator(".ch-card.tpl").count()) === 3);
const before = await page.locator(".home-sec").first().locator(".ch-card:not(.new)").count();
await page.screenshot({ path: E2E_OUT + "tpl-home.png", fullPage: true });
await page.click("[data-tpl-take=wizard]");
await page.waitForSelector(".sheet");
await sleep(400);
ok("taking opens my own copy", /Каэлен Звездочёт/.test(await page.locator(".topbar").innerText()));
ok("the copy is editable", (await page.locator(".sheet.viewer").count()) === 0);
await page.click(".tab[data-tab=spells]");
ok("copy has the spellbook", (await page.locator(".tile", { hasText: "Волшебная стрела" }).count()) === 1);
ok("copy passes the sheet check", (await page.locator("[data-act=menu].has-issues").count()) === 0);
await page.goto("http://localhost:8765/#/");
await page.waitForSelector(".ch-card.tpl");
ok("template stays after taking", (await page.locator(".ch-card.tpl").count()) === 3);
ok("my copy is listed first", (await page.locator(".home-sec").first().locator(".ch-card:not(.new)").count()) === before + 1);
page.on("dialog", d => d.accept());
await page.click("[data-tpl-hide=fighter]");
await page.waitForSelector(".modal-back.in");
await page.click(".modal-back.in .btn.gold, .modal-back.in .btn.danger, .modal-back.in [data-ok]");
await sleep(400);
ok("owner can hide a template", (await page.locator(".ch-card.tpl:not(.arch)").count()) === 2);
await page.reload();
await page.waitForSelector(".ch-card.tpl");
ok("hidden stays hidden after reload", (await page.locator(".ch-card.tpl:not(.arch)").count()) === 2);
await page.click("[data-tpl-hidden]");
await page.click(".ch-card.tpl.arch [data-tpl-hide=fighter]");
await sleep(400);
ok("and can bring it back", (await page.locator(".ch-card.tpl:not(.arch)").count()) === 3);
ok("no errors", errors.length === 0, errors.join("|"));
await browser.close();
console.log(r.join("\n"));
