import { chromium, launchOpts, E2E_OUT } from "./env.mjs";
const r = [];
const ok = (n, c, x = "") => r.push(`${c ? "PASS" : "FAIL"} ${n}${x ? " :: " + x : ""}`);
const sleep = ms => new Promise(res => setTimeout(res, ms));
const browser = await chromium.launch(launchOpts);
const ctx = await browser.newContext({ viewport: { width: 390, height: 844 }, serviceWorkers: "block", isMobile: true, hasTouch: true });
await ctx.route(/gstatic\.com|googleapis\.com|google\.com/, x => x.abort());
const page = await ctx.newPage();
const errors = [];
page.on("pageerror", e => errors.push(e.message));
await page.goto("http://localhost:8765/#/");
await page.waitForSelector(".ch-card.tpl");
const secs = await page.locator(".home-sec-h h2").allInnerTexts();
ok("ready characters come right after my characters", secs[0] === "Персонажи" && secs[1] === "Готовые персонажи", secs.join(","));
ok("three ready characters", (await page.locator(".ch-card.tpl").count()) === 3);
const before = await page.locator(".home-sec").first().locator(".ch-card:not(.new)").count();
await page.screenshot({ path: E2E_OUT + "tpl-home.png", fullPage: true });
await page.click(".ch-card.tpl a[href='#/t/cleric']");
await page.waitForSelector(".sheet");
await sleep(400);
ok("preview opens the ready sheet read-only", (await page.locator(".sheet.viewer").count()) === 1 && /Сестра Илва/.test(await page.locator(".topbar").innerText()));
ok("preview explains and offers to take", /готовый персонаж/.test(await page.locator(".ro-bar").innerText()) && (await page.locator(".ro-bar [data-act=tpl-take]").count()) === 1);
await page.click(".tab[data-tab=spells]");
await sleep(300);
ok("preview tabs keep the preview address", page.url().endsWith("#/t/cleric/spells"), page.url());
ok("preview shows the spells", (await page.locator(".tile", { hasText: "Лечение ран" }).count()) === 1);
await page.reload();
await page.waitForSelector(".sheet");
ok("preview survives reload", (await page.locator(".tab.on[data-tab=spells]").count()) === 1 && (await page.locator(".sheet.viewer").count()) === 1);
await page.click("[data-act=menu]");
ok("no share for a preview", (await page.locator("[data-m=share]").count()) === 0);
await page.keyboard.press("Escape");
await page.goto("http://localhost:8765/#/");
await page.waitForSelector(".ch-card.tpl");
ok("preview is not added to recent", (await page.locator(".home-sec-h h2", { hasText: "Недавно открытые" }).count()) === 0);
await page.goto("http://localhost:8765/#/t/cleric");
await page.waitForSelector(".ro-bar [data-act=tpl-take]");
await page.click(".ro-bar [data-act=tpl-take]");
await page.waitForSelector(".sheet:not(.viewer)");
await sleep(300);
ok("take from preview opens my editable copy", /#\/c\//.test(page.url()) && /Сестра Илва/.test(await page.locator(".topbar").innerText()));
await page.goto("http://localhost:8765/#/");
await page.waitForSelector(".ch-card.tpl");
await page.click("[data-tpl-take=wizard]");
await page.waitForSelector(".sheet");
await sleep(400);
ok("taking opens my own copy", /Каэлен Звездочёт/.test(await page.locator(".topbar").innerText()));
ok("the copy is editable", (await page.locator(".sheet.viewer").count()) === 0);
await page.click(".tab[data-tab=spells]");
ok("copy has the spellbook", (await page.locator(".tile", { hasText: "Волшебная стрела" }).count()) === 1);
ok("copy passes the sheet check", (await page.locator("[data-act=menu].has-issues").count()) === 0);
await page.goto("http://localhost:8765/#/");
await page.waitForSelector(".ch-card.tpl");
ok("template stays after taking", (await page.locator(".ch-card.tpl").count()) === 3);
ok("my copies are listed first", (await page.locator(".home-sec").first().locator(".ch-card:not(.new)").count()) === before + 2);
page.on("dialog", d => d.accept());
await page.click("[data-tpl-hide=fighter]");
await page.waitForSelector(".modal-back.in");
await page.click(".modal-back.in .btn.gold, .modal-back.in .btn.danger, .modal-back.in [data-ok]");
await sleep(400);
ok("owner can hide a template", (await page.locator(".ch-card.tpl:not(.arch)").count()) === 2);
await page.reload();
await page.waitForSelector(".ch-card.tpl");
ok("hidden stays hidden after reload", (await page.locator(".ch-card.tpl:not(.arch)").count()) === 2);
await page.click("[data-tpl-hidden]");
await page.click(".ch-card.tpl.arch [data-tpl-hide=fighter]");
await sleep(400);
ok("and can bring it back", (await page.locator(".ch-card.tpl:not(.arch)").count()) === 3);
ok("no errors", errors.length === 0, errors.join("|"));
await browser.close();
console.log(r.join("\n"));
