import { chromium, launchOpts, E2E_OUT } from "./env.mjs";
const r = [];
const ok = (n, c, x = "") => r.push(`${c ? "PASS" : "FAIL"} ${n}${x ? " :: " + x : ""}`);
const sleep = ms => new Promise(res => setTimeout(res, ms));
const browser = await chromium.launch(launchOpts);
const ctx = await browser.newContext({ viewport: { width: 1280, height: 900 }, serviceWorkers: "block" });
await ctx.route(/gstatic\.com|googleapis\.com|google\.com/, x => x.abort());
const page = await ctx.newPage();
const errors = [];
page.on("pageerror", e => errors.push(e.message));
await page.goto("http://localhost:8765/#/c/kirion-thorndike/spells");
await page.waitForSelector(".sheet");
const temp = () => page.evaluate(() => { const t = document.querySelector(".hp-temp"); return t ? t.textContent : ""; });
await page.click(".tile:has-text('Доспех Агатиса')");
await page.click(".modal-back.in [data-x=cast]");
await sleep(300);
await page.keyboard.press("Escape");
await page.click(".tab[data-tab=combat]");
ok("agathys gives 15 temp", (await temp()).includes("+15"), await temp());
await page.click(".tab[data-tab=features]");
await page.click(".tile:has-text('Дьявольская живучесть')");
await page.click(".modal-back.in [data-x=feat-dmg]");
await sleep(300);
const t = await page.locator("#toasts .toast").allInnerTexts();
ok("lower roll keeps 15", t.some(x => x.includes("Оставил 15")), t.join(" | ").replace(/\n/g, " "));
await page.locator("#toasts [data-temp-force]").click();
await sleep(200);
await page.keyboard.press("Escape");
await page.click(".tab[data-tab=combat]");
ok("forced replace", /\+[5-8]/.test(await temp()), await temp());
await page.click(".tab[data-tab=features]");
await page.click(".tile:has-text('Благословение Тёмного')");
await page.click(".modal-back.in [data-x=feat-dmg]");
await sleep(300);
await page.keyboard.press("Escape");
await page.click(".tab[data-tab=combat]");
ok("higher roll replaces (9)", (await temp()).includes("+9"), await temp());
ok("no errors", errors.length === 0, errors.join("|"));
await browser.close();
console.log(r.join("\n"));
