import { chromium, launchOpts, E2E_OUT } from "./env.mjs";
const OUT = E2E_OUT;
const r = [];
const ok = (n, c, x = "") => r.push(`${c ? "PASS" : "FAIL"} ${n}${x ? " :: " + x : ""}`);
const sleep = ms => new Promise(res => setTimeout(res, ms));
const browser = await chromium.launch(launchOpts);
const ctx = await browser.newContext({ viewport: { width: 390, height: 844 }, hasTouch: true, isMobile: true });
await ctx.route(/gstatic\.com|googleapis\.com|google\.com/, x => x.abort());
const page = await ctx.newPage();
const errors = [];
page.on("pageerror", e => errors.push(e.message));
await page.goto("http://localhost:8765/#/c/kirion-thorndike/inventory");
await page.waitForSelector(".sheet");
await page.click("[data-act=add-item]");
await page.fill(".modal-back.in input[data-k=name]", "Палочка холода");
await page.fill(".modal-back.in input[data-k=uses]", "7");
await page.fill(".modal-back.in input[data-k=value]", "2000з");
await page.click(".modal-back.in button[type=submit]");
await sleep(300);
await page.selectOption("[data-ui=inv-sort]", "price");
await sleep(200);
const first = await page.locator(".inv-grid .slot .slot-name").nth(0).innerText();
const eqFirst = await page.locator(".inv-grid .slot").nth(0).getAttribute("class");
ok("equipped first by default", eqFirst.includes("eq"), first);
await page.click("[data-act=inv-eq-first]");
await sleep(150);
ok("price sort puts wand first", (await page.locator(".inv-grid .slot .slot-name").nth(0).innerText()) === "Палочка холода");
await page.reload();
await page.waitForSelector(".sheet");
ok("sort remembered", (await page.$eval("[data-ui=inv-sort]", s => s.value)) === "price");
await page.screenshot({ path: OUT + "m-inv.png" });
await page.click(".slot:has-text('Палочка холода')");
await page.waitForSelector(".modal-back.in [data-x=item-add-spell]");
await page.click(".modal-back.in [data-x=item-add-spell]");
await page.waitForSelector(".lib-row");
for (const name of ["Луч холода", "Метель", "Град"]) {
  await page.fill("[data-q]", name);
  await sleep(100);
  await page.locator(".lib-head", { hasText: name }).first().click();
  await sleep(150);
  await page.locator("[data-add]").dispatchEvent("click");
  await sleep(250);
}
await page.screenshot({ path: OUT + "m-lib-item.png" });
await page.keyboard.press("Escape").catch(() => {});
await page.goBack();
await sleep(400);
await page.click(".slot:has-text('Палочка холода')");
await sleep(300);
const linked = await page.$$eval(".modal-back.in [data-x=open-spell]", bs => bs.map(b => b.textContent.trim()));
ok("three spells linked", linked.length === 3, linked.join(","));
await page.locator(".modal-back.in [data-x=open-spell]", { hasText: "Град" }).click();
await sleep(400);
const btns = await page.$$eval(".modal-back.in [data-x=cast]", bs => bs.map(b => b.textContent.trim()));
ok("ice storm 3-5 charges", btns.join("|") === "3 заряда|4 заряда|5 зарядов", btns.join("|"));
await page.screenshot({ path: OUT + "m-hail.png" });
ok("no errors", errors.length === 0, errors.join("|"));
await browser.close();
console.log(r.join("\n"));
