import { chromium, launchOpts, E2E_OUT } from "./env.mjs";
const OUT = E2E_OUT;
const r = [];
const ok = (n, c, x = "") => r.push(`${c ? "PASS" : "FAIL"} ${n}${x ? " :: " + x : ""}`);
const sleep = ms => new Promise(res => setTimeout(res, ms));
const browser = await chromium.launch(launchOpts);
const ctx = await browser.newContext({ viewport: { width: 1280, height: 900 } });
await ctx.route(/gstatic\.com|googleapis\.com|google\.com/, x => x.abort());
const page = await ctx.newPage();
const errors = [];
page.on("pageerror", e => errors.push(e.message));
await page.goto("http://localhost:8765/#/c/kirion-thorndike/inventory");
await page.waitForSelector(".sheet");
await page.click("[data-act=add-item]");
await page.fill(".modal-back.in input[data-k=name]", "Палочка холода");
await page.selectOption(".modal-back.in select[data-k=type]", "wand");
await page.selectOption(".modal-back.in select[data-k=rarity]", "rare");
await page.fill(".modal-back.in input[data-k=uses]", "7");
await page.fill(".modal-back.in input[data-k=breakOn]", "20");
await page.click(".modal-back.in button[type=submit]");
await sleep(300);
await page.click(".tab[data-tab=spells]");
await page.click("[data-act=add-spell]");
await page.fill(".modal-back.in input[data-k=name]", "Луч холода");
await page.fill(".modal-back.in input[data-k=level]", "1");
await page.selectOption(".modal-back.in select[data-k=cost]", "item");
const optText = await page.$$eval(".modal-back.in select[data-k=itemId] option", os => os.map(o => o.textContent));
ok("item select lists items", optText.includes("Палочка холода"), optText.slice(0, 4).join(","));
await page.selectOption(".modal-back.in select[data-k=itemId]", { label: "Палочка холода" });
await page.fill(".modal-back.in input[data-k=charges]", "1");
await page.fill(".modal-back.in input[data-k=maxCharges]", "3");
await page.fill(".modal-back.in input[data-k=upcast]", "1d8");
await page.click(".modal-back.in [data-dl-add]");
await page.fill(".modal-back.in [data-dl-dice]", "1d8");
await page.selectOption(".modal-back.in [data-dl-type]", "cold");
await page.click(".modal-back.in button[type=submit]");
await sleep(300);
await page.click(".tile:has-text('Луч холода')");
await page.waitForSelector(".modal-back.in [data-x=cast]");
const castBtns = await page.$$eval(".modal-back.in [data-x=cast]", bs => bs.map(b => b.textContent.trim()));
ok("charge buttons", castBtns.length === 3, castBtns.join(" | "));
await page.click(".modal-back.in [data-x=cast][data-lvl='3']");
await sleep(200);
const dmgBtn = await page.locator(".modal-back.in [data-x=spell-dmg]").innerText();
ok("damage label shows extra", dmgBtn.includes("+2"), dmgBtn);
const cardDice = await page.locator(".modal-back.in .dice-texts").innerText();
ok("card dice scaled", cardDice.includes("3d8"), cardDice);
await page.screenshot({ path: OUT + "w-spell.png" });
for (let i = 0; i < 2; i++) { await page.click(".modal-back.in [data-x=cast][data-lvl='2']"); await sleep(150); }
const toasts = await page.locator("#toasts .toast").allInnerTexts();
ok("last charge triggers break roll", toasts.some(t => t.includes("Последний заряд, d20")), toasts.join(" | ").replace(/\n/g, " "));
await page.keyboard.press("Escape");
await page.click(".tab[data-tab=inventory]");
const ic = await page.$eval(".slot:has-text('Палочка холода') .slot-ic .ic", s => s.outerHTML.length);
ok("wand icon", ic > 0);
await page.click(".slot:has-text('Палочка холода')");
await sleep(300);
ok("item lists its spell", (await page.locator(".modal-back.in [data-x=open-spell]").count()) === 1);
await page.screenshot({ path: OUT + "w-item.png" });
await page.click(".modal-back.in [data-x=open-spell]");
await sleep(400);
const h3s = await page.$$eval(".modal-back.in h3", hs => hs.map(h => h.textContent));
ok("open spell from item", h3s.includes("Луч холода"), h3s.join(","));
await page.keyboard.press("Escape");
await sleep(300);
await page.click(".tab[data-tab=notes]");
await page.click("[data-act=notes-section][data-k=people]");
await page.click("[data-act=edit-note] >> nth=0");
await page.fill(".modal-back.in input[data-k=tags]", "порт, должник");
await page.click(".modal-back.in button[type=submit]");
await sleep(300);
ok("tag chips", (await page.locator(".note-filters .tag").count()) === 2);
await page.click(".note-filters .tag >> nth=0");
ok("tag filter", (await page.locator("[data-notes-list] .note").count()) === 1);
await page.click("[data-act=people-att][data-k=hostile]");
await page.fill("[data-ui=notes-q]", "мефист");
await sleep(150);
const n = await page.locator("[data-notes-list] .note").count();
ok("search all sections", n >= 1, String(n));
await page.screenshot({ path: OUT + "w-notes.png" });
ok("no errors", errors.length === 0, errors.join(" | "));
await browser.close();
console.log(r.join("\n"));
