import { readFileSync } from "node:fs";
import { initializeTestEnvironment, assertSucceeds, assertFails } from "@firebase/rules-unit-testing";
import { doc, getDoc, setDoc, updateDoc, deleteDoc, collection, query, where, getDocs, addDoc, FieldPath, orderBy, limit } from "firebase/firestore";
const { kirion } = await import(new URL("../../js/seed.js", import.meta.url).href);
const env = await initializeTestEnvironment({ projectId: "demo-final-check", firestore: { rules: readFileSync(new URL("../../firestore.rules", import.meta.url), "utf8").replace("ВСТАВЬ_СВОЙ_UID", "admin1"), host: "127.0.0.1", port: Number(process.env.FIRESTORE_PORT || 8080) } });
const g = (uid, email) => env.authenticatedContext(uid, { email, email_verified: true, firebase: { sign_in_provider: "google.com" } }).firestore();
const anonUser = uid => env.authenticatedContext(uid, { firebase: { sign_in_provider: "anonymous" } }).firestore();
const pub = env.unauthenticatedContext().firestore();
const alice = g("alice", "alice@gmail.com"), bob = g("bob", "bob@gmail.com"), carol = g("carol", "carol@gmail.com"), admin = g("admin1", "Owner.Site@gmail.com");
const now = () => Date.now();
const who = (uid, name) => ({ id: "dev123", uid, name, kind: "phone", os: "Android", browser: "Chrome", gpu: "Adreno 740" });
const createData = (uid, name) => ({ ...kirion(), createdAt: now(), updatedAt: now(), updatedBy: who(uid, name), archived: false, ownerUid: uid, ownerName: name });
let pass = 0, fail = 0;
const t = async (label, p) => { try { await p; pass++; console.log("ok  ", label); } catch (e) { fail++; console.log("FAIL", label, String(e.message).slice(0, 160)); } };
await env.clearFirestore();
await env.withSecurityRulesDisabled(async ctx => {
  const db = ctx.firestore();
  await setDoc(doc(db, "characters", "kirion-thorndike"), { ...kirion(), createdAt: 1, updatedAt: 2, updatedBy: { id: "x", kind: "phone", os: "iOS", browser: "Safari", gpu: "Apple GPU", name: "" } });
});
console.log("--- app flows that must keep working (current client code) ---");
await t("detectRules: anyone reads meta/rules", assertSucceeds(getDoc(doc(pub, "meta", "rules"))));
await t("admin probe: admin reads admin/probe", assertSucceeds(getDoc(doc(admin, "admin", "probe"))));
await t("admin probe: others denied", assertFails(getDoc(doc(alice, "admin", "probe"))));
await t("saveProfile: get + merge-set own profile", (async () => { await getDoc(doc(alice, "users", "alice")); await setDoc(doc(alice, "users", "alice"), { name: "Alice A", email: "alice@gmail.com", photo: "https://lh3.googleusercontent.com/a/x=s96-c", lastSeen: now(), createdAt: now() }, { merge: true }); })());
await t("ban watch: read own (missing) ban", assertSucceeds(getDoc(doc(alice, "bans", "alice"))));
await t("createChar with full seed + who() (7 keys)", assertSucceeds(setDoc(doc(alice, "characters", "a1"), createData("alice", "Alice A"))));
await t("home: where(ownerUid==me)", assertSucceeds(getDocs(query(collection(alice, "characters"), where("ownerUid", "==", "alice")))));
await t("saveChanges field patch", assertSucceeds(updateDoc(doc(alice, "characters", "a1"), new FieldPath("hp", "current"), 7, new FieldPath("info", "level"), 6, "updatedAt", now(), "updatedBy", who("alice", "Alice A"))));
await t("addHistory with full body (no portrait)", (async () => { const c = createData("alice", "Alice A"); delete c.portrait; delete c.updatedBy; await addDoc(collection(alice, "characters", "a1", "history"), { at: now(), reason: "Перед правкой", by: who("alice", "Alice A"), data: c }); })());
await t("listHistory by owner", assertSucceeds(getDocs(query(collection(alice, "characters", "a1", "history"), orderBy("at", "desc"), limit(40)))));
await t("saveAcl: acl then invite", (async () => { await setDoc(doc(alice, "characters", "a1", "acl", "main"), { emails: ["bob@gmail.com"], updatedAt: now() }); await setDoc(doc(alice, "invites", "bob@gmail.com", "chars", "a1"), { name: "Кирион", ownerName: "Alice A", ownerUid: "alice", at: now() }); })());
await t("editor: cannot read other editors in acl", assertFails(getDoc(doc(bob, "characters", "a1", "acl", "main"))));
await t("editor: reads own invite", assertSucceeds(getDoc(doc(bob, "invites", "bob@gmail.com", "chars", "a1"))));
await t("editor: invites list", assertSucceeds(getDocs(collection(bob, "invites", "bob@gmail.com", "chars"))));
await t("editor: field patch", assertSucceeds(updateDoc(doc(bob, "characters", "a1"), new FieldPath("hp", "temp"), 3, "updatedAt", now(), "updatedBy", who("bob", "Bob B"))));
await t("editor: history read + write", (async () => { await getDocs(collection(bob, "characters", "a1", "history")); await addDoc(collection(bob, "characters", "a1", "history"), { at: now(), reason: "", by: who("bob", "Bob B"), data: { name: "x" } }); })());
await t("viewer (signed out) opens link sheet", assertSucceeds(getDoc(doc(pub, "characters", "a1"))));
await t("viewer 'Копия себе' (createChar of copy)", assertSucceeds(setDoc(doc(carol, "characters", "c-copy"), createData("carol", "Carol"))));
await t("non-editor getAcl denied (sheet treats as viewer)", assertFails(getDoc(doc(carol, "characters", "a1", "acl", "main"))));
await t("admin claims legacy kirion (claimCharacter)", assertSucceeds(updateDoc(doc(admin, "characters", "kirion-thorndike"), { ownerUid: "admin1", ownerName: "Weiss", updatedAt: now(), updatedBy: who("admin1", "Weiss") })));
await t("admin list all + users + bans", (async () => { await getDocs(collection(admin, "characters")); await getDocs(collection(admin, "users")); await getDocs(collection(admin, "bans")); })());
await t("owner sets visibility private (revoke link)", assertSucceeds(updateDoc(doc(alice, "characters", "a1"), "visibility", "private", "updatedAt", now(), "updatedBy", who("alice", "Alice A"))));
await t("editor still reads private sheet", assertSucceeds(getDoc(doc(bob, "characters", "a1"))));
await t("missing doc reads as not-found", assertSucceeds(getDoc(doc(pub, "characters", "nope"))));
await t("deleteCharacter sequence (history, invites, acl, char)", (async () => {
  const h = await getDocs(collection(alice, "characters", "a1", "history"));
  await Promise.all(h.docs.map(d => deleteDoc(d.ref)));
  await deleteDoc(doc(alice, "invites", "bob@gmail.com", "chars", "a1"));
  await deleteDoc(doc(alice, "characters", "a1", "acl", "main"));
  await deleteDoc(doc(alice, "characters", "a1"));
})());
console.log("--- gaps found in the shipped rules: must be denied now ---");
await env.withSecurityRulesDisabled(async ctx => {
  const db = ctx.firestore();
  await setDoc(doc(db, "characters", "c1"), { ...createData("alice", "Alice A"), visibility: "private" });
  await setDoc(doc(db, "characters", "c1", "acl", "main"), { emails: ["bob@gmail.com"] });
  await addDoc(collection(db, "characters", "c1", "history"), { at: 1, reason: "", by: who("bob", "Боб Иванов"), data: { name: "old" } });
});
await t("anonymous-provider account creates characters", assertFails(setDoc(doc(anonUser("anon1"), "characters", "spam1"), createData("anon1", "Игрок"))));
await t("private (unshared) character read by stranger", assertFails(getDoc(doc(pub, "characters", "c1"))));
await t("signed-out visitor reads edit history", assertFails(getDocs(collection(pub, "characters", "c1", "history"))));
await t("editor forges updatedBy as owner", assertFails(updateDoc(doc(bob, "characters", "c1"), "name", "X", "updatedAt", now(), "updatedBy", who("alice", "Alice A"))));
await t("editor writes history as someone else", assertFails(addDoc(collection(bob, "characters", "c1", "history"), { at: now(), reason: "", by: who("alice", "Alice"), data: {} })));
await t("editor rewrites ownerName", assertFails(updateDoc(doc(bob, "characters", "c1"), "ownerName", "Не Алиса", "updatedAt", now(), "updatedBy", who("bob", "Bob"))));
await t("editor changes visibility", assertFails(updateDoc(doc(bob, "characters", "c1"), "visibility", "link", "updatedAt", now(), "updatedBy", who("bob", "Bob"))));
await t("future updatedAt", assertFails(updateDoc(doc(bob, "characters", "c1"), "updatedAt", now() + 1e12, "updatedBy", who("bob", "Bob"))));
await t("900 KB history payload", assertFails(addDoc(collection(alice, "characters", "c1", "history"), { at: now(), reason: "", by: who("alice", "a"), data: { portrait: "A".repeat(900000) } })));
await t("profile with someone else's email", assertFails(setDoc(doc(carol, "users", "carol"), { name: "Weiss", email: "admin@example.com", lastSeen: now() })));
await t("invite spam to an email that is not an editor", assertFails(setDoc(doc(alice, "invites", "victim@gmail.com", "chars", "c1"), { name: "любой текст", ownerName: "Поддержка", ownerUid: "alice", at: now() })));
await t("invitee can dismiss own invite", (async () => { await env.withSecurityRulesDisabled(c => setDoc(doc(c.firestore(), "invites", "bob@gmail.com", "chars", "c1"), { name: "x", ownerName: "a", ownerUid: "alice", at: 1 })); await deleteDoc(doc(bob, "invites", "bob@gmail.com", "chars", "c1")); })());
await t("admin restore of a pre-claim version cannot orphan a sheet", (async () => { const { deleteField } = await import("firebase/firestore"); await env.withSecurityRulesDisabled(c => setDoc(doc(c.firestore(), "characters", "k2"), { ...createData("admin1", "Weiss") })); await assertFails(updateDoc(doc(admin, "characters", "k2"), "ownerUid", deleteField(), "ownerName", deleteField(), "updatedAt", now(), "updatedBy", who("admin1", "Weiss"))); })());
console.log("--- lead corrections ---");
await env.withSecurityRulesDisabled(async ctx => {
  const db = ctx.firestore();
  await setDoc(doc(db, "characters", "d1"), { ...createData("dave", "Dave") });
  await addDoc(collection(db, "characters", "d1", "history"), { at: 1, reason: "", by: who("dave", "Dave"), data: { name: "old" } });
  await setDoc(doc(db, "characters", "d1", "acl", "main"), { emails: [] });
  await setDoc(doc(db, "bans", "dave"), { at: 1 });
});
const dave = g("dave", "dave@gmail.com");
await t("phone clock 30 min ahead still saves", assertSucceeds(updateDoc(doc(alice, "characters", "c1"), "name", "Y", "updatedAt", now() + 30 * 60000, "updatedBy", who("alice", "Alice A"))));
await t("updatedAt 2 h ahead denied", assertFails(updateDoc(doc(alice, "characters", "c1"), "name", "Z", "updatedAt", now() + 2 * 3600000, "updatedBy", who("alice", "Alice A"))));
await t("banned owner cannot edit", assertFails(updateDoc(doc(dave, "characters", "d1"), "name", "spam", "updatedAt", now(), "updatedBy", who("dave", "Dave"))));
await t("banned owner cannot create", assertFails(setDoc(doc(dave, "characters", "d2"), createData("dave", "Dave"))));
await t("banned owner can still delete own data (account deletion)", (async () => {
  const h = await getDocs(collection(dave, "characters", "d1", "history"));
  await Promise.all(h.docs.map(d => deleteDoc(d.ref)));
  await deleteDoc(doc(dave, "characters", "d1", "acl", "main"));
  await deleteDoc(doc(dave, "characters", "d1"));
})());
await t("stranger cannot delete someone's sheet", assertFails(deleteDoc(doc(carol, "characters", "kirion-thorndike"))));
await t("public updatedBy shape {uid,name,kind} accepted", assertSucceeds(updateDoc(doc(alice, "characters", "c1"), "name", "W", "updatedAt", now(), "updatedBy", { uid: "alice", name: "Alice", kind: "phone" })));
console.log(`\n${pass} passed, ${fail} failed`);
await env.cleanup();
process.exit(fail ? 1 : 0);
