server {
  listen 80;
  root /usr/share/nginx/html;
  index index.html;
  charset utf-8;
  charset_types application/javascript application/json text/css;
  types {
    application/manifest+json webmanifest;
    application/wasm wasm;
    audio/mp4 m4a;
    audio/ogg ogg;
    image/webp webp;
  }
  include /etc/nginx/mime.types;
  location / {
    add_header Cache-Control "no-store";
    try_files $uri $uri/ =404;
  }
  location ~ /\.git { deny all; }
}
